[[correlations]]
entity = "original"
fields = [
    "longitude",
    "latitude",
]
matrix = [
    [
    1.0,
    -0.3307411674347158,
],
    [
    -0.3307411674347158,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gender",
    "address",
]
matrix = [
    [
    1.0,
    0.9449111825230692,
],
    [
    0.9449111825230692,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gender",
    "first_name",
]
matrix = [
    [
    1.0,
    0.999999999999999,
],
    [
    0.999999999999999,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gender",
    "last_name",
]
matrix = [
    [
    1.0,
    0.958980113006967,
],
    [
    0.958980113006967,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gender",
    "type",
]
matrix = [
    [
    1.0,
    0.48181205582971576,
],
    [
    0.48181205582971576,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gender",
    "neighborhood",
]
matrix = [
    [
    1.0,
    0.7379992257061366,
],
    [
    0.7379992257061366,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "address",
    "first_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "address",
    "last_name",
]
matrix = [
    [
    1.0,
    0.9635157357819797,
],
    [
    0.9635157357819797,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "address",
    "race",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "address",
    "type",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "address",
    "neighborhood",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "first_name",
    "last_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "first_name",
    "race",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "first_name",
    "type",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "first_name",
    "neighborhood",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "last_name",
    "race",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "last_name",
    "type",
]
matrix = [
    [
    1.0,
    0.9358266959957232,
],
    [
    0.9358266959957232,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "last_name",
    "neighborhood",
]
matrix = [
    [
    1.0,
    0.9578190943061314,
],
    [
    0.9578190943061314,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "race",
    "type",
]
matrix = [
    [
    1.0,
    0.3150311720706672,
],
    [
    0.3150311720706672,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "race",
    "neighborhood",
]
matrix = [
    [
    1.0,
    0.7418451110273773,
],
    [
    0.7418451110273773,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "type",
    "neighborhood",
]
matrix = [
    [
    1.0,
    0.8150304849255793,
],
    [
    0.8150304849255793,
    1.0,
],
]
conditional = []
