[[constraints]]
table = "original"
type = "range"
field = "age"
min = 15.0
max = 87.0

[[constraints]]
table = "original"
type = "range"
field = "longitude"
min = -118.4717452
max = -117.7306469

[[constraints]]
table = "original"
type = "range"
field = "latitude"
min = 33.7898575
max = 34.287098

[[constraints]]
table = "original"
type = "check"
expr = "longitude <= age"

[[constraints]]
table = "original"
type = "check"
expr = "longitude <= latitude"
