[[constraints]]
table = "original"
type = "range"
field = "yield"
min = 14.43333
max = 65.7667

[[constraints]]
table = "original"
type = "range"
field = "year"
min = 1931.0
max = 1932.0

[[constraints]]
table = "original"
type = "check"
expr = "yield <= year"
