[[constraints]]
table = "original"
type = "range"
field = "total exports"
min = 13.31
max = 16472.88

[[constraints]]
table = "original"
type = "range"
field = "beef"
min = 0.1
max = 961.0

[[constraints]]
table = "original"
type = "range"
field = "pork"
min = 0.0
max = 1895.6

[[constraints]]
table = "original"
type = "range"
field = "poultry"
min = 0.0
max = 630.4

[[constraints]]
table = "original"
type = "range"
field = "dairy"
min = 0.19
max = 929.95

[[constraints]]
table = "original"
type = "range"
field = "fruits fresh"
min = 0.0
max = 2791.8

[[constraints]]
table = "original"
type = "range"
field = "fruits proc"
min = 0.0
max = 5944.6

[[constraints]]
table = "original"
type = "range"
field = "total fruits"
min = 0.0
max = 8736.4

[[constraints]]
table = "original"
type = "range"
field = "veggies fresh"
min = 0.0
max = 803.2

[[constraints]]
table = "original"
type = "range"
field = "veggies proc"
min = 0.0
max = 1303.5

[[constraints]]
table = "original"
type = "range"
field = "total veggies"
min = 0.0
max = 2106.79

[[constraints]]
table = "original"
type = "range"
field = "corn"
min = 0.0
max = 2529.8

[[constraints]]
table = "original"
type = "range"
field = "wheat"
min = 0.0
max = 1664.5

[[constraints]]
table = "original"
type = "range"
field = "cotton"
min = 0.0
max = 2308.76

[[constraints]]
table = "original"
type = "check"
expr = "beef <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "pork <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "poultry <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "dairy <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "fruits fresh <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "fruits proc <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "total fruits <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "veggies fresh <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "veggies proc <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "total veggies <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "corn <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "wheat <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "cotton <= total exports"

[[constraints]]
table = "original"
type = "check"
expr = "fruits fresh <= fruits proc"

[[constraints]]
table = "original"
type = "check"
expr = "fruits fresh <= total fruits"

[[constraints]]
table = "original"
type = "check"
expr = "fruits proc <= total fruits"

[[constraints]]
table = "original"
type = "check"
expr = "veggies fresh <= veggies proc"

[[constraints]]
table = "original"
type = "check"
expr = "veggies fresh <= total veggies"

[[constraints]]
table = "original"
type = "check"
expr = "veggies proc <= total veggies"
