[[constraints]]
table = "original"
type = "range"
field = "pop"
min = 7094.0
max = 8287238.0

[[constraints]]
table = "original"
type = "range"
field = "lat"
min = 24.833333
max = 49.1

[[constraints]]
table = "original"
type = "range"
field = "lon"
min = -124.2639442
max = -68.0119714

[[constraints]]
table = "original"
type = "check"
expr = "lat <= pop"

[[constraints]]
table = "original"
type = "check"
expr = "lon <= pop"

[[constraints]]
table = "original"
type = "check"
expr = "lon <= lat"
