[[correlations]]
entity = "original"
fields = [
    "Score",
    "Year",
]
matrix = [
    [
    1.0,
    0.574117754057526,
],
    [
    0.574117754057526,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Score",
    "Year",
]
matrix = [
    [
    1.0,
    0.6588321630200948,
],
    [
    0.6588321630200948,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Encoder",
    "Model",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []
