[[correlations]]
entity = "original"
fields = [
    "Year",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.9021745379694497,
],
    [
    0.9021745379694497,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Year",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.896117410433818,
],
    [
    0.896117410433818,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Year",
    "Spending_USD",
]
matrix = [
    [
    1.0,
    0.8262733812538644,
],
    [
    0.8262733812538644,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Year",
    "Spending_USD",
]
matrix = [
    [
    1.0,
    0.9315976070574148,
],
    [
    0.9315976070574148,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Life_Expectancy",
    "Spending_USD",
]
matrix = [
    [
    1.0,
    0.5794304588530952,
],
    [
    0.5794304588530952,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Life_Expectancy",
    "Spending_USD",
]
matrix = [
    [
    1.0,
    0.7474072371099253,
],
    [
    0.7474072371099253,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "Spending_USD"
given = "Country"

[[correlations.distributions]]
when = "USA"
distribution = "uniform"

[correlations.distributions.params]
max = 11859.179
min = 326.961

[[correlations.distributions]]
when = "Canada"
distribution = "uniform"

[correlations.distributions.params]
max = 5828.324
min = 313.391

[[correlations.distributions]]
when = "France"
distribution = "uniform"

[correlations.distributions.params]
max = 5468.418
min = 192.143

[[correlations.distributions]]
when = "Great Britain"
distribution = "uniform"

[correlations.distributions.params]
max = 5018.7
min = 123.993

[[correlations.distributions]]
when = "Germany"
distribution = "uniform"

[correlations.distributions.params]
max = 6938.983
min = 252.311

[[correlations.distributions]]
when = "Japan"
distribution = "uniform"

[correlations.distributions.params]
max = 4665.641
min = 150.437

[correlations.default]
kind = "gamma"

[correlations.default.params]
scale = 1720.9015305310731
shape = 1.6208590995027436
