[[constraints]]
table = "original"
type = "range"
field = "Year"
min = 1970.0
max = 2020.0

[[constraints]]
table = "original"
type = "range"
field = "Spending_USD"
min = 123.993
max = 11859.179

[[constraints]]
table = "original"
type = "range"
field = "Life_Expectancy"
min = 70.6
max = 84.7

[[constraints]]
table = "original"
type = "check"
expr = "Life_Expectancy <= Year"

[[constraints]]
table = "original"
type = "check"
expr = "Life_Expectancy <= Spending_USD"
