[table]
name = "original"
count = 520

[table.stats]
source_rows = 520

[table.sort_by]
column = "id"
direction = "asc"

[[columns]]
name = "name"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 520

[columns.stats]
distinct_count = 52
null_rate = 0.0
min_length = 4
max_length = 20
avg_length = 8.711538461538462

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "region"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 520

[columns.stats]
distinct_count = 5
null_rate = 0.0
min_length = 4
max_length = 9
avg_length = 5.903846153846154

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "id"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 520

[columns.stats]
distinct_count = 52
null_rate = 0.0
min = 1.0
max = 72.0
mean = 29.78846153846154
std = 16.628476327940696

[columns.stats.percentiles]
p25 = 17.0
p50 = 30.0
p75 = 42.0
p95 = 55.0
p99 = 72.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "pct"
data_type = "float"
nullable = false
precision = 3

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 520

[columns.stats]
distinct_count = 165
null_rate = 0.0
min = 0.006
max = 0.289
mean = 0.0999961538461539
std = 0.04743221493964136

[columns.stats.percentiles]
p25 = 0.059
p50 = 0.103
p75 = 0.13
p95 = 0.185
p99 = 0.199

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "total"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 520

[columns.stats]
distinct_count = 52
null_rate = 0.0
min = 222679.0
max = 12581722.0
mean = 2249722.653846154
std = 2375082.223335015

[columns.stats.percentiles]
p25 = 729572.0
p50 = 1693399.0
p75 = 2528592.0
p95 = 7214163.0
p99 = 12581722.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "group"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 5
row_count = 520

[columns.stats]
distinct_count = 10
null_rate = 0.0
min_length = 6
max_length = 16
avg_length = 12.9

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[constraints]]
type = "range"
field = "id"
min = 1.0
max = 72.0

[[constraints]]
type = "range"
field = "pct"
min = 0.006
max = 0.289

[[constraints]]
type = "range"
field = "total"
min = 222679.0
max = 12581722.0

[[constraints]]
type = "check"
expr = "pct <= id"

[[constraints]]
type = "check"
expr = "id <= total"

[[constraints]]
type = "check"
expr = "pct <= total"
