[[constraints]]
table = "original"
type = "range"
field = "page_id"
min = 1025.0
max = 755278.0

[[constraints]]
table = "original"
type = "range"
field = "APPEARANCES"
min = 1.0
max = 4043.0

[[constraints]]
table = "original"
type = "range"
field = "Year"
min = 1939.0
max = 2013.0
