[table]
name = "original"
count = 55

[table.stats]
source_rows = 55

[[table.scaling.custom]]
name = "side"
field = "side"
cardinality = 4

[table.sort_by]
column = "year"
direction = "asc"

[[columns]]
name = "side"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 55

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 3
max_length = 6
avg_length = 4.836363636363636

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "year"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 55

[columns.stats]
distinct_count = 55
null_rate = 0.0
min = 1956.0
max = 2010.0
mean = 1983.0
std = 16.020819787597222

[columns.stats.percentiles]
p25 = 1970.0
p50 = 1983.0
p75 = 1997.0
p95 = 2007.0
p99 = 2009.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "miles"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 55

[columns.stats]
distinct_count = 55
null_rate = 0.0
min = 3675.0
max = 10067.0
mean = 7164.909090909091
std = 2160.0816708902057

[columns.stats.percentiles]
p25 = 5376.0
p50 = 6943.0
p75 = 9416.0
p95 = 9994.0
p99 = 10037.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "gas"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 55

[columns.stats]
distinct_count = 46
null_rate = 0.0
min = 1.39
max = 3.31
mean = 2.1650909090909094
std = 0.45800239659437947

[columns.stats.percentiles]
p25 = 1.78
p50 = 2.14
p75 = 2.38
p95 = 2.95
p99 = 3.3

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "year"
min = 0.0

[[constraints]]
type = "range"
field = "miles"
min = 0.0

[[constraints]]
type = "range"
field = "gas"
min = 1.39
max = 3.31

[[constraints]]
type = "check"
expr = "year <= miles"

[[constraints]]
type = "check"
expr = "gas <= year"

[[constraints]]
type = "check"
expr = "gas <= miles"
