//! Schema assembly — build a Weave schema document from inferred elements.
//!
//! Takes the combined results of profiling, distribution fitting, temporal
//! pattern recognition, and relationship detection, and assembles them into
//! a valid Weave schema (either as a [`DataModel`] or as a human-readable DSL).

use std::collections::BTreeMap;
use std::fmt::Write;

use tracing::{debug, info};

use knit_core::{
    CountSpec, DataModel, DistributionKind, DistributionSpec, Entity, Field,
    GeneratorSpec, NullSpec, Relationship, RelationshipKind as CoreRelKind,
    Value, WeightedChoice,
};

use crate::correlation::Correlation;
use crate::fitting::{Distribution, FitResult};
use crate::relationships::{RelationshipCandidate, RelationshipKind};
use crate::temporal::TemporalPatternSpec;
use crate::type_inference::{InferredType, StringPattern};

/// Analysis results for a single table, used as input to schema assembly.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct TableAnalysis {
    /// Table / entity name.
    pub name: String,
    /// Per-column analysis results.
    pub columns: Vec<ColumnAnalysis>,
    /// Detected outgoing relationships (FKs from this table).
    pub relationships: Vec<RelationshipCandidate>,
    /// Detected correlations involving this table's columns.
    pub correlations: Vec<Correlation>,
    /// Number of rows observed in the source data.
    pub row_count: u64,
}

impl TableAnalysis {
    /// Create a new `TableAnalysis` with the given name, columns, and row count.
    pub fn new(name: String, columns: Vec<ColumnAnalysis>, row_count: u64) -> Self {
        Self {
            name,
            columns,
            relationships: Vec::new(),
            correlations: Vec::new(),
            row_count,
        }
    }
}

/// Analysis results for a single column.
#[derive(Debug, Clone)]
#[non_exhaustive]
pub struct ColumnAnalysis {
    /// Column name.
    pub name: String,
    /// Whether this is a primary key.
    pub is_primary_key: bool,
    /// Distribution fit result (for numeric columns).
    pub distribution: Option<FitResult>,
    /// Temporal pattern (for timestamp columns).
    pub temporal_pattern: Option<TemporalPatternSpec>,
    /// Categorical weights (category → weight).
    pub categorical_weights: Option<Vec<(String, f64)>>,
    /// Null rate (0.0–1.0).
    pub null_rate: f64,
    /// Confidence score for the overall inference.
    pub confidence: f64,
    /// Semantic type inferred from string content (UUID, date, email, etc.).
    pub inferred_type: Option<InferredType>,
    /// Detected string patterns (email, phone, URL) with match rates.
    pub string_patterns: Vec<(StringPattern, f64)>,
    /// Whether a numeric column contains only integer values.
    pub is_integer_valued: bool,
    /// Whether a temporal column has time-of-day precision (vs date-only).
    pub has_time_component: bool,
    /// Min/max timestamps as seconds since epoch (for temporal range).
    pub temporal_range: Option<(f64, f64)>,
}

impl ColumnAnalysis {
    /// Create a new `ColumnAnalysis` with required fields; optional fields default to `None`/empty.
    pub fn new(name: String, null_rate: f64, confidence: f64) -> Self {
        Self {
            name,
            is_primary_key: false,
            distribution: None,
            temporal_pattern: None,
            categorical_weights: None,
            null_rate,
            confidence,
            inferred_type: None,
            string_patterns: vec![],
            is_integer_valued: false,
            has_time_component: false,
            temporal_range: None,
        }
    }
}

/// Assemble a Weave schema document from table analyses.
///
/// Produces a human-readable schema string with generator specifications,
/// relationship references, and confidence annotations.
pub fn assemble_schema(tables: &[TableAnalysis]) -> String {
    let mut out = String::with_capacity(4096);

    writeln!(out, "# Auto-generated Weave schema").unwrap();
    writeln!(out, "# Generated by knit-learn").unwrap();
    writeln!(out).unwrap();

    for table in tables {
        debug!(table = %table.name, cols = table.columns.len(), "assembling table schema");
        assemble_table(&mut out, table);
        writeln!(out).unwrap();
    }

    info!(tables = tables.len(), bytes = out.len(), "schema assembled");
    out
}

/// Assemble a proper [`DataModel`] from table analyses.
///
/// Unlike [`assemble_schema`], this returns a structured model that can be
/// serialized to valid Weave TOML/JSON by the caller.
pub fn assemble_data_model(name: &str, tables: &[TableAnalysis]) -> DataModel {
    let mut entities = Vec::with_capacity(tables.len());
    let mut relationships = Vec::new();
    let mut correlations = Vec::new();

    for table in tables {
        let (entity, rels, corrs) = build_entity(table);
        entities.push(entity);
        relationships.extend(rels);
        correlations.extend(corrs);
    }

    info!(
        entities = entities.len(),
        relationships = relationships.len(),
        "data model assembled"
    );

    DataModel {
        name: name.to_string(),
        description: Some("Auto-generated by knit learn".to_string()),
        seed: 42,
        locale: "en_US".to_string(),
        timezone: "UTC".to_string(),
        entities,
        relationships,
        noise_profiles: Vec::new(),
        correlations,
        params: BTreeMap::new(),
        schema_version: "1.0".to_string(),
    }
}

/// Build an [`Entity`] from a `TableAnalysis`, extracting relationships
/// and correlations as separate top-level items.
fn build_entity(
    table: &TableAnalysis,
) -> (Entity, Vec<Relationship>, Vec<knit_core::Correlation>) {
    let mut fields = Vec::with_capacity(table.columns.len());

    for col in &table.columns {
        let fk = table
            .relationships
            .iter()
            .find(|r| r.from_column == col.name && r.from_table == table.name);

        let generator = build_generator(col, fk);
        let data_type = infer_data_type(col, fk);
        let nullable = if col.null_rate > 0.01 {
            NullSpec::Probability(col.null_rate)
        } else {
            NullSpec::Never
        };

        fields.push(Field {
            name: col.name.clone(),
            description: None,
            data_type,
            generator: Some(generator),
            nullable,
            primary_key: if col.is_primary_key { Some(true) } else { None },
        });
    }

    // Build top-level Relationship entries from detected FKs
    let rels: Vec<Relationship> = table
        .relationships
        .iter()
        .map(|r| Relationship {
            name: format!("{}_{}_fk", r.from_table, r.from_column),
            from: r.from_table.clone(),
            to: r.to_table.clone(),
            kind: match r.kind {
                RelationshipKind::OneToOne => CoreRelKind::OneToOne,
                RelationshipKind::OneToMany => CoreRelKind::OneToMany,
                RelationshipKind::ManyToMany => CoreRelKind::ManyToMany,
            },
            foreign_key: Some(r.from_column.clone()),
            cardinality: None,
        })
        .collect();

    // Build top-level Correlation entries
    let corrs: Vec<knit_core::Correlation> = table
        .correlations
        .iter()
        .filter_map(|c| {
            let fields = vec![c.column_a.clone(), c.column_b.clone()];
            // Only emit if coefficient is meaningful
            if c.coefficient.abs() < 0.3 {
                return None;
            }
            Some(knit_core::Correlation {
                entity: table.name.clone(),
                fields,
                matrix: vec![
                    vec![1.0, c.coefficient],
                    vec![c.coefficient, 1.0],
                ],
                conditional: Vec::new(),
            })
        })
        .collect();

    let entity = Entity {
        name: table.name.clone(),
        description: None,
        count: CountSpec::Fixed(table.row_count),
        fields,
        constraints: Vec::new(),
        topology: None,
    };

    (entity, rels, corrs)
}

/// Build a [`GeneratorSpec`] for a column based on inferred properties.
fn build_generator(
    col: &ColumnAnalysis,
    fk: Option<&RelationshipCandidate>,
) -> GeneratorSpec {
    // FK → Lookup
    if let Some(rel) = fk {
        return GeneratorSpec::Lookup {
            entity: rel.to_table.clone(),
            field: rel.to_column.clone(),
        };
    }

    // PK → Sequence (or UuidGen for UUID columns, prefixed for string PKs)
    if col.is_primary_key {
        if matches!(col.inferred_type, Some(InferredType::Uuid)) {
            return GeneratorSpec::UuidGen { version: 4 };
        }
        // String-typed PKs get a prefix to produce string values
        let is_string_pk = matches!(
            col.inferred_type,
            Some(InferredType::Text) | Some(InferredType::Categorical)
        ) || !col.string_patterns.is_empty();
        return GeneratorSpec::Sequence {
            start: 1,
            step: 1,
            prefix: if is_string_pk {
                Some(format!("{}_", col.name))
            } else {
                None
            },
        };
    }

    // Temporal pattern
    if col.temporal_pattern.is_some() {
        return build_temporal_generator(col);
    }

    // Distribution
    if let Some(fit) = &col.distribution {
        return build_distribution_generator(&fit.best.distribution, col.is_integer_valued);
    }

    // Boolean (check before categorical since bool columns store weights there)
    if matches!(col.inferred_type, Some(InferredType::Boolean)) {
        if let Some(weights) = &col.categorical_weights {
            let true_w = weights.iter().find(|(k, _)| k == "true").map(|(_, w)| *w).unwrap_or(0.5);
            let false_w = weights.iter().find(|(k, _)| k == "false").map(|(_, w)| *w).unwrap_or(0.5);
            return GeneratorSpec::OneOf {
                choices: vec![
                    WeightedChoice { value: Value::Bool(true), weight: true_w },
                    WeightedChoice { value: Value::Bool(false), weight: false_w },
                ],
            };
        }
        return GeneratorSpec::OneOf {
            choices: vec![
                WeightedChoice { value: Value::Bool(true), weight: 0.5 },
                WeightedChoice { value: Value::Bool(false), weight: 0.5 },
            ],
        };
    }

    // Categorical
    if let Some(weights) = &col.categorical_weights {
        return build_categorical_generator(weights);
    }

    // Semantic type from string inference
    if let Some(ref inferred) = col.inferred_type {
        match inferred {
            InferredType::Uuid => {
                return GeneratorSpec::UuidGen { version: 4 };
            }
            InferredType::Date(_) => {
                let method = if col.has_time_component { "datetime" } else { "date" };
                return GeneratorSpec::Faker { method: method.into(), args: vec![] };
            }
            _ => {}
        }
    }

    // Column name heuristic — map common names to appropriate faker methods.
    // Placed before string pattern matching so semantic names override generic patterns
    // (e.g., "PostalCode" → zip_code instead of phone pattern match).
    if let Some(method) = faker_method_from_column_name(&col.name) {
        return GeneratorSpec::Faker { method: method.into(), args: vec![] };
    }

    // String pattern → Faker
    if let Some((pattern, _rate)) = col.string_patterns.first() {
        match pattern {
            StringPattern::Email => {
                return GeneratorSpec::Faker { method: "email".into(), args: vec![] };
            }
            StringPattern::Phone => {
                return GeneratorSpec::Faker { method: "phone".into(), args: vec![] };
            }
            StringPattern::Name => {
                return GeneratorSpec::Faker { method: "name".into(), args: vec![] };
            }
            StringPattern::Date => {
                return GeneratorSpec::Faker { method: "date".into(), args: vec![] };
            }
            StringPattern::HexString(len) => {
                return GeneratorSpec::Faker {
                    method: "hex_string".into(),
                    args: vec![knit_core::Value::Int(*len as i64)],
                };
            }
            _ => {}
        }
    }

    // Fallback: use faker("word") for string/text columns, sequence for others
    if matches!(
        col.inferred_type,
        Some(InferredType::Text) | Some(InferredType::Categorical)
    ) || !col.string_patterns.is_empty()
    {
        return GeneratorSpec::Faker {
            method: "word".into(),
            args: vec![],
        };
    }
    GeneratorSpec::Sequence {
        start: 1,
        step: 1,
        prefix: None,
    }
}

/// Map a fitted distribution to a [`GeneratorSpec::Distribution`].
fn build_distribution_generator(dist: &Distribution, round: bool) -> GeneratorSpec {
    let (kind, params) = match dist {
        Distribution::Normal(mean, std_dev) => {
            let mut p = BTreeMap::new();
            p.insert("mean".into(), *mean);
            p.insert("std_dev".into(), *std_dev);
            (DistributionKind::Normal, p)
        }
        Distribution::LogNormal(mu, sigma) => {
            let mut p = BTreeMap::new();
            p.insert("mu".into(), *mu);
            p.insert("sigma".into(), *sigma);
            (DistributionKind::LogNormal, p)
        }
        Distribution::Exponential(lambda) => {
            let mut p = BTreeMap::new();
            p.insert("lambda".into(), *lambda);
            (DistributionKind::Exponential, p)
        }
        Distribution::Uniform(min, max) => {
            let mut p = BTreeMap::new();
            p.insert("min".into(), *min);
            p.insert("max".into(), *max);
            (DistributionKind::Uniform, p)
        }
        Distribution::Poisson(lambda) => {
            let mut p = BTreeMap::new();
            p.insert("lambda".into(), *lambda);
            (DistributionKind::Poisson, p)
        }
        Distribution::Beta(alpha, beta) => {
            let mut p = BTreeMap::new();
            p.insert("alpha".into(), *alpha);
            p.insert("beta".into(), *beta);
            (DistributionKind::Beta, p)
        }
        Distribution::Gamma(shape, rate) => {
            let mut p = BTreeMap::new();
            p.insert("shape".into(), *shape);
            // Generator expects scale (= 1/rate)
            p.insert("scale".into(), 1.0 / *rate);
            (DistributionKind::Gamma, p)
        }
        Distribution::Pareto(x_m, alpha) => {
            let mut p = BTreeMap::new();
            p.insert("scale".into(), *x_m);
            p.insert("shape".into(), *alpha);
            (DistributionKind::Pareto, p)
        }
        Distribution::Zipf(n, s) => {
            let mut p = BTreeMap::new();
            p.insert("n".into(), *n as f64);
            p.insert("s".into(), *s);
            (DistributionKind::Zipf, p)
        }
    };

    GeneratorSpec::Distribution {
        spec: DistributionSpec { kind, params, round },
    }
}

/// Map categorical weights to a [`GeneratorSpec::OneOf`].
fn build_categorical_generator(weights: &[(String, f64)]) -> GeneratorSpec {
    let choices: Vec<WeightedChoice> = weights
        .iter()
        .take(200)
        .map(|(val, w)| WeightedChoice {
            value: Value::String(val.clone()),
            weight: *w,
        })
        .collect();

    GeneratorSpec::OneOf { choices }
}

/// Map a temporal pattern to a [`GeneratorSpec`].
fn build_temporal_generator(col: &ColumnAnalysis) -> GeneratorSpec {
    let method = if col.has_time_component { "datetime" } else { "date" };
    let args = if let Some((min_s, max_s)) = col.temporal_range {
        // Convert epoch seconds to ISO date strings for args
        let min_days = (min_s / 86_400.0).floor() as i64;
        let max_days = (max_s / 86_400.0).floor() as i64;
        let (y1, m1, d1) = days_to_ymd(min_days);
        let (y2, m2, d2) = days_to_ymd(max_days);
        vec![
            Value::String(format!("{y1:04}-{m1:02}-{d1:02}")),
            Value::String(format!("{y2:04}-{m2:02}-{d2:02}")),
        ]
    } else {
        vec![]
    };
    GeneratorSpec::Faker {
        method: method.into(),
        args,
    }
}

/// Convert days since epoch to (year, month, day) — same as in faker.rs.
fn days_to_ymd(days: i64) -> (i32, u32, u32) {
    let z = days + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u32;
    let yoe = (doe - doe / 1460 + doe / 36524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m <= 2 { y + 1 } else { y };
    (y as i32, m, d)
}

/// Map common column names to faker methods using keyword heuristics.
fn faker_method_from_column_name(name: &str) -> Option<&'static str> {
    let lower = name.to_lowercase();
    // Check for known semantic keywords in the column name
    if lower.contains("address") || lower.contains("street") {
        return Some("address");
    }
    if lower == "city" || lower.ends_with("_city") || lower.starts_with("city_") {
        return Some("city");
    }
    if lower == "state" || lower == "province" || lower.ends_with("_state") {
        return Some("state");
    }
    if lower == "country" || lower.ends_with("_country") || lower.starts_with("country_") {
        return Some("country");
    }
    if lower.contains("zip") || lower.contains("postal") {
        return Some("zip_code");
    }
    if lower.contains("company") || lower.contains("organization") || lower.contains("organisation") {
        return Some("company");
    }
    if lower.contains("url") || lower.contains("website") || lower.contains("homepage") {
        return Some("url");
    }
    if lower.contains("domain") {
        return Some("domain");
    }
    if lower.contains("title") && !lower.contains("subtitle") {
        return Some("title");
    }
    None
}

/// Infer a [`knit_core::DataType`] from column analysis.
fn infer_data_type(
    col: &ColumnAnalysis,
    fk: Option<&RelationshipCandidate>,
) -> knit_core::DataType {
    // UUID columns keep their type even as PK/FK
    if matches!(col.inferred_type, Some(InferredType::Uuid)) {
        return knit_core::DataType::Uuid;
    }
    if matches!(col.inferred_type, Some(InferredType::Boolean)) {
        return knit_core::DataType::Bool;
    }
    if matches!(col.inferred_type, Some(InferredType::Date(_))) {
        return if col.has_time_component {
            knit_core::DataType::Datetime
        } else {
            knit_core::DataType::Date
        };
    }
    if fk.is_some() || col.is_primary_key {
        // If the column has string content, keep it as String
        let is_string = matches!(
            col.inferred_type,
            Some(InferredType::Text) | Some(InferredType::Categorical)
        ) || !col.string_patterns.is_empty();
        if is_string {
            return knit_core::DataType::String;
        }
        return knit_core::DataType::Int;
    }
    if col.temporal_pattern.is_some() {
        return if col.has_time_component {
            knit_core::DataType::Datetime
        } else {
            knit_core::DataType::Date
        };
    }
    if col.distribution.is_some() {
        // Check if all values are whole numbers → Int
        if col.is_integer_valued {
            return knit_core::DataType::Int;
        }
        return knit_core::DataType::Float;
    }
    if col.categorical_weights.is_some() {
        return knit_core::DataType::String;
    }
    knit_core::DataType::String
}

fn assemble_table(out: &mut String, table: &TableAnalysis) {
    writeln!(out, "entity {} {{", table.name).unwrap();

    for col in &table.columns {
        assemble_column(out, col, &table.relationships, &table.name);
    }

    writeln!(out, "}}").unwrap();
}

fn assemble_column(
    out: &mut String,
    col: &ColumnAnalysis,
    relationships: &[RelationshipCandidate],
    table_name: &str,
) {
    // Check if this column is a FK
    let fk = relationships
        .iter()
        .find(|r| r.from_column == col.name && r.from_table == table_name);

    let generator = if let Some(rel) = fk {
        format!("ref({}.{})", rel.to_table, rel.to_column)
    } else if col.is_primary_key {
        if matches!(col.inferred_type, Some(InferredType::Uuid)) {
            "uuid()".to_string()
        } else {
            "auto_increment()".to_string()
        }
    } else if let Some(spec) = &col.temporal_pattern {
        if spec.generator_expr.is_empty() {
            "timestamp()".to_string()
        } else {
            spec.generator_expr.clone()
        }
    } else if let Some(fit) = &col.distribution {
        distribution_to_generator(&fit.best.distribution)
    } else if let Some(weights) = &col.categorical_weights {
        categorical_to_generator(weights)
    } else if matches!(col.inferred_type, Some(InferredType::Uuid)) {
        "uuid()".to_string()
    } else if matches!(col.inferred_type, Some(InferredType::Boolean)) {
        "one_of(\"true\" => 50%, \"false\" => 50%)".to_string()
    } else if matches!(col.inferred_type, Some(InferredType::Date(_))) {
        "faker(\"date\")".to_string()
    } else if col.string_patterns.iter().any(|(p, _)| *p == StringPattern::Email) {
        "faker(\"email\")".to_string()
    } else if col.string_patterns.iter().any(|(p, _)| *p == StringPattern::Phone) {
        "faker(\"phone\")".to_string()
    } else if col.string_patterns.iter().any(|(p, _)| *p == StringPattern::Name) {
        "faker(\"name\")".to_string()
    } else if col.string_patterns.iter().any(|(p, _)| matches!(p, StringPattern::HexString(_))) {
        let len = col.string_patterns.iter()
            .find_map(|(p, _)| if let StringPattern::HexString(n) = p { Some(*n) } else { None })
            .unwrap_or(32);
        format!("faker(\"hex_string\", {})", len)
    } else {
        "unknown()".to_string()
    };

    let null_suffix = if col.null_rate > 0.01 {
        format!(" | null({})", format_pct(col.null_rate))
    } else {
        String::new()
    };

    // Confidence comment
    let comment = if col.confidence < 1.0 {
        format!("  # confidence: {:.0}%", col.confidence * 100.0)
    } else {
        String::new()
    };

    writeln!(out, "  {} = {}{}{}", col.name, generator, null_suffix, comment).unwrap();
}

/// Map a fitted distribution to a Weave generator expression.
fn distribution_to_generator(dist: &Distribution) -> String {
    match dist {
        Distribution::Normal(mean, std_dev) => {
            format!("normal({:.2}, {:.2})", mean, std_dev)
        }
        Distribution::LogNormal(mu, sigma) => {
            format!("log_normal({:.2}, {:.2})", mu, sigma)
        }
        Distribution::Exponential(lambda) => {
            format!("exponential({:.4})", lambda)
        }
        Distribution::Uniform(min, max) => {
            format!("uniform({:.2}, {:.2})", min, max)
        }
        Distribution::Poisson(lambda) => {
            format!("poisson({:.2})", lambda)
        }
        Distribution::Beta(alpha, beta) => {
            format!("beta({:.2}, {:.2})", alpha, beta)
        }
        Distribution::Gamma(shape, rate) => {
            format!("gamma(shape={:.2}, scale={:.2})", shape, 1.0 / rate)
        }
        Distribution::Pareto(x_m, alpha) => {
            format!("pareto(scale={:.2}, shape={:.2})", x_m, alpha)
        }
        Distribution::Zipf(n, s) => {
            format!("zipf({}, {:.2})", n, s)
        }
    }
}

/// Map categorical weights to a `one_of(...)` generator.
fn categorical_to_generator(weights: &[(String, f64)]) -> String {
    if weights.is_empty() {
        return "unknown()".to_string();
    }
    let items: Vec<String> = weights
        .iter()
        .take(20) // Cap displayed items
        .map(|(val, w)| format!("\"{}\" => {:.0}%", val, w * 100.0))
        .collect();
    format!("one_of({})", items.join(", "))
}

fn format_pct(rate: f64) -> String {
    format!("{:.0}%", rate * 100.0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fitting::CandidateFit;

    fn make_fit(dist: Distribution) -> FitResult {
        FitResult {
            best: CandidateFit {
                distribution: dist.clone(),
                ks_stat: 0.05,
                p_value: 0.5,
                aic: 100.0,
                bic: 105.0,
            },
            alternatives: vec![CandidateFit {
                distribution: dist,
                ks_stat: 0.05,
                p_value: 0.5,
                aic: 100.0,
                bic: 105.0,
            }],
        }
    }

    #[test]
    fn assemble_simple_schema() {
        let tables = vec![TableAnalysis {
            name: "users".into(),
            columns: vec![
                ColumnAnalysis {
                    name: "id".into(),
                    is_primary_key: true,
                    distribution: None,
                    temporal_pattern: None,
                    categorical_weights: None,
                    null_rate: 0.0,
                    confidence: 1.0,
                    inferred_type: None,
                    string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                },
                ColumnAnalysis {
                    name: "age".into(),
                    is_primary_key: false,
                    distribution: Some(make_fit(Distribution::Normal(30.0, 10.0))),
                    temporal_pattern: None,
                    categorical_weights: None,
                    null_rate: 0.02,
                    confidence: 0.85,
                    inferred_type: None,
                    string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                },
            ],
            relationships: vec![],
            correlations: vec![],
            row_count: 5000,
        }];

        let schema = assemble_schema(&tables);
        assert!(schema.contains("entity users"));
        assert!(schema.contains("id = auto_increment()"));
        assert!(schema.contains("normal(30.00, 10.00)"));
        assert!(schema.contains("confidence: 85%"));
        assert!(schema.contains("null(2%)"));
    }

    #[test]
    fn assemble_with_fk() {
        let tables = vec![TableAnalysis {
            name: "orders".into(),
            columns: vec![ColumnAnalysis {
                name: "user_id".into(),
                is_primary_key: false,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 0.9,
                inferred_type: None,
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![RelationshipCandidate {
                from_table: "orders".into(),
                from_column: "user_id".into(),
                to_table: "users".into(),
                to_column: "id".into(),
                kind: RelationshipKind::OneToMany,
                confidence: 0.9,
                is_self_ref: false,
            }],
            correlations: vec![],
            row_count: 1000,
        }];

        let schema = assemble_schema(&tables);
        assert!(schema.contains("ref(users.id)"), "schema: {}", schema);
    }

    #[test]
    fn assemble_categorical() {
        let tables = vec![TableAnalysis {
            name: "items".into(),
            columns: vec![ColumnAnalysis {
                name: "status".into(),
                is_primary_key: false,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: Some(vec![
                    ("active".into(), 0.7),
                    ("inactive".into(), 0.3),
                ]),
                null_rate: 0.0,
                confidence: 0.95,
                inferred_type: None,
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![],
            correlations: vec![],
            row_count: 500,
        }];

        let schema = assemble_schema(&tables);
        assert!(schema.contains("one_of("), "schema: {}", schema);
        assert!(schema.contains("active"));
    }

    #[test]
    fn assemble_temporal() {
        let tables = vec![TableAnalysis {
            name: "events".into(),
            columns: vec![ColumnAnalysis {
                name: "created_at".into(),
                is_primary_key: false,
                distribution: None,
                temporal_pattern: Some(crate::temporal::TemporalPatternSpec {
                    pattern: crate::temporal::TemporalPattern::FixedInterval {
                        interval_secs: 3600.0,
                    },
                    generator_expr: "time_series(interval=3600s)".into(),
                    confidence: 0.9,
                }),
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 0.9,
                inferred_type: None,
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![],
            correlations: vec![],
            row_count: 2000,
        }];

        let schema = assemble_schema(&tables);
        assert!(schema.contains("time_series(interval=3600s)"), "schema: {}", schema);
    }

    #[test]
    fn assemble_empty() {
        let schema = assemble_schema(&[]);
        assert!(schema.contains("Auto-generated"));
    }

    #[test]
    fn distribution_generators() {
        assert!(distribution_to_generator(&Distribution::Normal(0.0, 1.0)).contains("normal"));
        assert!(distribution_to_generator(&Distribution::Exponential(0.5)).contains("exponential"));
        assert!(distribution_to_generator(&Distribution::Uniform(0.0, 100.0)).contains("uniform"));
        assert!(distribution_to_generator(&Distribution::Beta(2.0, 5.0)).contains("beta"));
        let gamma = distribution_to_generator(&Distribution::Gamma(1.0, 2.0));
        assert!(gamma.contains("gamma"), "gamma: {}", gamma);
        assert!(gamma.contains("shape="), "gamma should have shape param: {}", gamma);
        assert!(gamma.contains("scale="), "gamma should have scale param: {}", gamma);
        let pareto = distribution_to_generator(&Distribution::Pareto(1.0, 2.0));
        assert!(pareto.contains("pareto"), "pareto: {}", pareto);
        assert!(pareto.contains("scale="), "pareto should have scale param: {}", pareto);
        assert!(pareto.contains("shape="), "pareto should have shape param: {}", pareto);
    }

    #[test]
    fn build_distribution_generator_param_names() {
        use crate::fitting::Distribution;

        // Gamma: shape/scale (rate converted to scale)
        let spec = build_distribution_generator(&Distribution::Gamma(2.0, 0.5), false);
        if let GeneratorSpec::Distribution { spec: ds } = &spec {
            assert_eq!(ds.kind, DistributionKind::Gamma);
            assert!(ds.params.contains_key("shape"), "Gamma missing shape param");
            assert!(ds.params.contains_key("scale"), "Gamma missing scale param");
            assert!((ds.params["shape"] - 2.0).abs() < 1e-10);
            assert!((ds.params["scale"] - 2.0).abs() < 1e-10); // scale = 1/rate = 1/0.5
        } else {
            panic!("Expected Distribution spec for Gamma");
        }

        // Pareto: scale/shape
        let spec = build_distribution_generator(&Distribution::Pareto(1.0, 3.0), false);
        if let GeneratorSpec::Distribution { spec: ds } = &spec {
            assert_eq!(ds.kind, DistributionKind::Pareto);
            assert!(ds.params.contains_key("scale"), "Pareto missing scale param");
            assert!(ds.params.contains_key("shape"), "Pareto missing shape param");
            assert!((ds.params["scale"] - 1.0).abs() < 1e-10);
            assert!((ds.params["shape"] - 3.0).abs() < 1e-10);
        } else {
            panic!("Expected Distribution spec for Pareto");
        }

        // Beta: alpha/beta (unchanged)
        let spec = build_distribution_generator(&Distribution::Beta(2.0, 5.0), false);
        if let GeneratorSpec::Distribution { spec: ds } = &spec {
            assert_eq!(ds.kind, DistributionKind::Beta);
            assert!(ds.params.contains_key("alpha"), "Beta missing alpha param");
            assert!(ds.params.contains_key("beta"), "Beta missing beta param");
        } else {
            panic!("Expected Distribution spec for Beta");
        }
    }

    #[test]
    fn row_count_preserved() {
        let tables = vec![TableAnalysis {
            name: "big_table".into(),
            columns: vec![ColumnAnalysis {
                name: "id".into(),
                is_primary_key: true,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 1.0,
                inferred_type: None,
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![],
            correlations: vec![],
            row_count: 50_000,
        }];

        let model = assemble_data_model("test", &tables);
        assert_eq!(model.entities[0].count, CountSpec::Fixed(50_000));
    }

    #[test]
    fn uuid_pk_uses_uuid_gen() {
        let tables = vec![TableAnalysis {
            name: "items".into(),
            columns: vec![ColumnAnalysis {
                name: "id".into(),
                is_primary_key: true,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 0.95,
                inferred_type: Some(InferredType::Uuid),
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![],
            correlations: vec![],
            row_count: 100,
        }];

        let model = assemble_data_model("test", &tables);
        let field = &model.entities[0].fields[0];
        assert!(
            matches!(field.generator, Some(GeneratorSpec::UuidGen { version: 4 })),
            "expected UuidGen, got {:?}",
            field.generator,
        );
        assert_eq!(field.data_type, knit_core::DataType::Uuid);
    }

    #[test]
    fn uuid_non_pk_uses_uuid_gen() {
        let col = ColumnAnalysis {
            name: "trace_id".into(),
            is_primary_key: false,
            distribution: None,
            temporal_pattern: None,
            categorical_weights: None,
            null_rate: 0.0,
            confidence: 0.95,
            inferred_type: Some(InferredType::Uuid),
            string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                };
        let gen = build_generator(&col, None);
        assert!(matches!(gen, GeneratorSpec::UuidGen { version: 4 }));
    }

    #[test]
    fn boolean_uses_one_of() {
        let col = ColumnAnalysis {
            name: "active".into(),
            is_primary_key: false,
            distribution: None,
            temporal_pattern: None,
            categorical_weights: None,
            null_rate: 0.0,
            confidence: 0.9,
            inferred_type: Some(InferredType::Boolean),
            string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                };
        let gen = build_generator(&col, None);
        assert!(matches!(gen, GeneratorSpec::OneOf { .. }));
    }

    #[test]
    fn email_pattern_uses_faker() {
        let col = ColumnAnalysis {
            name: "email".into(),
            is_primary_key: false,
            distribution: None,
            temporal_pattern: None,
            categorical_weights: None,
            null_rate: 0.0,
            confidence: 0.9,
            inferred_type: Some(InferredType::Text),
            string_patterns: vec![(StringPattern::Email, 0.95)],
            is_integer_valued: false,
            has_time_component: false,
            temporal_range: None,
        };
        let gen = build_generator(&col, None);
        assert!(
            matches!(gen, GeneratorSpec::Faker { ref method, .. } if method == "email"),
            "expected Faker(email), got {:?}",
            gen,
        );
    }

    #[test]
    fn phone_pattern_uses_faker() {
        let col = ColumnAnalysis {
            name: "phone".into(),
            is_primary_key: false,
            distribution: None,
            temporal_pattern: None,
            categorical_weights: None,
            null_rate: 0.0,
            confidence: 0.9,
            inferred_type: Some(InferredType::Text),
            string_patterns: vec![(StringPattern::Phone, 0.9)],
            is_integer_valued: false,
            has_time_component: false,
            temporal_range: None,
        };
        let gen = build_generator(&col, None);
        assert!(
            matches!(gen, GeneratorSpec::Faker { ref method, .. } if method == "phone"),
            "expected Faker(phone), got {:?}",
            gen,
        );
    }

    #[test]
    fn uuid_dsl_output() {
        let tables = vec![TableAnalysis {
            name: "traces".into(),
            columns: vec![ColumnAnalysis {
                name: "trace_id".into(),
                is_primary_key: false,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 0.95,
                inferred_type: Some(InferredType::Uuid),
                string_patterns: vec![],
                    is_integer_valued: false,
                    has_time_component: false,
                    temporal_range: None,
                }],
            relationships: vec![],
            correlations: vec![],
            row_count: 100,
        }];
        let schema = assemble_schema(&tables);
        assert!(schema.contains("uuid()"), "schema: {}", schema);
    }

    #[test]
    fn email_dsl_output() {
        let tables = vec![TableAnalysis {
            name: "contacts".into(),
            columns: vec![ColumnAnalysis {
                name: "email".into(),
                is_primary_key: false,
                distribution: None,
                temporal_pattern: None,
                categorical_weights: None,
                null_rate: 0.0,
                confidence: 0.9,
                inferred_type: Some(InferredType::Text),
                string_patterns: vec![(StringPattern::Email, 0.95)],
                is_integer_valued: false,
                has_time_component: false,
                temporal_range: None,
            }],
            relationships: vec![],
            correlations: vec![],
            row_count: 100,
        }];
        let schema = assemble_schema(&tables);
        assert!(schema.contains("faker(\"email\")"), "schema: {}", schema);
    }
}
