[[correlations]]
entity = "original"
fields = [
    "high",
    "close",
]
matrix = [
    [
    1.0,
    0.9998030293822232,
],
    [
    0.9998030293822232,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "close",
]
matrix = [
    [
    1.0,
    0.9995909746731312,
],
    [
    0.9995909746731312,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "open",
]
matrix = [
    [
    1.0,
    0.9998503868226887,
],
    [
    0.9998503868226887,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "open",
]
matrix = [
    [
    1.0,
    0.9996658184023339,
],
    [
    0.9996658184023339,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "adjclose",
]
matrix = [
    [
    1.0,
    0.9998030293822232,
],
    [
    0.9998030293822232,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "adjclose",
]
matrix = [
    [
    1.0,
    0.9995909746731312,
],
    [
    0.9995909746731312,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "low",
]
matrix = [
    [
    1.0,
    0.9996923436120136,
],
    [
    0.9996923436120136,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "low",
]
matrix = [
    [
    1.0,
    0.9994833186626921,
],
    [
    0.9994833186626921,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "open",
]
matrix = [
    [
    1.0,
    0.9996281931676778,
],
    [
    0.9996281931676778,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "open",
]
matrix = [
    [
    1.0,
    0.9990984806261017,
],
    [
    0.9990984806261017,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "adjclose",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "adjclose",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "low",
]
matrix = [
    [
    1.0,
    0.9998164477100954,
],
    [
    0.9998164477100954,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "low",
]
matrix = [
    [
    1.0,
    0.9996310772946901,
],
    [
    0.9996310772946901,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "adjclose",
]
matrix = [
    [
    1.0,
    0.9996281931676778,
],
    [
    0.9996281931676778,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "adjclose",
]
matrix = [
    [
    1.0,
    0.9990984806261017,
],
    [
    0.9990984806261017,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "low",
]
matrix = [
    [
    1.0,
    0.9997784774597166,
],
    [
    0.9997784774597166,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "low",
]
matrix = [
    [
    1.0,
    0.999516179267337,
],
    [
    0.999516179267337,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "adjclose",
    "low",
]
matrix = [
    [
    1.0,
    0.9998164477100954,
],
    [
    0.9998164477100954,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "adjclose",
    "low",
]
matrix = [
    [
    1.0,
    0.9996310772946901,
],
    [
    0.9996310772946901,
    1.0,
],
]
conditional = []
