[table]
name = "original"
count = 1043

[table.stats]
source_rows = 1043

[[table.scaling.custom]]
name = "label"
field = "label"
cardinality = 2

[table.sort_by]
column = "idx"
direction = "asc"

[[columns]]
name = "sentence"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 1043

[columns.stats]
distinct_count = 1039
null_rate = 0.0
min_length = 9
max_length = 157
avg_length = 41.83509108341323

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "label"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 1043

[columns.stats]
distinct_count = 2
null_rate = 0.0
min = 0.0
max = 1.0
mean = 0.6912751677852349
std = 0.46218894611053274

[columns.stats.percentiles]
p25 = 0.0
p50 = 1.0
p75 = 1.0
p95 = 1.0
p99 = 1.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "skewed"

[[columns]]
name = "idx"
data_type = "int32"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 1043

[columns.stats]
distinct_count = 1043
null_rate = 0.0
min = 0.0
max = 1042.0
mean = 521.0
std = 301.2324683695302

[columns.stats.percentiles]
p25 = 261.0
p50 = 521.0
p75 = 782.0
p95 = 990.0
p99 = 1032.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[constraints]]
type = "range"
field = "label"
min = 0.0
max = 1.0

[[constraints]]
type = "range"
field = "idx"
min = 0.0
max = 1042.0
