[table]
name = "original"
count = 5105

[table.stats]
source_rows = 5105

[table.sort_by]
column = "date"
direction = "asc"

[[columns]]
name = "date"
data_type = "date"
nullable = false

[columns.generator]
type = "sequence"
start = "2000-01-03"
step = "1d"

[columns.stats]
null_rate = 0.0
min_temporal = "2000-01-03T00:00:00"
max_temporal = "2020-04-17T00:00:00"

[columns.traits]
semantic = "timestamp"

[[columns]]
name = "open"
data_type = "float"
nullable = false
precision = 6

[columns.generator]
type = "time_series"
baseline = 1469.25

[[columns.generator.components]]
type = "trend"
slope = 0.3385319641480703
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 17.202198476540275

[columns.stats]
distinct_count = 5003
null_rate = 0.0
min = 679.280029
max = 3380.449951
mean = 1595.4601524090124
std = 607.3868054140817

[columns.stats.percentiles]
p25 = 1155.430054
p50 = 1367.089966
p75 = 2015.27002
p95 = 2856.790039
p99 = 3143.850098

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "high"
data_type = "float"
nullable = false
precision = 6

[columns.generator]
type = "time_series"
baseline = 1478.0

[[columns.generator.components]]
type = "trend"
slope = 0.33933283373508477
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 14.726147443761365

[columns.stats]
distinct_count = 4991
null_rate = 0.0
min = 695.27002
max = 3393.52002
mean = 1604.6796066701304
std = 608.7061894840924

[columns.stats.percentiles]
p25 = 1163.75
p50 = 1376.51001
p75 = 2023.77002
p95 = 2870.620117
p99 = 3154.26001

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "low"
data_type = "float"
nullable = false
precision = 6

[columns.generator]
type = "time_series"
baseline = 1438.359985

[[columns.generator.components]]
type = "trend"
slope = 0.33765513878389763
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 16.980731453250293

[columns.stats]
distinct_count = 5004
null_rate = 0.0
min = 666.789978
max = 3378.830078
mean = 1585.437091999411
std = 605.820607616677

[columns.stats.percentiles]
p25 = 1144.780029
p50 = 1358.689941
p75 = 2002.329956
p95 = 2846.179932
p99 = 3135.459961

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "close"
data_type = "float"
nullable = false
precision = 6

[columns.generator]
type = "time_series"
baseline = 1455.219971

[[columns.generator.components]]
type = "trend"
slope = 0.33869891048649237
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 19.755218604290675

[columns.stats]
distinct_count = 4998
null_rate = 0.0
min = 676.530029
max = 3386.149902
mean = 1595.6414743351615
std = 607.4778842309488

[columns.stats.percentiles]
p25 = 1155.459961
p50 = 1367.339966
p75 = 2016.709961
p95 = 2857.699951
p99 = 3141.629883

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "adjclose"
data_type = "float"
nullable = false
precision = 6

[columns.generator]
type = "time_series"
baseline = 1455.219971

[[columns.generator.components]]
type = "trend"
slope = 0.33869891048649237
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 19.755218604290675

[columns.stats]
distinct_count = 4998
null_rate = 0.0
min = 676.530029
max = 3386.149902
mean = 1595.6414743351615
std = 607.4778842309488

[columns.stats.percentiles]
p25 = 1155.459961
p50 = 1367.339966
p75 = 2016.709961
p95 = 2857.699951
p99 = 3141.629883

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "volume"
data_type = "int"
nullable = false

[columns.generator]
type = "time_series"
baseline = 931800000.0

[[columns.generator.components]]
type = "trend"
slope = 587488.5898943866
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 616005314.165591

[columns.stats]
distinct_count = 4966
null_rate = 0.0
min = 356070000.0
max = 11456230000.0
mean = 3124407298.7267385
std = 1503511973.1211405

[columns.stats.percentiles]
p25 = 1692000000.0
p50 = 3235340000.0
p75 = 3931120000.0
p95 = 5760040000.0
p99 = 7597450000.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "open"
min = 0.0

[[constraints]]
type = "range"
field = "high"
min = 0.0

[[constraints]]
type = "range"
field = "low"
min = 0.0

[[constraints]]
type = "range"
field = "close"
min = 0.0

[[constraints]]
type = "range"
field = "adjclose"
min = 0.0

[[constraints]]
type = "range"
field = "volume"
min = 0.0

[[constraints]]
type = "check"
expr = "open <= high"

[[constraints]]
type = "check"
expr = "low <= open"

[[constraints]]
type = "check"
expr = "open <= volume"

[[constraints]]
type = "check"
expr = "low <= high"

[[constraints]]
type = "check"
expr = "close <= high"

[[constraints]]
type = "check"
expr = "adjclose <= high"

[[constraints]]
type = "check"
expr = "high <= volume"

[[constraints]]
type = "check"
expr = "low <= close"

[[constraints]]
type = "check"
expr = "low <= adjclose"

[[constraints]]
type = "check"
expr = "low <= volume"

[[constraints]]
type = "check"
expr = "close <= adjclose"

[[constraints]]
type = "check"
expr = "close <= volume"

[[constraints]]
type = "check"
expr = "adjclose <= volume"
