[[correlations]]
entity = "original"
fields = [
    "other",
    "disease",
]
matrix = [
    [
    1.0,
    0.9010041168504933,
],
    [
    0.9010041168504933,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "other",
    "disease",
]
matrix = [
    [
    1.0,
    0.7930434782608695,
],
    [
    0.7930434782608695,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "other",
    "wounds",
]
matrix = [
    [
    1.0,
    0.41447001347766504,
],
    [
    0.41447001347766504,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "disease",
    "wounds",
]
matrix = [
    [
    1.0,
    0.5993604423228814,
],
    [
    0.5993604423228814,
    1.0,
],
]
conditional = []
