[[constraints]]
table = "original"
type = "range"
field = "wounds"
min = 0.0
max = 287.0

[[constraints]]
table = "original"
type = "range"
field = "other"
min = 5.0
max = 361.0

[[constraints]]
table = "original"
type = "range"
field = "disease"
min = 1.0
max = 2761.0

[[constraints]]
table = "original"
type = "range"
field = "army_size"
min = 8571.0
max = 47751.0

[[constraints]]
table = "original"
type = "check"
expr = "wounds <= army_size"

[[constraints]]
table = "original"
type = "check"
expr = "other <= army_size"

[[constraints]]
table = "original"
type = "check"
expr = "disease <= army_size"
