[[correlations]]
entity = "original"
fields = [
    "BOAT",
    "DOCK",
]
matrix = [
    [
    1.0,
    0.7062267475149115,
],
    [
    0.7062267475149115,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "BOAT",
    "DOCK",
]
matrix = [
    [
    1.0,
    0.7062267475148988,
],
    [
    0.7062267475148988,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STEVE_ROSS",
    "GUEST",
]
matrix = [
    [
    1.0,
    0.6971150462836825,
],
    [
    0.6971150462836825,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STEVE_ROSS",
    "GUEST",
]
matrix = [
    [
    1.0,
    0.6971150462836834,
],
    [
    0.6971150462836834,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "LAKE",
    "RIVER",
]
matrix = [
    [
    1.0,
    -0.4666185796451764,
],
    [
    -0.4666185796451764,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "LAKE",
    "RIVER",
]
matrix = [
    [
    1.0,
    -0.46661857964517767,
],
    [
    -0.46661857964517767,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "BRIDGE",
    "APPLE_FRAME",
]
matrix = [
    [
    1.0,
    0.3751332385900968,
],
    [
    0.3751332385900968,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "BRIDGE",
    "APPLE_FRAME",
]
matrix = [
    [
    1.0,
    0.3751332385900987,
],
    [
    0.3751332385900987,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "BRIDGE",
    "BUILDING",
]
matrix = [
    [
    1.0,
    0.3751332385900968,
],
    [
    0.3751332385900968,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "BRIDGE",
    "BUILDING",
]
matrix = [
    [
    1.0,
    0.3751332385900987,
],
    [
    0.3751332385900987,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "FLORIDA_FRAME",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.3299999162436877,
],
    [
    0.3299999162436877,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "FLORIDA_FRAME",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.3299999162436867,
],
    [
    0.3299999162436867,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "LIGHTHOUSE",
    "CLIFF",
]
matrix = [
    [
    1.0,
    0.3504616713487835,
],
    [
    0.3504616713487835,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "LIGHTHOUSE",
    "CLIFF",
]
matrix = [
    [
    1.0,
    0.3504616713487755,
],
    [
    0.3504616713487755,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "TREE",
]
matrix = [
    [
    1.0,
    -0.7189056374487314,
],
    [
    -0.7189056374487314,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "TREE",
]
matrix = [
    [
    1.0,
    -0.7189056374487325,
],
    [
    -0.7189056374487325,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "CLIFF",
]
matrix = [
    [
    1.0,
    0.3296490128910816,
],
    [
    0.3296490128910816,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "CLIFF",
]
matrix = [
    [
    1.0,
    0.32964901289108317,
],
    [
    0.32964901289108317,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.4825640064328963,
],
    [
    0.4825640064328963,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.4825640064328965,
],
    [
    0.4825640064328965,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.9691880644983998,
],
    [
    0.9691880644983998,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.9691880644984,
],
    [
    0.9691880644984,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "TREES",
]
matrix = [
    [
    1.0,
    -0.5901746474615173,
],
    [
    -0.5901746474615173,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "TREES",
]
matrix = [
    [
    1.0,
    -0.5901746474615106,
],
    [
    -0.5901746474615106,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.8555979618608535,
],
    [
    0.8555979618608535,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OCEAN",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.8555979618608411,
],
    [
    0.8555979618608411,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STRUCTURE",
    "CABIN",
]
matrix = [
    [
    1.0,
    0.7338142166700484,
],
    [
    0.7338142166700484,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STRUCTURE",
    "CABIN",
]
matrix = [
    [
    1.0,
    0.7338142166700514,
],
    [
    0.7338142166700514,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STRUCTURE",
    "BARN",
]
matrix = [
    [
    1.0,
    0.34539551651292555,
],
    [
    0.34539551651292555,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "STRUCTURE",
    "BARN",
]
matrix = [
    [
    1.0,
    0.34539551651292616,
],
    [
    0.34539551651292616,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CUMULUS",
    "CLOUDS",
]
matrix = [
    [
    1.0,
    0.5460948883216566,
],
    [
    0.5460948883216566,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CUMULUS",
    "CLOUDS",
]
matrix = [
    [
    1.0,
    0.5460948883216592,
],
    [
    0.5460948883216592,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "FENCE",
    "BARN",
]
matrix = [
    [
    1.0,
    0.3123302026949514,
],
    [
    0.3123302026949514,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "FENCE",
    "BARN",
]
matrix = [
    [
    1.0,
    0.31233020269495476,
],
    [
    0.31233020269495476,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "CONIFER",
]
matrix = [
    [
    1.0,
    0.4101347486420602,
],
    [
    0.4101347486420602,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "CONIFER",
]
matrix = [
    [
    1.0,
    0.4101347486420577,
],
    [
    0.4101347486420577,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "MOUNTAIN",
]
matrix = [
    [
    1.0,
    0.7503825554954253,
],
    [
    0.7503825554954253,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "MOUNTAIN",
]
matrix = [
    [
    1.0,
    0.7503825554954198,
],
    [
    0.7503825554954198,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.4441052888331546,
],
    [
    0.4441052888331546,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SNOWY_MOUNTAIN",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.44410528883315264,
],
    [
    0.44410528883315264,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "CONIFER",
]
matrix = [
    [
    1.0,
    0.3593538408811193,
],
    [
    0.3593538408811193,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "CONIFER",
]
matrix = [
    [
    1.0,
    0.35935384088111855,
],
    [
    0.35935384088111855,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "DECIDUOUS",
]
matrix = [
    [
    1.0,
    0.38737147648056275,
],
    [
    0.38737147648056275,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "DECIDUOUS",
]
matrix = [
    [
    1.0,
    0.38737147648056486,
],
    [
    0.38737147648056486,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    -0.3881390012094648,
],
    [
    -0.3881390012094648,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    -0.38813900120946665,
],
    [
    -0.38813900120946665,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "WAVES",
]
matrix = [
    [
    1.0,
    -0.6853915883639728,
],
    [
    -0.6853915883639728,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "WAVES",
]
matrix = [
    [
    1.0,
    -0.6853915883639716,
],
    [
    -0.6853915883639716,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "TREES",
]
matrix = [
    [
    1.0,
    0.7707508758454209,
],
    [
    0.7707508758454209,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "TREES",
]
matrix = [
    [
    1.0,
    0.7707508758454118,
],
    [
    0.7707508758454118,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "BEACH",
]
matrix = [
    [
    1.0,
    -0.688180083733004,
],
    [
    -0.688180083733004,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREE",
    "BEACH",
]
matrix = [
    [
    1.0,
    -0.6881800837329992,
],
    [
    -0.6881800837329992,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "RIVER",
    "WATERFALL",
]
matrix = [
    [
    1.0,
    0.3948043197178468,
],
    [
    0.3948043197178468,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "RIVER",
    "WATERFALL",
]
matrix = [
    [
    1.0,
    0.39480431971784735,
],
    [
    0.39480431971784735,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "GUEST",
    "PORTRAIT",
]
matrix = [
    [
    1.0,
    0.36039750781097946,
],
    [
    0.36039750781097946,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "GUEST",
    "PORTRAIT",
]
matrix = [
    [
    1.0,
    0.36039750781097757,
],
    [
    0.36039750781097757,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CLIFF",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.3408266412405266,
],
    [
    0.3408266412405266,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CLIFF",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.340826641240524,
],
    [
    0.340826641240524,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CLIFF",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.3176229079078132,
],
    [
    0.3176229079078132,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CLIFF",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.3176229079078116,
],
    [
    0.3176229079078116,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WINTER",
    "CABIN",
]
matrix = [
    [
    1.0,
    0.3005293760305463,
],
    [
    0.3005293760305463,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WINTER",
    "CABIN",
]
matrix = [
    [
    1.0,
    0.3005293760305476,
],
    [
    0.3005293760305476,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WINTER",
    "SNOW",
]
matrix = [
    [
    1.0,
    0.9166611354391966,
],
    [
    0.9166611354391966,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WINTER",
    "SNOW",
]
matrix = [
    [
    1.0,
    0.916661135439191,
],
    [
    0.916661135439191,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "DECIDUOUS",
]
matrix = [
    [
    1.0,
    -0.37487792068706266,
],
    [
    -0.37487792068706266,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "DECIDUOUS",
]
matrix = [
    [
    1.0,
    -0.3748779206870617,
],
    [
    -0.3748779206870617,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "MOUNTAIN",
]
matrix = [
    [
    1.0,
    0.4553426202459437,
],
    [
    0.4553426202459437,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "MOUNTAIN",
]
matrix = [
    [
    1.0,
    0.4553426202459413,
],
    [
    0.4553426202459413,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "TREES",
]
matrix = [
    [
    1.0,
    0.41252389759983604,
],
    [
    0.41252389759983604,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "TREES",
]
matrix = [
    [
    1.0,
    0.4125238975998354,
],
    [
    0.4125238975998354,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.36849960631020184,
],
    [
    0.36849960631020184,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "CONIFER",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.3684996063102012,
],
    [
    0.3684996063102012,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MOON",
    "NIGHT",
]
matrix = [
    [
    1.0,
    0.5169842621132014,
],
    [
    0.5169842621132014,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MOON",
    "NIGHT",
]
matrix = [
    [
    1.0,
    0.5169842621131975,
],
    [
    0.5169842621131975,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OVAL_FRAME",
    "FRAMED",
]
matrix = [
    [
    1.0,
    0.8291659387872709,
],
    [
    0.8291659387872709,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "OVAL_FRAME",
    "FRAMED",
]
matrix = [
    [
    1.0,
    0.8291659387872689,
],
    [
    0.8291659387872689,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MOUNTAIN",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.6914918649865467,
],
    [
    0.6914918649865467,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MOUNTAIN",
    "MOUNTAINS",
]
matrix = [
    [
    1.0,
    0.691491864986545,
],
    [
    0.691491864986545,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEASHELL_FRAME",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.32999991624368624,
],
    [
    0.32999991624368624,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEASHELL_FRAME",
    "PALM_TREES",
]
matrix = [
    [
    1.0,
    0.3299999162436867,
],
    [
    0.3299999162436867,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "APPLE_FRAME",
    "BUILDING",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "APPLE_FRAME",
    "BUILDING",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PERSON",
    "FIRE",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PERSON",
    "FIRE",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ROCKS",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.30665618835597336,
],
    [
    0.30665618835597336,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ROCKS",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.3066561883559734,
],
    [
    0.3066561883559734,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PALM_TREES",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.49790543663230524,
],
    [
    0.49790543663230524,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PALM_TREES",
    "WAVES",
]
matrix = [
    [
    1.0,
    0.497905436632307,
],
    [
    0.497905436632307,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PALM_TREES",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.4296726821263267,
],
    [
    0.4296726821263267,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "PALM_TREES",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.429672682126325,
],
    [
    0.429672682126325,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WAVES",
    "TREES",
]
matrix = [
    [
    1.0,
    -0.565288863725827,
],
    [
    -0.565288863725827,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WAVES",
    "TREES",
]
matrix = [
    [
    1.0,
    -0.5652888637258223,
],
    [
    -0.5652888637258223,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WAVES",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.8470897879022495,
],
    [
    0.8470897879022495,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "WAVES",
    "BEACH",
]
matrix = [
    [
    1.0,
    0.8470897879022476,
],
    [
    0.8470897879022476,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "AURORA_BOREALIS",
    "NIGHT",
]
matrix = [
    [
    1.0,
    0.421589224833344,
],
    [
    0.421589224833344,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "AURORA_BOREALIS",
    "NIGHT",
]
matrix = [
    [
    1.0,
    0.42158922483334327,
],
    [
    0.42158922483334327,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREES",
    "BEACH",
]
matrix = [
    [
    1.0,
    -0.5787044318849554,
],
    [
    -0.5787044318849554,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "TREES",
    "BEACH",
]
matrix = [
    [
    1.0,
    -0.5787044318849511,
],
    [
    -0.5787044318849511,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "EPISODE",
    "TITLE",
]
matrix = [
    [
    1.0,
    0.9999999999999009,
],
    [
    0.9999999999999009,
    1.0,
],
]
conditional = []
