[[correlations]]
entity = "original"
fields = [
    "longitude",
    "latitude",
]
matrix = [
    [
    1.0,
    -0.5588826806690763,
],
    [
    -0.5588826806690763,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "iata",
    "name",
]
matrix = [
    [
    1.0,
    0.9999999999675341,
],
    [
    0.9999999999675341,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "iata",
    "state",
]
matrix = [
    [
    1.0,
    0.9999999999996844,
],
    [
    0.9999999999996844,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "iata",
    "country",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "iata",
    "city",
]
matrix = [
    [
    1.0,
    0.9999999999197041,
],
    [
    0.9999999999197041,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "state",
]
matrix = [
    [
    1.0,
    0.9794167628256402,
],
    [
    0.9794167628256402,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "country",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "city",
]
matrix = [
    [
    1.0,
    0.9912906446186669,
],
    [
    0.9912906446186669,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "state",
    "city",
]
matrix = [
    [
    1.0,
    0.9080770646632836,
],
    [
    0.9080770646632836,
    1.0,
],
]
conditional = []
