[[constraints]]
table = "original"
type = "range"
field = "beer_servings"
min = 0.0
max = 376.0

[[constraints]]
table = "original"
type = "range"
field = "spirit_servings"
min = 0.0
max = 438.0

[[constraints]]
table = "original"
type = "range"
field = "wine_servings"
min = 0.0
max = 370.0

[[constraints]]
table = "original"
type = "range"
field = "total_litres_of_pure_alcohol"
min = 0.0
max = 14.4
