[[correlations]]
entity = "original"
fields = [
    "year",
    "passengers",
]
matrix = [
    [
    1.0,
    0.9218238352924205,
],
    [
    0.9218238352924205,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "passengers",
]
matrix = [
    [
    1.0,
    0.9505490437222238,
],
    [
    0.9505490437222238,
    1.0,
],
]
conditional = []
