[table]
name = "original"
count = 344

[table.stats]
source_rows = 344

[table.sort_by]
column = "species"
direction = "asc"

[[columns]]
name = "species"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_species.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 6
max_length = 9
avg_length = 6.593023255813954

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "island"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "species"
file = "original__species_island_sex_bill_length_mm_bill_depth_mm.tsv"
column = 1

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 5
max_length = 9
avg_length = 6.093023255813954

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "bill_length_mm"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "tuple_lookup"
source_field = "species"
file = "original__species_island_sex_bill_length_mm_bill_depth_mm.tsv"
column = 3

[columns.stats]
distinct_count = 164
null_rate = 0.005813953488372093
min = 32.1
max = 59.6
mean = 43.92192982456141
std = 5.4595837139265315

[columns.stats.percentiles]
p25 = 39.2
p50 = 44.5
p75 = 48.5
p95 = 52.0
p99 = 55.8

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "bill_depth_mm"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "tuple_lookup"
source_field = "species"
file = "original__species_island_sex_bill_length_mm_bill_depth_mm.tsv"
column = 4

[columns.stats]
distinct_count = 80
null_rate = 0.005813953488372093
min = 13.1
max = 21.5
mean = 17.151169590643274
std = 1.9747931568167811

[columns.stats.percentiles]
p25 = 15.6
p50 = 17.3
p75 = 18.7
p95 = 20.0
p99 = 21.1

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "flipper_length_mm"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 5.300468468475865
sigma = 0.0693051016813828

[columns.stats]
distinct_count = 55
null_rate = 0.005813953488372093
min = 172.0
max = 231.0
mean = 200.91520467836258
std = 14.061713679356892

[columns.stats.percentiles]
p25 = 190.0
p50 = 197.0
p75 = 213.0
p95 = 225.0
p99 = 230.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "body_mass_g"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 8.32549682256698
sigma = 0.18772859432886774

[columns.stats]
distinct_count = 94
null_rate = 0.005813953488372093
min = 2700.0
max = 6300.0
mean = 4201.754385964912
std = 801.9545356980957

[columns.stats.percentiles]
p25 = 3550.0
p50 = 4050.0
p75 = 4750.0
p95 = 5650.0
p99 = 6000.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "sex"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "species"
file = "original__species_island_sex_bill_length_mm_bill_depth_mm.tsv"
column = 2

[columns.nullable]
probability = 0.03197674418604651

[columns.stats]
distinct_count = 2
null_rate = 0.03197674418604651
min_length = 4
max_length = 6
avg_length = 4.990990990990991

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[constraints]]
type = "range"
field = "bill_length_mm"
min = 32.1
max = 59.6

[[constraints]]
type = "range"
field = "bill_depth_mm"
min = 13.1
max = 21.5

[[constraints]]
type = "range"
field = "flipper_length_mm"
min = 172.0
max = 231.0

[[constraints]]
type = "range"
field = "body_mass_g"
min = 2700.0
max = 6300.0

[[constraints]]
type = "check"
expr = "bill_depth_mm <= bill_length_mm"

[[constraints]]
type = "check"
expr = "bill_length_mm <= flipper_length_mm"

[[constraints]]
type = "check"
expr = "bill_length_mm <= body_mass_g"

[[constraints]]
type = "check"
expr = "bill_depth_mm <= flipper_length_mm"

[[constraints]]
type = "check"
expr = "bill_depth_mm <= body_mass_g"

[[constraints]]
type = "check"
expr = "flipper_length_mm <= body_mass_g"
