[[constraints]]
table = "original"
type = "range"
field = "survived"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "pclass"
min = 1.0
max = 3.0

[[constraints]]
table = "original"
type = "range"
field = "age"
min = 0.42
max = 80.0

[[constraints]]
table = "original"
type = "range"
field = "sibsp"
min = 0.0
max = 8.0

[[constraints]]
table = "original"
type = "range"
field = "parch"
min = 0.0
max = 6.0

[[constraints]]
table = "original"
type = "range"
field = "fare"
min = 0.0
max = 512.3292

[[constraints]]
table = "original"
type = "check"
expr = "survived <= pclass"

[[constraints]]
table = "original"
type = "check"
expr = "sibsp <= fare"

[[constraints]]
table = "original"
type = "check"
expr = "parch <= fare"
