[table]
name = "original"
count = 64

[table.stats]
source_rows = 64

[[table.scaling.custom]]
name = "Year"
field = "Year"
cardinality = 3

[[columns]]
name = "Model"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 64

[columns.stats]
distinct_count = 8
null_rate = 0.0
min_length = 2
max_length = 11
avg_length = 7.125

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Year"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 64

[columns.stats]
distinct_count = 3
null_rate = 0.0
min = 2017.0
max = 2019.0
mean = 2018.0
std = 0.8728715609439694

[columns.stats.percentiles]
p25 = 2017.0
p50 = 2018.0
p75 = 2019.0
p95 = 2019.0
p99 = 2019.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "Encoder"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 64

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 4
max_length = 11
avg_length = 7.5

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Task"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 64

[columns.stats]
distinct_count = 8
null_rate = 0.0
min_length = 3
max_length = 5
avg_length = 4.0

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Score"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 64

[columns.stats]
distinct_count = 56
null_rate = 0.0
min = 11.6
max = 97.8
mean = 75.57968749999998
std = 19.289697716554077

[columns.stats.percentiles]
p25 = 67.2
p50 = 75.5
p75 = 92.2
p95 = 96.9
p99 = 97.5

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "Year"
min = 2017.0
max = 2019.0

[[constraints]]
type = "range"
field = "Score"
min = 11.6
max = 97.8

[[constraints]]
type = "check"
expr = "Score <= Year"
