[table]
name = "original"
count = 1064

[table.stats]
source_rows = 1064

[[table.scaling.custom]]
name = "timepoint"
field = "timepoint"
cardinality = 19

[table.sort_by]
column = "event"
direction = "desc"

[[columns]]
name = "subject"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 1064

[columns.stats]
distinct_count = 14
null_rate = 0.0
min_length = 2
max_length = 3
avg_length = 2.2857142857142856

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "timepoint"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 1064

[columns.stats]
distinct_count = 19
null_rate = 0.0
min = 0.0
max = 18.0
mean = 9.0
std = 5.479801274970678

[columns.stats.percentiles]
p25 = 4.0
p50 = 9.0
p75 = 14.0
p95 = 18.0
p99 = 18.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "event"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 1064

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 3
max_length = 4
avg_length = 3.5

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "region"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 1064

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 7
max_length = 8
avg_length = 7.5

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "signal"
data_type = "float"
nullable = false
precision = 15

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 1064

[columns.stats]
distinct_count = 1064
null_rate = 0.0
min = -0.25548585958000003
max = 0.564984721448
mean = 0.003539768564097037
std = 0.09392971336541271

[columns.stats.percentiles]
p25 = -0.0460485902002
p50 = -0.0135663176316
p75 = 0.0242915167749
p95 = 0.208112190773
p99 = 0.340479918138

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "timepoint"
min = 0.0
max = 18.0

[[constraints]]
type = "range"
field = "signal"
min = -0.25548585958000003
max = 0.564984721448
