[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.8179411262715759,
],
    [
    0.8179411262715759,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.8342887759080051,
],
    [
    0.8342887759080051,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.8717537758865828,
],
    [
    0.8717537758865828,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.8818981264349859,
],
    [
    0.8818981264349859,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_width",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.9628654314027955,
],
    [
    0.9628654314027955,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_width",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.9376668235763413,
],
    [
    0.9376668235763413,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_width",
    "sepal_width",
]
matrix = [
    [
    1.0,
    -0.3661259325364395,
],
    [
    -0.3661259325364395,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_length",
    "sepal_width",
]
matrix = [
    [
    1.0,
    -0.42844010433054003,
],
    [
    -0.42844010433054003,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_length",
    "sepal_width",
]
matrix = [
    [
    1.0,
    -0.30963508601557777,
],
    [
    -0.30963508601557777,
    1.0,
],
]
conditional = []
