[[correlations]]
entity = "original"
fields = [
    "Spending_USD",
    "Year",
]
matrix = [
    [
    1.0,
    0.8262733812538644,
],
    [
    0.8262733812538644,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Spending_USD",
    "Year",
]
matrix = [
    [
    1.0,
    0.9315976070574148,
],
    [
    0.9315976070574148,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Spending_USD",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.5794304588530952,
],
    [
    0.5794304588530952,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Spending_USD",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.7474072371099253,
],
    [
    0.7474072371099253,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Year",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.9021745379694497,
],
    [
    0.9021745379694497,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Year",
    "Life_Expectancy",
]
matrix = [
    [
    1.0,
    0.896117410433818,
],
    [
    0.896117410433818,
    1.0,
],
]
conditional = []
