[table]
name = "original"
count = 136

[table.stats]
source_rows = 136

[[columns]]
name = "MMSA"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 136

[columns.stats]
distinct_count = 136
null_rate = 0.0
min_length = 8
max_length = 72
avg_length = 26.022058823529413

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "total_percent_at_risk"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 136

[columns.stats]
distinct_count = 131
null_rate = 0.0
min_length = 6
max_length = 6
avg_length = 6.0

[columns.traits]
semantic = "text"
cardinality = "high"

[[columns]]
name = "high_risk_per_ICU_bed"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 136

[columns.stats]
distinct_count = 136
null_rate = 0.0
min_length = 2
max_length = 11
avg_length = 10.654411764705882

[columns.traits]
semantic = "float"
cardinality = "unique"

[[columns]]
name = "high_risk_per_hospital"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 136

[columns.stats]
distinct_count = 136
null_rate = 0.0
min_length = 2
max_length = 11
avg_length = 9.889705882352942

[columns.traits]
semantic = "float"
cardinality = "unique"

[[columns]]
name = "icu_beds"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 136

[columns.stats]
distinct_count = 125
null_rate = 0.0
min_length = 1
max_length = 4
avg_length = 2.7720588235294117

[columns.traits]
semantic = "integer"
cardinality = "high"

[[columns]]
name = "hospitals"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 5
row_count = 136

[columns.stats]
distinct_count = 38
null_rate = 0.0
min_length = 1
max_length = 3
avg_length = 1.4852941176470589

[columns.traits]
semantic = "integer"
cardinality = "medium"

[[columns]]
name = "total_at_risk"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 6
row_count = 136

[columns.stats]
distinct_count = 136
null_rate = 0.0
min = 17941.53
max = 6165101.69
mean = 667188.7250220586
std = 884786.817983343

[columns.stats.percentiles]
p25 = 160884.86
p50 = 400036.73
p75 = 926872.05
p95 = 1925986.3
p99 = 5345495.42

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "total_at_risk"
min = 17941.53
max = 6165101.69
