[table]
name = "original"
count = 649

[table.stats]
source_rows = 649

[table.sort_by]
column = "Date"
direction = "asc"

[[columns]]
name = "Date"
data_type = "date"
nullable = false

[columns.generator]
type = "sequence"
start = "1914-12-01"
step = "30d"

[columns.stats]
null_rate = 0.0
min_temporal = "1914-12-01T00:00:00"
max_temporal = "1968-12-01T00:00:00"

[columns.traits]
semantic = "timestamp"

[[columns]]
name = "Price"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "time_series"
baseline = 55.0

[[columns.generator.components]]
type = "trend"
slope = 1.1285583755854949
degree = 1

[[columns.generator.components]]
type = "noise"
std_dev = 12.483962422579626

[columns.stats]
distinct_count = 637
null_rate = 0.0
min = 46.85
max = 985.93
mean = 290.807318952234
std = 256.0629060224077

[columns.stats.percentiles]
p25 = 106.9
p50 = 172.27
p75 = 436.73
p95 = 880.04
p99 = 953.31

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "Price"
min = 0.0
