[[constraints]]
table = "original"
type = "range"
field = "year"
min = 0.0

[[constraints]]
table = "original"
type = "range"
field = "miles"
min = 0.0

[[constraints]]
table = "original"
type = "range"
field = "gas"
min = 1.39
max = 3.31

[[constraints]]
table = "original"
type = "check"
expr = "year <= miles"

[[constraints]]
table = "original"
type = "check"
expr = "gas <= year"

[[constraints]]
table = "original"
type = "check"
expr = "gas <= miles"
