[[correlations]]
entity = "original"
fields = [
    "speeding",
    "not_distracted",
]
matrix = [
    [
    1.0,
    0.5880103950298474,
],
    [
    0.5880103950298474,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "not_distracted",
]
matrix = [
    [
    1.0,
    0.5628761482420019,
],
    [
    0.5628761482420019,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "alcohol",
]
matrix = [
    [
    1.0,
    0.6697185644227318,
],
    [
    0.6697185644227318,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "alcohol",
]
matrix = [
    [
    1.0,
    0.6426535137336531,
],
    [
    0.6426535137336531,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.5719755301227495,
],
    [
    0.5719755301227495,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.5416987193990679,
],
    [
    0.5416987193990679,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "total",
]
matrix = [
    [
    1.0,
    0.6115476008001184,
],
    [
    0.6115476008001184,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "speeding",
    "total",
]
matrix = [
    [
    1.0,
    0.5593646088343495,
],
    [
    0.5593646088343495,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "alcohol",
]
matrix = [
    [
    1.0,
    0.7328163816427737,
],
    [
    0.7328163816427737,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "alcohol",
]
matrix = [
    [
    1.0,
    0.7969591384225531,
],
    [
    0.7969591384225531,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.7473065439024139,
],
    [
    0.7473065439024139,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.7981356622471605,
],
    [
    0.7981356622471605,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "total",
]
matrix = [
    [
    1.0,
    0.8275603520837714,
],
    [
    0.8275603520837714,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "not_distracted",
    "total",
]
matrix = [
    [
    1.0,
    0.877605056190591,
],
    [
    0.877605056190591,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alcohol",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.7835199456551566,
],
    [
    0.7835199456551566,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alcohol",
    "no_previous",
]
matrix = [
    [
    1.0,
    0.8560115842345808,
],
    [
    0.8560115842345808,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alcohol",
    "total",
]
matrix = [
    [
    1.0,
    0.8526132163334914,
],
    [
    0.8526132163334914,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alcohol",
    "total",
]
matrix = [
    [
    1.0,
    0.894576069808138,
],
    [
    0.894576069808138,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "no_previous",
    "total",
]
matrix = [
    [
    1.0,
    0.9561791745723076,
],
    [
    0.9561791745723076,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "no_previous",
    "total",
]
matrix = [
    [
    1.0,
    0.9582060568648609,
],
    [
    0.9582060568648609,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ins_premium",
    "ins_losses",
]
matrix = [
    [
    1.0,
    0.623116438519707,
],
    [
    0.623116438519707,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ins_premium",
    "ins_losses",
]
matrix = [
    [
    1.0,
    0.6466968325791855,
],
    [
    0.6466968325791855,
    1.0,
],
]
conditional = []
