[[correlations]]
entity = "original"
fields = [
    "APPEARANCES",
    "YEAR",
]
matrix = [
    [
    1.0,
    -0.338195913202244,
],
    [
    -0.338195913202244,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "APPEARANCES",
    "page_id",
]
matrix = [
    [
    1.0,
    -0.53756543260108,
],
    [
    -0.53756543260108,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEX",
    "name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEX",
    "urlslug",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEX",
    "GSM",
]
matrix = [
    [
    1.0,
    0.3021223104415353,
],
    [
    0.3021223104415353,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "SEX",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.30352956577020673,
],
    [
    0.30352956577020673,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ID",
    "name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ID",
    "urlslug",
]
matrix = [
    [
    1.0,
    0.9999999999999376,
],
    [
    0.9999999999999376,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ID",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.45703854548270123,
],
    [
    0.45703854548270123,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "EYE",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "ALIGN",
]
matrix = [
    [
    1.0,
    0.999999999999896,
],
    [
    0.999999999999896,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "urlslug",
]
matrix = [
    [
    1.0,
    0.9999999997711941,
],
    [
    0.9999999997711941,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "GSM",
]
matrix = [
    [
    1.0,
    0.9999999999999998,
],
    [
    0.9999999999999998,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "ALIVE",
]
matrix = [
    [
    1.0,
    0.99999999999994,
],
    [
    0.99999999999994,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.9999999999954038,
],
    [
    0.9999999999954038,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "HAIR",
]
matrix = [
    [
    1.0,
    0.9999999999999082,
],
    [
    0.9999999999999082,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "EYE",
    "urlslug",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "EYE",
    "GSM",
]
matrix = [
    [
    1.0,
    0.4444444444444445,
],
    [
    0.4444444444444445,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "EYE",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.48671945727575944,
],
    [
    0.48671945727575944,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ALIGN",
    "urlslug",
]
matrix = [
    [
    1.0,
    0.9999999999998367,
],
    [
    0.9999999999998367,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ALIGN",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.40332450957569427,
],
    [
    0.40332450957569427,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "urlslug",
    "GSM",
]
matrix = [
    [
    1.0,
    0.9999999999999999,
],
    [
    0.9999999999999999,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "urlslug",
    "ALIVE",
]
matrix = [
    [
    1.0,
    0.999999999999941,
],
    [
    0.999999999999941,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "urlslug",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.9999999999952274,
],
    [
    0.9999999999952274,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "urlslug",
    "HAIR",
]
matrix = [
    [
    1.0,
    0.9999999999999387,
],
    [
    0.9999999999999387,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "GSM",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.9280736795734381,
],
    [
    0.9280736795734381,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "GSM",
    "HAIR",
]
matrix = [
    [
    1.0,
    0.41394756139712446,
],
    [
    0.41394756139712446,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "ALIVE",
    "FIRST APPEARANCE",
]
matrix = [
    [
    1.0,
    0.40347810313563715,
],
    [
    0.40347810313563715,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "FIRST APPEARANCE",
    "HAIR",
]
matrix = [
    [
    1.0,
    0.43703054110579476,
],
    [
    0.43703054110579476,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "EYE"

[[correlations.distributions]]
when = "Photocellular Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.4242502695479309

[[correlations.distributions]]
when = "Orange Eyes"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 32.0
min = 2.0

[[correlations.distributions]]
when = "Blue Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.749027369758606
sigma = 1.599706493009572

[[correlations.distributions]]
when = "Auburn Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 2.0
shape = 0.8577886584793518

[[correlations.distributions]]
when = "Brown Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.3157162764831827
sigma = 1.3719074404031513

[[correlations.distributions]]
when = "Green Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.426719150666194
sigma = 1.5276390493244427

[[correlations.distributions]]
when = "Yellow Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.1998215241074464
sigma = 1.3894076152260892

[[correlations.distributions]]
when = "Hazel Eyes"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 99.54095913416681
shape = 0.5088576034793041

[[correlations.distributions]]
when = "White Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.1480579122627854
sigma = 1.3625446805967407

[[correlations.distributions]]
when = "Red Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.44619840370421515

[[correlations.distributions]]
when = "Amber Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 11.0
shape = 0.9622125609805009

[[correlations.distributions]]
when = "Gold Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 2.0
shape = 0.8744482884294515

[[correlations.distributions]]
when = "Violet Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.050761421319796954

[[correlations.distributions]]
when = "Grey Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.7330087603428668
sigma = 1.4463688655751694

[[correlations.distributions]]
when = "Pink Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 4.0
shape = 0.7205397032049005

[[correlations.distributions]]
when = "Purple Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 3.0
shape = 0.5007557315791493

[[correlations.distributions]]
when = "Black Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.13549381540983
sigma = 1.32925978841595

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "page_id"
given = "EYE"

[[correlations.distributions]]
when = "Blue Eyes"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 107965.44498643481
shape = 0.9117459412473226

[[correlations.distributions]]
when = "Black Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000007942388075992538

[[correlations.distributions]]
when = "Green Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000008459209372641196

[[correlations.distributions]]
when = "Yellow Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000006892777002874689

[[correlations.distributions]]
when = "Grey Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 10.308094793784637
sigma = 1.7817429646615293

[[correlations.distributions]]
when = "Auburn Hair"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 192614.0
min = 4935.0

[[correlations.distributions]]
when = "Purple Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.00001655603686319865

[[correlations.distributions]]
when = "Orange Eyes"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 309545.0
min = 7575.0

[[correlations.distributions]]
when = "Red Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000008056346708598917

[[correlations.distributions]]
when = "Photocellular Eyes"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 333530.0
min = 1843.0

[[correlations.distributions]]
when = "Hazel Eyes"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 10.3720608043873
sigma = 1.6569802236643114

[[correlations.distributions]]
when = "Amber Eyes"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 2657.0
shape = 0.6407345887491485

[[correlations.distributions]]
when = "Brown Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.0000073417385520872135

[[correlations.distributions]]
when = "White Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000008709580974551054

[[correlations.distributions]]
when = "Pink Eyes"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 160584.0
min = 2780.0

[[correlations.distributions]]
when = "Gold Eyes"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 374789.0
min = 8324.0

[[correlations.distributions]]
when = "Violet Eyes"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000007998848165864115

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.000006782364340844538

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "SEX"

[[correlations.distributions]]
when = "Female Characters"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.5052769343810378

[[correlations.distributions]]
when = "Male Characters"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.5273649499227903

[[correlations.distributions]]
when = "Genderless Characters"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.07786885245901638

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "HAIR"

[[correlations.distributions]]
when = "Blue Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.5810096786699461

[[correlations.distributions]]
when = "Green Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.45853045847821744

[[correlations.distributions]]
when = "Gold Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 2.0
shape = 0.7096888626410413

[[correlations.distributions]]
when = "Orange Hair"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.2360295153175582
sigma = 1.1506373085181718

[[correlations.distributions]]
when = "Blond Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.4600003319669842

[[correlations.distributions]]
when = "Black Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.47155271449327696

[[correlations.distributions]]
when = "Red Hair"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.2469175568740156
sigma = 1.4218449176322456

[[correlations.distributions]]
when = "Purple Hair"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.1817875372441384
sigma = 1.2819759193193776

[[correlations.distributions]]
when = "Pink Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.6177377510065771

[[correlations.distributions]]
when = "White Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.4790042350729091

[[correlations.distributions]]
when = "Brown Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.5009099296917575

[[correlations.distributions]]
when = "Grey Hair"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.5469312399350763

[[correlations.distributions]]
when = "Strawberry Blond Hair"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.8657841596198863
sigma = 1.731648437860057

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "ALIGN"

[[correlations.distributions]]
when = "Good Characters"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.297426535824036
sigma = 1.4816275780454622

[[correlations.distributions]]
when = "Bad Characters"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.6531870778617406

[[correlations.distributions]]
when = "Neutral Characters"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.05880574289144
sigma = 1.3227371036753555

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "GSM"

[[correlations.distributions]]
when = "Bisexual Characters"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 16.0
shape = 0.945921225231463

[[correlations.distributions]]
when = "Homosexual Characters"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.7960011133444613
sigma = 1.3984601539619639

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "page_id"
given = "GSM"

[[correlations.distributions]]
when = "Homosexual Characters"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000009237330103689031

[[correlations.distributions]]
when = "Bisexual Characters"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1614.0
shape = 0.5576968781117092

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.000006782364340844538

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "APPEARANCES"
given = "ID"

[[correlations.distributions]]
when = "Public Identity"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 2.201885166636265
sigma = 1.3788781880744951

[[correlations.distributions]]
when = "Identity Unknown"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 1.8212568272489023

[[correlations.distributions]]
when = "Secret Identity"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1.0
shape = 0.4824255137348368

[correlations.default]
kind = "pareto"

[correlations.default.params]
scale = 1.0
shape = 0.5229189016414668

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "page_id"
given = "ID"

[[correlations.distributions]]
when = "Public Identity"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 404010.0
min = 1386.0

[[correlations.distributions]]
when = "Identity Unknown"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 252709.0
min = 127141.0

[[correlations.distributions]]
when = "Secret Identity"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.000008226485588509114

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.000006782364340844538
