[[constraints]]
table = "original"
type = "range"
field = "page_id"
min = 1380.0
max = 404010.0

[[constraints]]
table = "original"
type = "range"
field = "APPEARANCES"
min = 1.0
max = 3093.0

[[constraints]]
table = "original"
type = "range"
field = "YEAR"
min = 1935.0
max = 2013.0
