[[constraints]]
table = "original"
type = "range"
field = ""
min = 0.0
max = 59.0

[[constraints]]
table = "original"
type = "range"
field = "subject"
min = 1.0
max = 20.0

[[constraints]]
table = "original"
type = "range"
field = "solutions"
min = 1.0
max = 3.0

[[constraints]]
table = "original"
type = "range"
field = "score"
min = 2.0
max = 9.0

[[constraints]]
table = "original"
type = "check"
expr = "solutions <= score"
