[table]
name = "original"
count = 299

[table.stats]
source_rows = 299

[[table.scaling.custom]]
name = "answerKey"
field = "answerKey"
cardinality = 8

[[columns]]
name = "id"
data_type = "string"
nullable = false
primary_key = true

[columns.generator]
type = "tuple_lookup"
source_field = "question"
file = "original__question_id_answerKey.tsv"
column = 1

[columns.stats]
distinct_count = 299
null_rate = 0.0
min_length = 12
max_length = 22
avg_length = 15.538461538461538

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "question"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_question.dict.txt"
expansion = "shuffle"

[columns.stats]
distinct_count = 299
null_rate = 0.0
min_length = 30
max_length = 568
avg_length = 133.86622073578596

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "choices"
data_type = "string"
nullable = false

[columns.generator]
type = "sequence"
start = 1
step = 1

[columns.stats]
null_rate = 0.0

[columns.traits]

[[columns]]
name = "answerKey"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "question"
file = "original__question_id_answerKey.tsv"
column = 2

[columns.stats]
distinct_count = 8
null_rate = 0.0
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "medium"
