[[constraints]]
table = "original"
type = "range"
field = "year"
min = 2000.0
max = 2010.0

[[constraints]]
table = "original"
type = "range"
field = "month"
min = 1.0
max = 12.0

[[constraints]]
table = "original"
type = "range"
field = "count"
min = 2.0
max = 2440.0

[[constraints]]
table = "original"
type = "range"
field = "rate"
min = 0.3
max = 27.1

[[constraints]]
table = "original"
type = "check"
expr = "month <= year"

[[constraints]]
table = "original"
type = "check"
expr = "rate <= year"

[[constraints]]
table = "original"
type = "check"
expr = "rate <= count"
