[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "n_fertility",
]
matrix = [
    [
    1.0,
    -0.8373275309687552,
],
    [
    -0.8373275309687552,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "n_fertility",
]
matrix = [
    [
    1.0,
    -0.8506759909141104,
],
    [
    -0.8506759909141104,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "year",
]
matrix = [
    [
    1.0,
    0.4783341802969815,
],
    [
    0.4783341802969815,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "year",
]
matrix = [
    [
    1.0,
    0.50973566365817,
],
    [
    0.50973566365817,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    0.9676822810487342,
],
    [
    0.9676822810487342,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    0.9880744564571646,
],
    [
    0.9880744564571646,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.8201573608720886,
],
    [
    -0.8201573608720886,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.8506746654736181,
],
    [
    -0.8506746654736181,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.9676822810487342,
],
    [
    0.9676822810487342,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.9880744564571646,
],
    [
    0.9880744564571646,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8266282357800007,
],
    [
    -0.8266282357800007,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8520709027704185,
],
    [
    -0.8520709027704185,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "year",
]
matrix = [
    [
    1.0,
    -0.42934510014510624,
],
    [
    -0.42934510014510624,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "year",
]
matrix = [
    [
    1.0,
    -0.44944094539578966,
],
    [
    -0.44944094539578966,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    -0.8290328894528592,
],
    [
    -0.8290328894528592,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    -0.8526987537188193,
],
    [
    -0.8526987537188193,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "p_fertility",
]
matrix = [
    [
    1.0,
    0.9479065868764391,
],
    [
    0.9479065868764391,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "p_fertility",
]
matrix = [
    [
    1.0,
    0.9495117746448476,
],
    [
    0.9495117746448476,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    -0.8382091517688035,
],
    [
    -0.8382091517688035,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    -0.8455095825092966,
],
    [
    -0.8455095825092966,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "fertility",
]
matrix = [
    [
    1.0,
    0.9811491481922694,
],
    [
    0.9811491481922694,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_fertility",
    "fertility",
]
matrix = [
    [
    1.0,
    0.9808392844736009,
],
    [
    0.9808392844736009,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    0.43916495155193763,
],
    [
    0.43916495155193763,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "n_life_expect",
]
matrix = [
    [
    1.0,
    0.47418430178303456,
],
    [
    0.47418430178303456,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.39659488758152595,
],
    [
    -0.39659488758152595,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.41586109456376136,
],
    [
    -0.41586109456376136,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.450087646353469,
],
    [
    0.450087646353469,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.47227535817459687,
],
    [
    0.47227535817459687,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.4377733635923912,
],
    [
    -0.4377733635923912,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.46023195916110743,
],
    [
    -0.46023195916110743,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.8122312779249178,
],
    [
    -0.8122312779249178,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "p_fertility",
]
matrix = [
    [
    1.0,
    -0.8416075318398676,
],
    [
    -0.8416075318398676,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.9562531678131599,
],
    [
    0.9562531678131599,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    0.9733902605504653,
],
    [
    0.9733902605504653,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8201573608720886,
],
    [
    -0.8201573608720886,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "n_life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8506746654736181,
],
    [
    -0.8506746654736181,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_fertility",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    -0.8182339056779333,
],
    [
    -0.8182339056779333,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_fertility",
    "p_life_expect",
]
matrix = [
    [
    1.0,
    -0.8490737257383424,
],
    [
    -0.8490737257383424,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_fertility",
    "fertility",
]
matrix = [
    [
    1.0,
    0.9811491481922694,
],
    [
    0.9811491481922694,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_fertility",
    "fertility",
]
matrix = [
    [
    1.0,
    0.9808392844736009,
],
    [
    0.9808392844736009,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8373275309687552,
],
    [
    -0.8373275309687552,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "p_life_expect",
    "fertility",
]
matrix = [
    [
    1.0,
    -0.8506759909141104,
],
    [
    -0.8506759909141104,
    1.0,
],
]
conditional = []
