[[constraints]]
table = "original"
type = "range"
field = "year"
min = 1955.0
max = 2000.0

[[constraints]]
table = "original"
type = "range"
field = "fertility"
min = 1.03
max = 8.23

[[constraints]]
table = "original"
type = "range"
field = "life_expect"
min = 27.79
max = 81.57

[[constraints]]
table = "original"
type = "range"
field = "n_fertility"
min = 1.03
max = 8.23

[[constraints]]
table = "original"
type = "range"
field = "n_life_expect"
min = 27.79
max = 81.57

[[constraints]]
table = "original"
type = "range"
field = "p_fertility"
min = 1.16
max = 8.23

[[constraints]]
table = "original"
type = "range"
field = "p_life_expect"
min = 27.79
max = 80.24

[[constraints]]
table = "original"
type = "check"
expr = "fertility <= year"

[[constraints]]
table = "original"
type = "check"
expr = "life_expect <= year"

[[constraints]]
table = "original"
type = "check"
expr = "n_fertility <= year"

[[constraints]]
table = "original"
type = "check"
expr = "n_life_expect <= year"

[[constraints]]
table = "original"
type = "check"
expr = "p_fertility <= year"

[[constraints]]
table = "original"
type = "check"
expr = "p_life_expect <= year"

[[constraints]]
table = "original"
type = "check"
expr = "fertility <= life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "fertility <= n_life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "fertility <= p_life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "n_fertility <= life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "p_fertility <= life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "n_fertility <= n_life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "n_fertility <= p_life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "p_fertility <= n_life_expect"

[[constraints]]
table = "original"
type = "check"
expr = "p_fertility <= p_life_expect"
