[[correlations]]
entity = "original"
fields = [
    "item_id",
    "common_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "item_id",
    "gap_species_code",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "item_id",
    "scientific_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "common_name",
    "gap_species_code",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "common_name",
    "scientific_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "gap_species_code",
    "scientific_name",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "habitat_yearround_pct"
given = "scientific_name"

[[correlations.distributions]]
when = "Turdus migratorius"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9996
min = 0.0

[[correlations.distributions]]
when = "Lithobates catesbeianus"
distribution = "exponential"

[correlations.distributions.params]
lambda = 5.665569673030627

[[correlations.distributions]]
when = "Odocoileus virginianus"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9825
min = 0.0

[[correlations.distributions]]
when = "Thamnophis sirtalis"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9993
min = 0.0

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 0.9996
min = 0.0

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "habitat_yearround_pct"
given = "common_name"

[[correlations.distributions]]
when = "American Bullfrog"
distribution = "exponential"

[correlations.distributions.params]
lambda = 5.665569673030627

[[correlations.distributions]]
when = "Common Gartersnake"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9993
min = 0.0

[[correlations.distributions]]
when = "White-tailed Deer"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9825
min = 0.0

[[correlations.distributions]]
when = "American Robin"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9996
min = 0.0

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 0.9996
min = 0.0

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "habitat_yearround_pct"
given = "gap_species_code"

[[correlations.distributions]]
when = "rCOGAx"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9993
min = 0.0

[[correlations.distributions]]
when = "bAMROx"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9996
min = 0.0

[[correlations.distributions]]
when = "mWTDEx"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9825
min = 0.0

[[correlations.distributions]]
when = "aAMBUx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 5.665569673030627

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 0.9996
min = 0.0

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "habitat_yearround_pct"
given = "item_id"

[[correlations.distributions]]
when = "58fa3f0be4b0b7ea54524859"
distribution = "exponential"

[correlations.distributions.params]
lambda = 5.665569673030627

[[correlations.distributions]]
when = "58fa817ae4b0b7ea54525c2f"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9825
min = 0.0

[[correlations.distributions]]
when = "58fa449fe4b0b7ea54524c5e"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9996
min = 0.0

[[correlations.distributions]]
when = "58fe0f4fe4b0074928294636"
distribution = "uniform"

[correlations.distributions.params]
max = 0.9993
min = 0.0

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 0.9996
min = 0.0
