[table]
name = "original"
count = 173

[table.stats]
source_rows = 173

[[columns]]
name = "URL"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 173

[columns.stats]
distinct_count = 173
null_rate = 0.0
min_length = 36
max_length = 67
avg_length = 49.716763005780344

[columns.traits]
semantic = "url"
cardinality = "unique"

[[columns]]
name = "Name/Alias"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 173

[columns.nullable]
probability = 0.057803468208092484

[columns.stats]
distinct_count = 162
null_rate = 0.057803468208092484
min_length = 4
max_length = 35
avg_length = 14.466257668711657

[columns.traits]
semantic = "text"
pii = true
cardinality = "unique"

[[columns]]
name = "Appearances"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 173

[columns.stats]
distinct_count = 148
null_rate = 0.0
min = 2.0
max = 4333.0
mean = 414.05202312138726
std = 677.9919501639841

[columns.stats.percentiles]
p25 = 58.0
p50 = 132.0
p75 = 491.0
p95 = 1761.0
p99 = 3130.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "Current?"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 173

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 2
max_length = 3
avg_length = 2.4739884393063583

[columns.traits]
semantic = "boolean"
cardinality = "medium"

[[columns]]
name = "Gender"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 173

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 4
max_length = 6
avg_length = 4.670520231213873

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Probationary Introl"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 5
row_count = 173

[columns.nullable]
probability = 0.9132947976878613

[columns.stats]
distinct_count = 12
null_rate = 0.9132947976878613
min_length = 6
max_length = 6
avg_length = 6.0

[columns.traits]
semantic = "categorical"
cardinality = "high"

[[columns]]
name = "Full/Reserve Avengers Intro"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 6
row_count = 173

[columns.nullable]
probability = 0.08092485549132948

[columns.stats]
distinct_count = 93
null_rate = 0.08092485549132948
min_length = 5
max_length = 6
avg_length = 5.817610062893082

[columns.traits]
semantic = "text"
cardinality = "high"

[[columns]]
name = "Year"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 7
row_count = 173

[columns.stats]
distinct_count = 42
null_rate = 0.0
min = 1900.0
max = 2015.0
mean = 1988.4450867052024
std = 30.37466894486063

[columns.stats.percentiles]
p25 = 1979.0
p50 = 1996.0
p75 = 2010.0
p95 = 2013.0
p99 = 2014.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "Years since joining"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 8
row_count = 173

[columns.stats]
distinct_count = 42
null_rate = 0.0
min = 0.0
max = 115.0
mean = 26.55491329479769
std = 30.374668944860616

[columns.stats.percentiles]
p25 = 5.0
p50 = 19.0
p75 = 36.0
p95 = 115.0
p99 = 115.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "Honorary"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 9
row_count = 173

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 4
max_length = 12
avg_length = 4.757225433526012

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Death1"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 10
row_count = 173

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 2
max_length = 3
avg_length = 2.398843930635838

[columns.traits]
semantic = "boolean"
cardinality = "medium"

[[columns]]
name = "Return1"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 11
row_count = 173

[columns.nullable]
probability = 0.6011560693641619

[columns.stats]
distinct_count = 2
null_rate = 0.6011560693641619
min_length = 2
max_length = 3
avg_length = 2.6666666666666665

[columns.traits]
semantic = "boolean"
cardinality = "medium"

[[columns]]
name = "Death2"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 12
row_count = 173

[columns.nullable]
probability = 0.9017341040462428

[columns.stats]
distinct_count = 2
null_rate = 0.9017341040462428
min_length = 2
max_length = 3
avg_length = 2.9411764705882355

[columns.traits]
semantic = "boolean"
cardinality = "medium"

[[columns]]
name = "Return2"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 13
row_count = 173

[columns.nullable]
probability = 0.9075144508670521

[columns.stats]
distinct_count = 2
null_rate = 0.9075144508670521
min_length = 2
max_length = 3
avg_length = 2.5

[columns.traits]
semantic = "boolean"
cardinality = "medium"

[[columns]]
name = "Death3"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 14
row_count = 173

[columns.nullable]
probability = 0.9884393063583815

[columns.stats]
distinct_count = 1
null_rate = 0.9884393063583815
min_length = 3
max_length = 3
avg_length = 3.0

[columns.traits]
semantic = "boolean"
cardinality = "high"

[[columns]]
name = "Return3"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 15
row_count = 173

[columns.nullable]
probability = 0.9884393063583815

[columns.stats]
distinct_count = 2
null_rate = 0.9884393063583815
min_length = 2
max_length = 3
avg_length = 2.5

[columns.traits]
semantic = "boolean"
cardinality = "unique"

[[columns]]
name = "Death4"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 16
row_count = 173

[columns.nullable]
probability = 0.9942196531791907

[columns.stats]
distinct_count = 1
null_rate = 0.9942196531791907
min_length = 3
max_length = 3
avg_length = 3.0

[columns.traits]
semantic = "boolean"
cardinality = "unique"

[[columns]]
name = "Return4"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 17
row_count = 173

[columns.nullable]
probability = 0.9942196531791907

[columns.stats]
distinct_count = 1
null_rate = 0.9942196531791907
min_length = 3
max_length = 3
avg_length = 3.0

[columns.traits]
semantic = "boolean"
cardinality = "unique"

[[columns]]
name = "Death5"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 18
row_count = 173

[columns.nullable]
probability = 0.9942196531791907

[columns.stats]
distinct_count = 1
null_rate = 0.9942196531791907
min_length = 3
max_length = 3
avg_length = 3.0

[columns.traits]
semantic = "boolean"
cardinality = "unique"

[[columns]]
name = "Return5"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 19
row_count = 173

[columns.nullable]
probability = 0.9942196531791907

[columns.stats]
distinct_count = 1
null_rate = 0.9942196531791907
min_length = 3
max_length = 3
avg_length = 3.0

[columns.traits]
semantic = "boolean"
cardinality = "unique"

[[columns]]
name = "Notes"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 20
row_count = 173

[columns.stats]
distinct_count = 72
null_rate = 0.0
min_length = 2
max_length = 256
avg_length = 43.53179190751445

[columns.traits]
semantic = "text"
cardinality = "high"

[[constraints]]
type = "range"
field = "Appearances"
min = 2.0
max = 4333.0

[[constraints]]
type = "range"
field = "Year"
min = 1900.0
max = 2015.0

[[constraints]]
type = "range"
field = "Years since joining"
min = 0.0
max = 115.0

[[constraints]]
type = "check"
expr = "Years since joining <= Year"
