[table]
name = "original"
count = 187

[table.stats]
source_rows = 187

[[table.scaling.custom]]
name = "region"
field = "region"
cardinality = 6

[[columns]]
name = "country"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 187

[columns.stats]
distinct_count = 187
null_rate = 0.0
min_length = 3
max_length = 30
avg_length = 8.566844919786096

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "income"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 187

[columns.stats]
distinct_count = 187
null_rate = 0.0
min = 599.0
max = 132877.0
mean = 17232.24064171123
std = 19310.63288224257

[columns.stats.percentiles]
p25 = 3661.0
p50 = 10996.0
p75 = 24200.0
p95 = 52469.0
p99 = 82633.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "health"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 187

[columns.stats]
distinct_count = 140
null_rate = 0.0
min = 48.5
max = 84.1
mean = 71.67326203208556
std = 7.748959108094908

[columns.stats.percentiles]
p25 = 65.5
p50 = 73.13
p75 = 77.9
p95 = 82.0
p99 = 82.9

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "population"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 187

[columns.stats]
distinct_count = 187
null_rate = 0.0
min = 52993.0
max = 1376048943.0
mean = 39088869.51871658
std = 143289835.8663455

[columns.stats.percentiles]
p25 = 2262485.0
p50 = 8544586.0
p75 = 27977863.0
p95 = 127017224.0
p99 = 321773631.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "region"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 187

[columns.stats]
distinct_count = 6
null_rate = 0.0
min_length = 7
max_length = 24
avg_length = 16.422459893048128

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[constraints]]
type = "range"
field = "income"
min = 599.0
max = 132877.0

[[constraints]]
type = "range"
field = "health"
min = 48.5
max = 84.1

[[constraints]]
type = "range"
field = "population"
min = 52993.0
max = 1376048943.0

[[constraints]]
type = "check"
expr = "health <= income"

[[constraints]]
type = "check"
expr = "income <= population"

[[constraints]]
type = "check"
expr = "health <= population"
