[table]
name = "original"
count = 344

[table.stats]
source_rows = 344

[[table.scaling.custom]]
name = "Species"
field = "Species"
cardinality = 3

[[table.scaling.custom]]
name = "Island"
field = "Island"
cardinality = 3

[[table.scaling.custom]]
name = "Sex"
field = "Sex"
cardinality = 3

[table.sort_by]
column = "Species"
direction = "asc"

[[columns]]
name = "Species"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_Species.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 6
max_length = 9
avg_length = 6.593023255813954

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "Island"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "Species"
file = "original__Species_Island_Sex_Beak_Length__mm__Beak_Depth__mm_.tsv"
column = 1

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 5
max_length = 9
avg_length = 6.093023255813954

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "Beak Length (mm)"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "tuple_lookup"
source_field = "Species"
file = "original__Species_Island_Sex_Beak_Length__mm__Beak_Depth__mm_.tsv"
column = 3

[columns.stats]
distinct_count = 164
null_rate = 0.005813953488372093
min = 32.1
max = 59.6
mean = 43.92192982456141
std = 5.4595837139265315

[columns.stats.percentiles]
p25 = 39.2
p50 = 44.5
p75 = 48.5
p95 = 52.0
p99 = 55.8

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "Beak Depth (mm)"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "tuple_lookup"
source_field = "Species"
file = "original__Species_Island_Sex_Beak_Length__mm__Beak_Depth__mm_.tsv"
column = 4

[columns.stats]
distinct_count = 80
null_rate = 0.005813953488372093
min = 13.1
max = 21.5
mean = 17.151169590643274
std = 1.9747931568167811

[columns.stats.percentiles]
p25 = 15.6
p50 = 17.3
p75 = 18.7
p95 = 20.0
p99 = 21.1

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "Flipper Length (mm)"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 5.300468468475865
sigma = 0.0693051016813828

[columns.stats]
distinct_count = 55
null_rate = 0.005813953488372093
min = 172.0
max = 231.0
mean = 200.91520467836258
std = 14.061713679356892

[columns.stats.percentiles]
p25 = 190.0
p50 = 197.0
p75 = 213.0
p95 = 225.0
p99 = 230.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "Body Mass (g)"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 8.32549682256698
sigma = 0.18772859432886774

[columns.stats]
distinct_count = 94
null_rate = 0.005813953488372093
min = 2700.0
max = 6300.0
mean = 4201.754385964912
std = 801.9545356980957

[columns.stats.percentiles]
p25 = 3550.0
p50 = 4050.0
p75 = 4750.0
p95 = 5650.0
p99 = 6000.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "Sex"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "Species"
file = "original__Species_Island_Sex_Beak_Length__mm__Beak_Depth__mm_.tsv"
column = 2

[columns.nullable]
probability = 0.029069767441860465

[columns.stats]
distinct_count = 3
null_rate = 0.029069767441860465
min_length = 1
max_length = 6
avg_length = 4.979041916167665

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[constraints]]
type = "range"
field = "Beak Length (mm)"
min = 32.1
max = 59.6

[[constraints]]
type = "range"
field = "Beak Depth (mm)"
min = 13.1
max = 21.5

[[constraints]]
type = "range"
field = "Flipper Length (mm)"
min = 172.0
max = 231.0

[[constraints]]
type = "range"
field = "Body Mass (g)"
min = 2700.0
max = 6300.0

[[constraints]]
type = "check"
expr = "Beak Depth (mm) <= Beak Length (mm)"

[[constraints]]
type = "check"
expr = "Beak Length (mm) <= Flipper Length (mm)"

[[constraints]]
type = "check"
expr = "Beak Length (mm) <= Body Mass (g)"

[[constraints]]
type = "check"
expr = "Beak Depth (mm) <= Flipper Length (mm)"

[[constraints]]
type = "check"
expr = "Beak Depth (mm) <= Body Mass (g)"

[[constraints]]
type = "check"
expr = "Flipper Length (mm) <= Body Mass (g)"
