[[constraints]]
table = "original"
type = "range"
field = "lat"
min = 25.79325
max = 48.79275

[[constraints]]
table = "original"
type = "range"
field = "long"
min = -124.2460278
max = -70.30875

[[constraints]]
table = "original"
type = "range"
field = "cnt"
min = 23.0
max = 25129.0

[[constraints]]
table = "original"
type = "check"
expr = "long <= lat"

[[constraints]]
table = "original"
type = "check"
expr = "long <= cnt"
