[table]
name = "original"
count = 551

[table.stats]
source_rows = 551

[[table.scaling.custom]]
name = "Consider the following hypothetical situations: <br>In Lottery A, you have a 50% chance of success, with a payout of $100. <br>In Lottery B, you have a 90% chance of success, with a payout of $20. <br><br>Assuming you have $10 to bet, would you play Lottery A or Lottery B?"
field = "Consider the following hypothetical situations: <br>In Lottery A, you have a 50% chance of success, with a payout of $100. <br>In Lottery B, you have a 90% chance of success, with a payout of $20. <br><br>Assuming you have $10 to bet, would you play Lottery A or Lottery B?"
cardinality = 3

[[table.scaling.custom]]
name = "Do you ever smoke cigarettes?"
field = "Do you ever smoke cigarettes?"
cardinality = 3

[[table.scaling.custom]]
name = "Do you ever drink alcohol?"
field = "Do you ever drink alcohol?"
cardinality = 3

[[table.scaling.custom]]
name = "Do you ever gamble?"
field = "Do you ever gamble?"
cardinality = 3

[[table.scaling.custom]]
name = "Have you ever been skydiving?"
field = "Have you ever been skydiving?"
cardinality = 3

[[table.scaling.custom]]
name = "Do you ever drive above the speed limit?"
field = "Do you ever drive above the speed limit?"
cardinality = 3

[[table.scaling.custom]]
name = "Have you ever cheated on your significant other?"
field = "Have you ever cheated on your significant other?"
cardinality = 3

[[table.scaling.custom]]
name = "Do you eat steak?"
field = "Do you eat steak?"
cardinality = 3

[[table.scaling.custom]]
name = "How do you like your steak prepared?"
field = "How do you like your steak prepared?"
cardinality = 6

[[table.scaling.custom]]
name = "Gender"
field = "Gender"
cardinality = 3

[[table.scaling.custom]]
name = "Age"
field = "Age"
cardinality = 5

[[table.scaling.custom]]
name = "Household Income"
field = "Household Income"
cardinality = 6

[[table.scaling.custom]]
name = "Education"
field = "Education"
cardinality = 6

[[table.scaling.custom]]
name = "Location (Census Region)"
field = "Location (Census Region)"
cardinality = 10

[table.sort_by]
column = "RespondentID"
direction = "desc"

[[columns]]
name = "RespondentID"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 551

[columns.stats]
distinct_count = 550
null_rate = 0.0018148820326678765
min = 3234760413.0
max = 3237565956.0
mean = 3234844785.9672728
std = 126575.38603025988

[columns.stats.percentiles]
p25 = 3234799491.0
p50 = 3234835549.0
p75 = 3234874621.0
p95 = 3234932801.0
p99 = 3234955240.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Consider the following hypothetical situations: <br>In Lottery A, you have a 50% chance of success, with a payout of $100. <br>In Lottery B, you have a 90% chance of success, with a payout of $20. <br><br>Assuming you have $10 to bet, would you play Lottery A or Lottery B?"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 551

[columns.stats]
distinct_count = 3
null_rate = 0.007259528130671506
min_length = 8
max_length = 9
avg_length = 8.9981718464351

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "Do you ever smoke cigarettes?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 551

[columns.nullable]
probability = 0.023593466424682397

[columns.stats]
distinct_count = 3
null_rate = 0.023593466424682397
min_length = 2
max_length = 8
avg_length = 2.16728624535316

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Do you ever drink alcohol?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 551

[columns.nullable]
probability = 0.016333938294010888

[columns.stats]
distinct_count = 3
null_rate = 0.016333938294010888
min_length = 2
max_length = 8
avg_length = 2.7785977859778597

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Do you ever gamble?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 551

[columns.nullable]
probability = 0.023593466424682397

[columns.stats]
distinct_count = 3
null_rate = 0.023593466424682397
min_length = 2
max_length = 8
avg_length = 2.4888475836431225

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Have you ever been skydiving?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 5
row_count = 551

[columns.nullable]
probability = 0.021778584392014518

[columns.stats]
distinct_count = 3
null_rate = 0.021778584392014518
min_length = 2
max_length = 8
avg_length = 2.0779220779220777

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Do you ever drive above the speed limit?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 6
row_count = 551

[columns.nullable]
probability = 0.019963702359346643

[columns.stats]
distinct_count = 3
null_rate = 0.019963702359346643
min_length = 2
max_length = 8
avg_length = 2.9

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Have you ever cheated on your significant other?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 7
row_count = 551

[columns.nullable]
probability = 0.019963702359346643

[columns.stats]
distinct_count = 3
null_rate = 0.019963702359346643
min_length = 2
max_length = 8
avg_length = 2.1814814814814816

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "Do you eat steak?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 8
row_count = 551

[columns.nullable]
probability = 0.019963702359346643

[columns.stats]
distinct_count = 3
null_rate = 0.019963702359346643
min_length = 2
max_length = 8
avg_length = 2.8074074074074074

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "How do you like your steak prepared?"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 9
row_count = 551

[columns.nullable]
probability = 0.21415607985480944

[columns.stats]
distinct_count = 6
null_rate = 0.21415607985480944
min_length = 4
max_length = 11
avg_length = 8.51501154734411

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Gender"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 10
row_count = 551

[columns.nullable]
probability = 0.06533575317604355

[columns.stats]
distinct_count = 3
null_rate = 0.06533575317604355
min_length = 4
max_length = 8
avg_length = 5.048543689320389

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "Age"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 11
row_count = 551

[columns.nullable]
probability = 0.06533575317604355

[columns.stats]
distinct_count = 5
null_rate = 0.06533575317604355
min_length = 4
max_length = 8
avg_length = 4.751456310679612

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "Household Income"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 12
row_count = 551

[columns.nullable]
probability = 0.2177858439201452

[columns.stats]
distinct_count = 6
null_rate = 0.2177858439201452
min_length = 8
max_length = 19
avg_length = 15.737819025522041

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Education"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 13
row_count = 551

[columns.nullable]
probability = 0.06896551724137931

[columns.stats]
distinct_count = 6
null_rate = 0.06896551724137931
min_length = 8
max_length = 32
avg_length = 20.69980506822612

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "Location (Census Region)"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 14
row_count = 551

[columns.nullable]
probability = 0.06896551724137931

[columns.stats]
distinct_count = 10
null_rate = 0.06896551724137931
min_length = 7
max_length = 18
avg_length = 13.610136452241715

[columns.traits]
semantic = "categorical"
pii = true
cardinality = "medium"

[[constraints]]
type = "range"
field = "RespondentID"
min = 3234760413.0
max = 3237565956.0
