[[correlations]]
entity = "original"
fields = [
    "open",
    "high",
]
matrix = [
    [
    1.0,
    0.9583367234604852,
],
    [
    0.9583367234604852,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "high",
]
matrix = [
    [
    1.0,
    0.9426980546941077,
],
    [
    0.9426980546941077,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "low",
]
matrix = [
    [
    1.0,
    0.9204107757536202,
],
    [
    0.9204107757536202,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "low",
]
matrix = [
    [
    1.0,
    0.9064768505139857,
],
    [
    0.9064768505139857,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "close",
]
matrix = [
    [
    1.0,
    0.9070870047552881,
],
    [
    0.9070870047552881,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "close",
]
matrix = [
    [
    1.0,
    0.8932271500088832,
],
    [
    0.8932271500088832,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "ret",
]
matrix = [
    [
    1.0,
    0.3091005232166081,
],
    [
    0.3091005232166081,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "open",
    "ret",
]
matrix = [
    [
    1.0,
    0.32332417081800846,
],
    [
    0.32332417081800846,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "low",
]
matrix = [
    [
    1.0,
    0.9440138001427467,
],
    [
    0.9440138001427467,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "low",
]
matrix = [
    [
    1.0,
    0.9501726713286857,
],
    [
    0.9501726713286857,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "close",
]
matrix = [
    [
    1.0,
    0.9647505372481843,
],
    [
    0.9647505372481843,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "close",
]
matrix = [
    [
    1.0,
    0.9706110391291098,
],
    [
    0.9706110391291098,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "ret",
]
matrix = [
    [
    1.0,
    0.33736181373668106,
],
    [
    0.33736181373668106,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high",
    "ret",
]
matrix = [
    [
    1.0,
    0.37971382345685883,
],
    [
    0.37971382345685883,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "low",
    "close",
]
matrix = [
    [
    1.0,
    0.9556351279567491,
],
    [
    0.9556351279567491,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "low",
    "close",
]
matrix = [
    [
    1.0,
    0.9551797040169133,
],
    [
    0.9551797040169133,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "low",
    "ret",
]
matrix = [
    [
    1.0,
    0.3025023258180229,
],
    [
    0.3025023258180229,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "low",
    "ret",
]
matrix = [
    [
    1.0,
    0.32224415318754496,
],
    [
    0.32224415318754496,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "ret",
]
matrix = [
    [
    1.0,
    0.30431945228839796,
],
    [
    0.30431945228839796,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "close",
    "ret",
]
matrix = [
    [
    1.0,
    0.321962224794555,
],
    [
    0.321962224794555,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "date",
    "signal",
]
matrix = [
    [
    1.0,
    0.9999999999999993,
],
    [
    0.9999999999999993,
    1.0,
],
]
conditional = []
