[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "signal"
given = "region"

[[correlations.distributions]]
when = "frontal"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0012980820495732412
std_dev = 0.07589557641011767

[[correlations.distributions]]
when = "parietal"
distribution = "normal"

[correlations.distributions.params]
mean = 0.005781455078620778
std_dev = 0.10889815919760026

[correlations.default]
kind = "normal"

[correlations.default.params]
mean = 0.003539768564097037
std_dev = 0.09388556308642108

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "signal"
given = "subject"

[[correlations.distributions]]
when = "s13"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0038528560263129527
std_dev = 0.08226266064757763

[[correlations.distributions]]
when = "s5"
distribution = "normal"

[correlations.distributions.params]
mean = -0.0008399721673513297
std_dev = 0.08036187198099137

[[correlations.distributions]]
when = "s0"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0038265112370995443
std_dev = 0.05371385352271105

[[correlations.distributions]]
when = "s9"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0012104478827251618
std_dev = 0.09331541074853875

[[correlations.distributions]]
when = "s11"
distribution = "normal"

[correlations.distributions.params]
mean = -0.002674324098949473
std_dev = 0.08600127587146658

[[correlations.distributions]]
when = "s4"
distribution = "normal"

[correlations.distributions.params]
mean = 0.011625102880747494
std_dev = 0.14564671704983914

[[correlations.distributions]]
when = "s10"
distribution = "normal"

[correlations.distributions.params]
mean = 0.006743812664380666
std_dev = 0.06787945505117615

[[correlations.distributions]]
when = "s12"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0010298152055710865
std_dev = 0.06618888517117483

[[correlations.distributions]]
when = "s3"
distribution = "normal"

[correlations.distributions.params]
mean = 0.00774878701755072
std_dev = 0.11446749006235228

[[correlations.distributions]]
when = "s2"
distribution = "normal"

[correlations.distributions.params]
mean = -0.0019263684793798643
std_dev = 0.06327846498431478

[[correlations.distributions]]
when = "s7"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0047107039987517
std_dev = 0.06402293224709484

[[correlations.distributions]]
when = "s1"
distribution = "normal"

[correlations.distributions.params]
mean = 0.00997791768637974
std_dev = 0.15726804986287682

[[correlations.distributions]]
when = "s6"
distribution = "normal"

[correlations.distributions.params]
mean = 0.0019222005998399741
std_dev = 0.08900051961429095

[[correlations.distributions]]
when = "s8"
distribution = "normal"

[correlations.distributions.params]
mean = 0.002349269443679107
std_dev = 0.08298832558667585

[correlations.default]
kind = "normal"

[correlations.default.params]
mean = 0.003539768564097037
std_dev = 0.09388556308642108

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "signal"
given = "event"

[[correlations.distributions]]
when = "stim"
distribution = "normal"

[correlations.distributions.params]
mean = 0.013748411381632497
std_dev = 0.12306352356752204

[[correlations.distributions]]
when = "cue"
distribution = "normal"

[correlations.distributions.params]
mean = -0.006668874253438554
std_dev = 0.04770675322113843

[correlations.default]
kind = "normal"

[correlations.default.params]
mean = 0.003539768564097037
std_dev = 0.09388556308642108
