[[constraints]]
table = "original"
type = "range"
field = "timepoint"
min = 0.0
max = 18.0

[[constraints]]
table = "original"
type = "range"
field = "signal"
min = -0.25548585958000003
max = 0.564984721448
