[[constraints]]
table = "original"
type = "range"
field = "Number of drivers involved in fatal collisions per billion miles"
min = 5.9
max = 23.9

[[constraints]]
table = "original"
type = "range"
field = "Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding"
min = 13.0
max = 54.0

[[constraints]]
table = "original"
type = "range"
field = "Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired"
min = 16.0
max = 44.0

[[constraints]]
table = "original"
type = "range"
field = "Percentage Of Drivers Involved In Fatal Collisions Who Were Not Distracted"
min = 10.0
max = 100.0

[[constraints]]
table = "original"
type = "range"
field = "Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents"
min = 76.0
max = 100.0

[[constraints]]
table = "original"
type = "range"
field = "Car Insurance Premiums ($)"
min = 641.96
max = 1301.52

[[constraints]]
table = "original"
type = "range"
field = "Losses incurred by insurance companies for collisions per insured driver ($)"
min = 82.75
max = 194.78

[[constraints]]
table = "original"
type = "check"
expr = "Number of drivers involved in fatal collisions per billion miles <= Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired"

[[constraints]]
table = "original"
type = "check"
expr = "Number of drivers involved in fatal collisions per billion miles <= Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents"

[[constraints]]
table = "original"
type = "check"
expr = "Number of drivers involved in fatal collisions per billion miles <= Car Insurance Premiums ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Number of drivers involved in fatal collisions per billion miles <= Losses incurred by insurance companies for collisions per insured driver ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding <= Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding <= Car Insurance Premiums ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding <= Losses incurred by insurance companies for collisions per insured driver ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired <= Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired <= Car Insurance Premiums ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired <= Losses incurred by insurance companies for collisions per insured driver ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Were Not Distracted <= Car Insurance Premiums ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Percentage Of Drivers Involved In Fatal Collisions Who Had Not Been Involved In Any Previous Accidents <= Car Insurance Premiums ($)"

[[constraints]]
table = "original"
type = "check"
expr = "Losses incurred by insurance companies for collisions per insured driver ($) <= Car Insurance Premiums ($)"
