[table]
name = "original"
count = 2251

[table.stats]
source_rows = 2251

[[table.scaling.custom]]
name = "answerKey"
field = "answerKey"
cardinality = 9

[[columns]]
name = "id"
data_type = "string"
nullable = false
primary_key = true

[columns.generator]
type = "dictionary"
file = "original_id.dict.txt"
expansion = "shuffle"

[columns.stats]
distinct_count = 2251
null_rate = 0.0
min_length = 8
max_length = 22
avg_length = 15.864504664593515

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "question"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "id"
file = "original__id_question_answerKey.tsv"
column = 1

[columns.stats]
distinct_count = 2245
null_rate = 0.0
min_length = 17
max_length = 587
avg_length = 111.14215904042648

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "choices"
data_type = "string"
nullable = false

[columns.generator]
type = "sequence"
start = 1
step = 1

[columns.stats]
null_rate = 0.0

[columns.traits]

[[columns]]
name = "answerKey"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "id"
file = "original__id_question_answerKey.tsv"
column = 2

[columns.stats]
distinct_count = 9
null_rate = 0.0
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "low"
