[table]
name = "original"
count = 1500

[table.stats]
source_rows = 1500

[table.sort_by]
column = "idx"
direction = "asc"

[[columns]]
name = "sentence1"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 1500

[columns.stats]
distinct_count = 1474
null_rate = 0.0
min_length = 12
max_length = 200
avg_length = 64.28933333333333

[columns.traits]
semantic = "text"
cardinality = "high"

[[columns]]
name = "sentence2"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 1500

[columns.stats]
distinct_count = 1467
null_rate = 0.0
min_length = 17
max_length = 186
avg_length = 63.75333333333333

[columns.traits]
semantic = "text"
cardinality = "high"

[[columns]]
name = "label"
data_type = "float"
nullable = false
precision = 15

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 1500

[columns.stats]
null_rate = 0.0
min = 0.0
max = 5.0
mean = 2.3639075540602206
std = 1.5004856453975999

[columns.stats.percentiles]
p25 = 1.0
p50 = 2.5999999046325684
p75 = 3.5999999046325684
p95 = 4.800000190734863
p99 = 5.0

[columns.traits]
semantic = "float"
distribution_shape = "normal"

[[columns]]
name = "idx"
data_type = "int32"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 1500

[columns.stats]
distinct_count = 1500
null_rate = 0.0
min = 0.0
max = 1499.0
mean = 749.5
std = 433.15701541127095

[columns.stats.percentiles]
p25 = 375.0
p50 = 750.0
p75 = 1124.0
p95 = 1424.0
p99 = 1484.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[constraints]]
type = "range"
field = "label"
min = 0.0
max = 5.0

[[constraints]]
type = "range"
field = "idx"
min = 0.0
max = 1499.0
