[[correlations]]
entity = "original"
fields = [
    "hospitals",
    "high_risk_per_hospital",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "hospitals",
    "high_risk_per_ICU_bed",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "hospitals",
    "MMSA",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "hospitals",
    "total_percent_at_risk",
]
matrix = [
    [
    1.0,
    0.9775222276499774,
],
    [
    0.9775222276499774,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "hospitals",
    "icu_beds",
]
matrix = [
    [
    1.0,
    0.9797840119009785,
],
    [
    0.9797840119009785,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_hospital",
    "high_risk_per_ICU_bed",
]
matrix = [
    [
    1.0,
    0.9999999999999502,
],
    [
    0.9999999999999502,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_hospital",
    "MMSA",
]
matrix = [
    [
    1.0,
    0.9999999999999536,
],
    [
    0.9999999999999536,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_hospital",
    "total_percent_at_risk",
]
matrix = [
    [
    1.0,
    0.9999999999999845,
],
    [
    0.9999999999999845,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_hospital",
    "icu_beds",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_ICU_bed",
    "MMSA",
]
matrix = [
    [
    1.0,
    0.9999999999999498,
],
    [
    0.9999999999999498,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_ICU_bed",
    "total_percent_at_risk",
]
matrix = [
    [
    1.0,
    0.9999999999999845,
],
    [
    0.9999999999999845,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "high_risk_per_ICU_bed",
    "icu_beds",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MMSA",
    "total_percent_at_risk",
]
matrix = [
    [
    1.0,
    0.999999999999992,
],
    [
    0.999999999999992,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "MMSA",
    "icu_beds",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total_percent_at_risk",
    "icu_beds",
]
matrix = [
    [
    1.0,
    0.9796312670361972,
],
    [
    0.9796312670361972,
    1.0,
],
]
conditional = []
