[[constraints]]
table = "original"
type = "range"
field = "year"
min = 2000.0
max = 2014.0

[[constraints]]
table = "original"
type = "range"
field = "month"
min = 1.0
max = 12.0

[[constraints]]
table = "original"
type = "range"
field = "date_of_month"
min = 1.0
max = 31.0

[[constraints]]
table = "original"
type = "range"
field = "day_of_week"
min = 1.0
max = 7.0

[[constraints]]
table = "original"
type = "range"
field = "births"
min = 5728.0
max = 16081.0

[[constraints]]
table = "original"
type = "check"
expr = "month <= year"

[[constraints]]
table = "original"
type = "check"
expr = "date_of_month <= year"

[[constraints]]
table = "original"
type = "check"
expr = "day_of_week <= year"

[[constraints]]
table = "original"
type = "check"
expr = "year <= births"

[[constraints]]
table = "original"
type = "check"
expr = "month <= births"

[[constraints]]
table = "original"
type = "check"
expr = "date_of_month <= births"

[[constraints]]
table = "original"
type = "check"
expr = "day_of_week <= births"
