[[correlations]]
entity = "original"
fields = [
    "Unemployment_rate",
    "P25th",
]
matrix = [
    [
    1.0,
    -0.3413964209005848,
],
    [
    -0.3413964209005848,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployment_rate",
    "P25th",
]
matrix = [
    [
    1.0,
    -0.3333367574307155,
],
    [
    -0.3333367574307155,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployment_rate",
    "Median",
]
matrix = [
    [
    1.0,
    -0.3019456595817109,
],
    [
    -0.3019456595817109,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Employed",
]
matrix = [
    [
    1.0,
    0.9697855987417962,
],
    [
    0.9697855987417962,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Employed",
]
matrix = [
    [
    1.0,
    0.9750221051015733,
],
    [
    0.9750221051015733,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Employed_full_time_year_round",
]
matrix = [
    [
    1.0,
    0.9691764697984575,
],
    [
    0.9691764697984575,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Employed_full_time_year_round",
]
matrix = [
    [
    1.0,
    0.968599747602696,
],
    [
    0.968599747602696,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Total",
]
matrix = [
    [
    1.0,
    0.9622314512620106,
],
    [
    0.9622314512620106,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Unemployed",
    "Total",
]
matrix = [
    [
    1.0,
    0.9738076282594904,
],
    [
    0.9738076282594904,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed",
    "Employed_full_time_year_round",
]
matrix = [
    [
    1.0,
    0.9958098304717039,
],
    [
    0.9958098304717039,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed",
    "Employed_full_time_year_round",
]
matrix = [
    [
    1.0,
    0.9960645433433304,
],
    [
    0.9960645433433304,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed",
    "Total",
]
matrix = [
    [
    1.0,
    0.994976334635262,
],
    [
    0.994976334635262,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed",
    "Total",
]
matrix = [
    [
    1.0,
    0.997035660150836,
],
    [
    0.997035660150836,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P25th",
    "P75th",
]
matrix = [
    [
    1.0,
    0.8670659828333235,
],
    [
    0.8670659828333235,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P25th",
    "P75th",
]
matrix = [
    [
    1.0,
    0.8890817463415998,
],
    [
    0.8890817463415998,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P25th",
    "Median",
]
matrix = [
    [
    1.0,
    0.9500138118223612,
],
    [
    0.9500138118223612,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P25th",
    "Median",
]
matrix = [
    [
    1.0,
    0.9460124066880333,
],
    [
    0.9460124066880333,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P75th",
    "Median",
]
matrix = [
    [
    1.0,
    0.9500985538977625,
],
    [
    0.9500985538977625,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "P75th",
    "Median",
]
matrix = [
    [
    1.0,
    0.9644800671038546,
],
    [
    0.9644800671038546,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed_full_time_year_round",
    "Total",
]
matrix = [
    [
    1.0,
    0.9846759668157083,
],
    [
    0.9846759668157083,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Employed_full_time_year_round",
    "Total",
]
matrix = [
    [
    1.0,
    0.9912020062021685,
],
    [
    0.9912020062021685,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Major",
    "Major_category",
]
matrix = [
    [
    1.0,
    0.9999999999999991,
],
    [
    0.9999999999999991,
    1.0,
],
]
conditional = []
