[[constraints]]
table = "original"
type = "range"
field = "chocolate"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "fruity"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "caramel"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "peanutyalmondy"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "nougat"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "crispedricewafer"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "hard"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "bar"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "pluribus"
min = 0.0
max = 1.0

[[constraints]]
table = "original"
type = "range"
field = "sugarpercent"
min = 0.011
max = 0.98799998

[[constraints]]
table = "original"
type = "range"
field = "pricepercent"
min = 0.011
max = 0.97600001

[[constraints]]
table = "original"
type = "range"
field = "winpercent"
min = 22.445341
max = 84.18029

[[constraints]]
table = "original"
type = "check"
expr = "crispedricewafer <= chocolate"

[[constraints]]
table = "original"
type = "check"
expr = "chocolate <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "fruity <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "caramel <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "peanutyalmondy <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "nougat <= bar"

[[constraints]]
table = "original"
type = "check"
expr = "nougat <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "crispedricewafer <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "hard <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "bar <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "pluribus <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "sugarpercent <= winpercent"

[[constraints]]
table = "original"
type = "check"
expr = "pricepercent <= winpercent"
