[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "time"
given = "align"

[[correlations.distributions]]
when = "dots"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 720.0
min = -80.0

[[correlations.distributions]]
when = "sacc"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 300.0
min = -600.0

[correlations.default]
kind = "normal"

[correlations.default.params]
mean = 74.15094339622641
std_dev = 284.42881499770203
