[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "Deaths"
given = "Entity"

[[correlations.distributions]]
when = "Drought"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 8.0
shape = 0.1712506155691955

[[correlations.distributions]]
when = "Extreme temperature"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 6.392809233325655
sigma = 1.458005669756427

[[correlations.distributions]]
when = "Earthquake"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 8.256485338094892
sigma = 2.142984033323911

[[correlations.distributions]]
when = "Mass movement (dry)"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 4.119951952537789
sigma = 1.269271418282932

[[correlations.distributions]]
when = "Volcanic activity"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 4.8347173863081645
sigma = 2.473325557650647

[[correlations.distributions]]
when = "All natural disasters"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 10.700073303032609
sigma = 1.8760450897878382

[[correlations.distributions]]
when = "Epidemic"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 8.433029060448114
sigma = 2.4292223738491034

[[correlations.distributions]]
when = "Wildfire"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 3.579673811365238
sigma = 1.3984903308226742

[[correlations.distributions]]
when = "Flood"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 8.151045929728824
sigma = 1.9468941050694943

[[correlations.distributions]]
when = "Landslide"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 5.910015328674287
sigma = 1.2625091580612948

[[correlations.distributions]]
when = "Extreme weather"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.9812955696877275
sigma = 1.6925882769451233

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 7.532823815223376
sigma = 2.83427267154807
