[table]
name = "original"
count = 123

[table.stats]
source_rows = 123

[[columns]]
name = "date"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 123

[columns.stats]
distinct_count = 123
null_rate = 0.0
min_length = 10
max_length = 10
avg_length = 10.0

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "price"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 123

[columns.stats]
distinct_count = 122
null_rate = 0.0
min = 735.09
max = 1549.38
mean = 1184.4334959349592
std = 195.40774336547273

[columns.stats.percentiles]
p25 = 1058.2
p50 = 1180.59
p75 = 1330.63
p95 = 1482.37
p99 = 1530.62

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "normal"

[[constraints]]
type = "range"
field = "price"
min = 735.09
max = 1549.38
