[[constraints]]
table = "original"
type = "range"
field = "number"
min = 1.0
max = 7.0

[[constraints]]
table = "original"
type = "range"
field = "orbital_period"
min = 0.09070629
max = 730000.0

[[constraints]]
table = "original"
type = "range"
field = "mass"
min = 0.0036
max = 25.0

[[constraints]]
table = "original"
type = "range"
field = "distance"
min = 1.35
max = 8500.0

[[constraints]]
table = "original"
type = "range"
field = "year"
min = 1989.0
max = 2014.0

[[constraints]]
table = "original"
type = "check"
expr = "number <= year"

[[constraints]]
table = "original"
type = "check"
expr = "mass <= year"
