[[correlations]]
entity = "original"
fields = [
    "Car Insurance Premiums ($)",
    "Losses incurred by insurance companies for collisions per insured driver ($)",
]
matrix = [
    [
    1.0,
    0.623116438519707,
],
    [
    0.623116438519707,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Car Insurance Premiums ($)",
    "Losses incurred by insurance companies for collisions per insured driver ($)",
]
matrix = [
    [
    1.0,
    0.6466968325791855,
],
    [
    0.6466968325791855,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Percentage Of Drivers Involved In Fatal Collisions Who Were Speeding",
    "Percentage Of Drivers Involved In Fatal Collisions Who Were Alcohol-Impaired",
]
matrix = [
    [
    1.0,
    0.3676719596921529,
],
    [
    0.3676719596921529,
    1.0,
],
]
conditional = []
