[table]
name = "original"
count = 12360

[table.stats]
source_rows = 12360

[[table.scaling.custom]]
name = "item_id"
field = "item_id"
cardinality = 4

[[table.scaling.custom]]
name = "common_name"
field = "common_name"
cardinality = 4

[[table.scaling.custom]]
name = "scientific_name"
field = "scientific_name"
cardinality = 4

[[table.scaling.custom]]
name = "gap_species_code"
field = "gap_species_code"
cardinality = 4

[table.sort_by]
column = "item_id"
direction = "asc"

[[columns]]
name = "item_id"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "common_name"
file = "original__common_name_scientific_name_gap_species_code_item_id.tsv"
column = 3

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 24
max_length = 24
avg_length = 24.0

[columns.traits]
semantic = "hex_string"
cardinality = "low"

[[columns]]
name = "common_name"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_common_name.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 14
max_length = 18
avg_length = 16.5

[columns.traits]
semantic = "categorical"
pii = true
cardinality = "low"

[[columns]]
name = "scientific_name"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "common_name"
file = "original__common_name_scientific_name_gap_species_code_item_id.tsv"
column = 1

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 18
max_length = 23
avg_length = 20.5

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "gap_species_code"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "common_name"
file = "original__common_name_scientific_name_gap_species_code_item_id.tsv"
column = 2

[columns.stats]
distinct_count = 4
null_rate = 0.0
min_length = 6
max_length = 6
avg_length = 6.0

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "county_id"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "uniform"
round = true

[columns.generator.params]
max = 56045.0
min = 1001.0

[columns.stats]
distinct_count = 3090
null_rate = 0.0
min = 1001.0
max = 56045.0
mean = 30500.32071197411
std = 14914.234222435924

[columns.stats.percentiles]
p25 = 19031.0
p50 = 29185.0
p75 = 45057.0
p95 = 53071.0
p99 = 55125.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "habitat_yearround_pct"
data_type = "float"
nullable = false
precision = 4

[columns.generator]
type = "distribution"
kind = "uniform"

[columns.generator.params]
max = 0.9996
min = 0.0

[columns.stats]
distinct_count = 6103
null_rate = 0.0
min = 0.0
max = 0.9996
mean = 0.5028371035598693
std = 0.36021626349164515

[columns.stats.percentiles]
p25 = 0.1775
p50 = 0.4549
p75 = 0.8757
p95 = 0.9892
p99 = 0.9961

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[constraints]]
type = "range"
field = "county_id"
min = 1001.0
max = 56045.0

[[constraints]]
type = "range"
field = "habitat_yearround_pct"
min = 0.0
max = 0.9996

[[constraints]]
type = "check"
expr = "habitat_yearround_pct <= county_id"
