[table]
name = "original"
count = 891

[table.stats]
source_rows = 891

[[table.scaling.custom]]
name = "survived"
field = "survived"
cardinality = 2

[[table.scaling.custom]]
name = "pclass"
field = "pclass"
cardinality = 3

[[table.scaling.custom]]
name = "sibsp"
field = "sibsp"
cardinality = 7

[[table.scaling.custom]]
name = "parch"
field = "parch"
cardinality = 7

[[table.scaling.custom]]
name = "adult_male"
field = "adult_male"
cardinality = 2

[[table.scaling.custom]]
name = "alone"
field = "alone"
cardinality = 2

[[columns]]
name = "survived"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 784

[columns.stats]
distinct_count = 2
null_rate = 0.0
min = 0.0
max = 1.0
mean = 0.3838383838383838
std = 0.4865924542648542

[columns.stats.percentiles]
p25 = 0.0
p50 = 0.0
p75 = 1.0
p95 = 1.0
p99 = 1.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "pclass"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 784

[columns.stats]
distinct_count = 3
null_rate = 0.0
min = 1.0
max = 3.0
mean = 2.308641975308642
std = 0.8360712409770494

[columns.stats.percentiles]
p25 = 2.0
p50 = 3.0
p75 = 3.0
p95 = 3.0
p99 = 3.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "skewed"

[[columns]]
name = "sex"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 784

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 4
max_length = 6
avg_length = 4.704826038159371

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "age"
data_type = "float"
precision = 0

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 784

[columns.nullable]
probability = 0.19865319865319866

[columns.stats]
distinct_count = 88
null_rate = 0.19865319865319866
min = 0.42
max = 80.0
mean = 29.69911764705882
std = 14.526497332334037

[columns.stats.percentiles]
p25 = 20.0
p50 = 28.0
p75 = 38.0
p95 = 56.0
p99 = 66.0

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "sibsp"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 784

[columns.stats]
distinct_count = 7
null_rate = 0.0
min = 0.0
max = 8.0
mean = 0.5230078563411896
std = 1.1027434322934322

[columns.stats.percentiles]
p25 = 0.0
p50 = 0.0
p75 = 1.0
p95 = 3.0
p99 = 5.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "long_tail"

[[columns]]
name = "parch"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 5
row_count = 784

[columns.stats]
distinct_count = 7
null_rate = 0.0
min = 0.0
max = 6.0
mean = 0.38159371492704824
std = 0.8060572211299486

[columns.stats.percentiles]
p25 = 0.0
p50 = 0.0
p75 = 0.0
p95 = 2.0
p99 = 4.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "long_tail"

[[columns]]
name = "fare"
data_type = "float"
nullable = false
precision = 4

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 6
row_count = 784

[columns.stats]
distinct_count = 248
null_rate = 0.0
min = 0.0
max = 512.3292
mean = 32.20420796857465
std = 49.69342859718088

[columns.stats.percentiles]
p25 = 7.925
p50 = 14.4542
p75 = 31.0
p95 = 113.275
p99 = 247.5208

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "embarked"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 7
row_count = 784

[columns.stats]
distinct_count = 3
null_rate = 0.002244668911335578
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "class"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 8
row_count = 784

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 5
max_length = 6
avg_length = 5.206509539842873

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "who"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 9
row_count = 784

[columns.stats]
distinct_count = 3
null_rate = 0.0
min_length = 3
max_length = 5
avg_length = 3.7946127946127945

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "adult_male"
data_type = "bool"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 10
row_count = 784

[columns.stats]
null_rate = 0.0

[columns.traits]
semantic = "boolean"

[[columns]]
name = "deck"
data_type = "string"

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 11
row_count = 784

[columns.nullable]
probability = 0.7721661054994389

[columns.stats]
distinct_count = 7
null_rate = 0.7721661054994389
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "embark_town"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 12
row_count = 784

[columns.stats]
distinct_count = 3
null_rate = 0.002244668911335578
min_length = 9
max_length = 11
avg_length = 10.535433070866143

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "alive"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 13
row_count = 784

[columns.stats]
distinct_count = 2
null_rate = 0.0
min_length = 2
max_length = 3
avg_length = 2.3838383838383836

[columns.traits]
semantic = "boolean"
cardinality = "low"

[[columns]]
name = "alone"
data_type = "bool"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 14
row_count = 784

[columns.stats]
null_rate = 0.0

[columns.traits]
semantic = "boolean"

[[constraints]]
type = "range"
field = "survived"
min = 0.0
max = 1.0

[[constraints]]
type = "range"
field = "pclass"
min = 1.0
max = 3.0

[[constraints]]
type = "range"
field = "age"
min = 0.42
max = 80.0

[[constraints]]
type = "range"
field = "sibsp"
min = 0.0
max = 8.0

[[constraints]]
type = "range"
field = "parch"
min = 0.0
max = 6.0

[[constraints]]
type = "range"
field = "fare"
min = 0.0
max = 512.3292

[[constraints]]
type = "check"
expr = "survived <= pclass"

[[constraints]]
type = "check"
expr = "sibsp <= fare"

[[constraints]]
type = "check"
expr = "parch <= fare"
