[[correlations]]
entity = "original"
fields = [
    "Y",
    "X",
]
matrix = [
    [
    1.0,
    0.8163076213667063,
],
    [
    0.8163076213667063,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "Y",
    "X",
]
matrix = [
    [
    1.0,
    0.8168854813001848,
],
    [
    0.8168854813001848,
    1.0,
],
]
conditional = []
