[[correlations]]
entity = "original"
fields = [
    "fare",
    "survived",
]
matrix = [
    [
    1.0,
    0.3237361394448083,
],
    [
    0.3237361394448083,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "parch",
]
matrix = [
    [
    1.0,
    0.4100738082761382,
],
    [
    0.4100738082761382,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.5494996199439061,
],
    [
    -0.5494996199439061,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.6880316726256096,
],
    [
    -0.6880316726256096,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "sibsp",
]
matrix = [
    [
    1.0,
    0.4471129882944581,
],
    [
    0.4471129882944581,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "survived",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.33848103596101586,
],
    [
    -0.33848103596101586,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "survived",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.3396679366500525,
],
    [
    -0.3396679366500525,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "parch",
    "sibsp",
]
matrix = [
    [
    1.0,
    0.41483769862015263,
],
    [
    0.41483769862015263,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "parch",
    "sibsp",
]
matrix = [
    [
    1.0,
    0.45001397100861634,
],
    [
    0.45001397100861634,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "age",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.36922601531551574,
],
    [
    -0.36922601531551574,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "age",
    "pclass",
]
matrix = [
    [
    1.0,
    -0.36166557503434504,
],
    [
    -0.36166557503434504,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "age",
    "sibsp",
]
matrix = [
    [
    1.0,
    -0.3082467589236574,
],
    [
    -0.3082467589236574,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "embark_town",
    "embarked",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "deck",
    "class",
]
matrix = [
    [
    1.0,
    0.6461176369278667,
],
    [
    0.6461176369278667,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "deck",
    "who",
]
matrix = [
    [
    1.0,
    0.32135468589345884,
],
    [
    0.32135468589345884,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sex",
    "alive",
]
matrix = [
    [
    1.0,
    0.5433513806577551,
],
    [
    0.5433513806577551,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sex",
    "who",
]
matrix = [
    [
    1.0,
    0.9476753874512575,
],
    [
    0.9476753874512575,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alive",
    "class",
]
matrix = [
    [
    1.0,
    0.33981738800531175,
],
    [
    0.33981738800531175,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "alive",
    "who",
]
matrix = [
    [
    1.0,
    0.5644967866491237,
],
    [
    0.5644967866491237,
    1.0,
],
]
conditional = []
