[[correlations]]
entity = "original"
fields = [
    "total",
    "fare",
]
matrix = [
    [
    1.0,
    0.9743576409796048,
],
    [
    0.9743576409796048,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "fare",
]
matrix = [
    [
    1.0,
    0.9472634288945934,
],
    [
    0.9472634288945934,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "distance",
]
matrix = [
    [
    1.0,
    0.9046764192201221,
],
    [
    0.9046764192201221,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "distance",
]
matrix = [
    [
    1.0,
    0.8740970113832398,
],
    [
    0.8740970113832398,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "tip",
]
matrix = [
    [
    1.0,
    0.6461857919756545,
],
    [
    0.6461857919756545,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "tip",
]
matrix = [
    [
    1.0,
    0.4992895514701028,
],
    [
    0.4992895514701028,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "tolls",
]
matrix = [
    [
    1.0,
    0.6831422196528585,
],
    [
    0.6831422196528585,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total",
    "tolls",
]
matrix = [
    [
    1.0,
    0.3800266644020578,
],
    [
    0.3800266644020578,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "distance",
]
matrix = [
    [
    1.0,
    0.920107702789572,
],
    [
    0.920107702789572,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "distance",
]
matrix = [
    [
    1.0,
    0.9257442230436977,
],
    [
    0.9257442230436977,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "tip",
]
matrix = [
    [
    1.0,
    0.4886124004721888,
],
    [
    0.4886124004721888,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "tip",
]
matrix = [
    [
    1.0,
    0.30804802505745693,
],
    [
    0.30804802505745693,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "tolls",
]
matrix = [
    [
    1.0,
    0.6093069206562153,
],
    [
    0.6093069206562153,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fare",
    "tolls",
]
matrix = [
    [
    1.0,
    0.37039231443938686,
],
    [
    0.37039231443938686,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "distance",
    "tip",
]
matrix = [
    [
    1.0,
    0.45258865650839597,
],
    [
    0.45258865650839597,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "distance",
    "tolls",
]
matrix = [
    [
    1.0,
    0.635267382016065,
],
    [
    0.635267382016065,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "distance",
    "tolls",
]
matrix = [
    [
    1.0,
    0.3648309744736399,
],
    [
    0.3648309744736399,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "tip",
    "tolls",
]
matrix = [
    [
    1.0,
    0.4136187978510578,
],
    [
    0.4136187978510578,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_zone",
    "pickup_borough",
]
matrix = [
    [
    1.0,
    0.9999999999999998,
],
    [
    0.9999999999999998,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_zone",
    "dropoff_zone",
]
matrix = [
    [
    1.0,
    0.36979278183231135,
],
    [
    0.36979278183231135,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_zone",
    "dropoff_borough",
]
matrix = [
    [
    1.0,
    0.5800664111642717,
],
    [
    0.5800664111642717,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_zone",
    "color",
]
matrix = [
    [
    1.0,
    0.8744779724410715,
],
    [
    0.8744779724410715,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_borough",
    "dropoff_zone",
]
matrix = [
    [
    1.0,
    0.6498236202649681,
],
    [
    0.6498236202649681,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_borough",
    "dropoff_borough",
]
matrix = [
    [
    1.0,
    0.582580571377596,
],
    [
    0.582580571377596,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pickup_borough",
    "color",
]
matrix = [
    [
    1.0,
    0.6201843090069403,
],
    [
    0.6201843090069403,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "dropoff_zone",
    "dropoff_borough",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "dropoff_zone",
    "color",
]
matrix = [
    [
    1.0,
    0.6603693046459347,
],
    [
    0.6603693046459347,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "dropoff_borough",
    "color",
]
matrix = [
    [
    1.0,
    0.5102154897612032,
],
    [
    0.5102154897612032,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tip"
given = "color"

[[correlations.distributions]]
when = "green"
distribution = "exponential"

[correlations.distributions.params]
lambda = 1.2571370048902877

[[correlations.distributions]]
when = "yellow"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.45610558957358255

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.5052496324314828

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tolls"
given = "dropoff_borough"

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.8650132465128164

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 4.149411959582573

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 1.2958758986000753

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 4.600809516234518

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 3.07434240709589

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "distance"
given = "dropoff_borough"

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.16779510422181143

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.15123415904976378

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.19886634276459939

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.41823054577238616

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.3306203924890125

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tip"
given = "dropoff_borough"

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.4190635244634135

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.5116120003773711

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 1.883938393839384

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.5245908505491974

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.5052496324314828

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "fare"
given = "dropoff_borough"

[[correlations.distributions]]
when = "Manhattan"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.2318462759426896
sigma = 0.5657066156162134

[[correlations.distributions]]
when = "Queens"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.688683201738415
sigma = 0.8528962429725918

[[correlations.distributions]]
when = "Brooklyn"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.7114417172786625
sigma = 0.7184449518082091

[[correlations.distributions]]
when = "Bronx"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.8670740151091545
sigma = 0.729749129212415

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 2.3280524384690895
sigma = 0.6515094051105617

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "total"
given = "dropoff_borough"

[[correlations.distributions]]
when = "Manhattan"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.6957986654497144
sigma = 0.465042610828208

[[correlations.distributions]]
when = "Brooklyn"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.9242106472299123
sigma = 0.6843342981077067

[[correlations.distributions]]
when = "Bronx"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.9834466224789007
sigma = 0.7036629213486013

[[correlations.distributions]]
when = "Queens"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.911681500803894
sigma = 0.8508220986751669

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 2.743171721577442
sigma = 0.5516432222975579

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tolls"
given = "payment"

[[correlations.distributions]]
when = "cash"
distribution = "exponential"

[correlations.distributions.params]
lambda = 5.33490357721184

[[correlations.distributions]]
when = "credit card"
distribution = "exponential"

[correlations.distributions.params]
lambda = 2.628480856366762

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 3.07434240709589

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "total"
given = "payment"

[[correlations.distributions]]
when = "cash"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.5152459374257226
sigma = 0.533465465033023

[[correlations.distributions]]
when = "credit card"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.836399176372226
sigma = 0.5292701686341874

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 2.743171721577442
sigma = 0.5516432222975579

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tolls"
given = "pickup_borough"

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 3.499634502923977

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 1.2850467289719627

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.5848525851018381

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 6.997316898228099

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 3.07434240709589

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "distance"
given = "pickup_borough"

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.1746462971456797

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.4255821055165726

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.24638622810346933

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.1339435887503695

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.3306203924890125

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "tip"
given = "pickup_borough"

[[correlations.distributions]]
when = "Brooklyn"
distribution = "exponential"

[correlations.distributions.params]
lambda = 1.0348274837210563

[[correlations.distributions]]
when = "Manhattan"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.5155834813629495

[[correlations.distributions]]
when = "Bronx"
distribution = "exponential"

[correlations.distributions.params]
lambda = 6.73011556764106

[[correlations.distributions]]
when = "Queens"
distribution = "exponential"

[correlations.distributions.params]
lambda = 0.32894078064606597

[correlations.default]
kind = "exponential"

[correlations.default.params]
lambda = 0.5052496324314828

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "fare"
given = "pickup_borough"

[[correlations.distributions]]
when = "Bronx"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.7929536874052077
sigma = 0.7399924732576679

[[correlations.distributions]]
when = "Brooklyn"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.5384691900637337
sigma = 0.7156078938595027

[[correlations.distributions]]
when = "Manhattan"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.2347772093184064
sigma = 0.5590580727299872

[[correlations.distributions]]
when = "Queens"
distribution = "gamma"

[correlations.distributions.params]
scale = 15.440568838164666
shape = 1.6148784785645416

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 2.3280524384690895
sigma = 0.6515094051105617

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "total"
given = "pickup_borough"

[[correlations.distributions]]
when = "Brooklyn"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.732151965159468
sigma = 0.6544535639796271

[[correlations.distributions]]
when = "Queens"
distribution = "gamma"

[correlations.distributions.params]
scale = 19.325634182930568
shape = 1.6382441189363377

[[correlations.distributions]]
when = "Bronx"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.8907230827840675
sigma = 0.6962490878766971

[[correlations.distributions]]
when = "Manhattan"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.6952275806757795
sigma = 0.45521536251093153

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 2.743171721577442
sigma = 0.5516432222975579
