[[constraints]]
table = "original"
type = "range"
field = "id"
min = 1.0
max = 72.0

[[constraints]]
table = "original"
type = "range"
field = "pct"
min = 0.006
max = 0.289

[[constraints]]
table = "original"
type = "range"
field = "total"
min = 222679.0
max = 12581722.0

[[constraints]]
table = "original"
type = "check"
expr = "pct <= id"

[[constraints]]
table = "original"
type = "check"
expr = "id <= total"

[[constraints]]
table = "original"
type = "check"
expr = "pct <= total"
