[[constraints]]
table = "original"
type = "range"
field = "Penicillin"
min = 0.001
max = 870.0

[[constraints]]
table = "original"
type = "range"
field = "Streptomycin"
min = 0.01
max = 14.0

[[constraints]]
table = "original"
type = "range"
field = "Neomycin"
min = 0.001
max = 40.0
