[table]
name = "original"
count = 53940

[table.stats]
source_rows = 53940

[[columns]]
name = "carat"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "log_normal"

[columns.generator.params]
mu = -0.3949669655482774
sigma = 0.5848220841250429

[columns.stats]
distinct_count = 273
null_rate = 0.0
min = 0.2
max = 5.01
mean = 0.7979397478679331
std = 0.474011244405377

[columns.stats.percentiles]
p25 = 0.4
p50 = 0.7
p75 = 1.04
p95 = 1.7
p99 = 2.18

[columns.traits]
semantic = "float"
cardinality = "low"
distribution_shape = "skewed"

[[columns]]
name = "cut"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "clarity"
file = "original__clarity_color_cut_depth_table.tsv"
column = 2

[columns.stats]
distinct_count = 5
null_rate = 0.0
min_length = 4
max_length = 9
avg_length = 6.286503522432332

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "color"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "clarity"
file = "original__clarity_color_cut_depth_table.tsv"
column = 1

[columns.stats]
distinct_count = 7
null_rate = 0.0
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "clarity"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_clarity.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 8
null_rate = 0.0
min_length = 2
max_length = 4
avg_length = 3.114757137560252

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "depth"
data_type = "float"
nullable = false
precision = 1

[columns.generator]
type = "tuple_lookup"
source_field = "clarity"
file = "original__clarity_color_cut_depth_table.tsv"
column = 3

[columns.stats]
distinct_count = 184
null_rate = 0.0
min = 43.0
max = 79.0
mean = 61.749404894322865
std = 1.432621318833703

[columns.stats.percentiles]
p25 = 61.0
p50 = 61.8
p75 = 62.5
p95 = 63.8
p99 = 65.6

[columns.traits]
semantic = "float"
cardinality = "low"
distribution_shape = "long_tail"

[[columns]]
name = "table"
data_type = "float"
nullable = false
precision = 0

[columns.generator]
type = "tuple_lookup"
source_field = "clarity"
file = "original__clarity_color_cut_depth_table.tsv"
column = 4

[columns.stats]
distinct_count = 127
null_rate = 0.0
min = 43.0
max = 95.0
mean = 57.45718390804598
std = 2.2344905628209704

[columns.stats.percentiles]
p25 = 56.0
p50 = 57.0
p75 = 59.0
p95 = 61.0
p99 = 64.0

[columns.traits]
semantic = "float"
cardinality = "low"
distribution_shape = "skewed"

[[columns]]
name = "price"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 7.786768479077399
sigma = 1.014639937514435

[columns.stats]
distinct_count = 11602
null_rate = 0.0
min = 326.0
max = 18823.0
mean = 3932.799721913237
std = 3989.4397381463814

[columns.stats.percentiles]
p25 = 950.0
p50 = 2401.0
p75 = 5324.0
p95 = 13107.0
p99 = 17379.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "skewed"

[[columns]]
name = "x"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 5.731157211716782
std_dev = 1.1217503485171458

[columns.stats]
distinct_count = 554
null_rate = 0.0
min = 0.0
max = 10.74
mean = 5.731157211716782
std = 1.1217607467925068

[columns.stats.percentiles]
p25 = 4.71
p50 = 5.7
p75 = 6.54
p95 = 7.66
p99 = 8.36

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "y"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 5.734525954764557
std_dev = 1.1421240869900506

[columns.stats]
distinct_count = 552
null_rate = 0.0
min = 0.0
max = 58.9
mean = 5.734525954764557
std = 1.1421346741236038

[columns.stats.percentiles]
p25 = 4.72
p50 = 5.71
p75 = 6.54
p95 = 7.65
p99 = 8.34

[columns.traits]
semantic = "float"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "z"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 3.538733778272153
std_dev = 0.705692305402726

[columns.stats]
distinct_count = 375
null_rate = 0.0
min = 0.0
max = 31.8
mean = 3.538733778272153
std = 0.7056988469499798

[columns.stats.percentiles]
p25 = 2.91
p50 = 3.53
p75 = 4.04
p95 = 4.73
p99 = 5.15

[columns.traits]
semantic = "float"
cardinality = "low"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "carat"
min = 0.2
max = 5.01

[[constraints]]
type = "range"
field = "depth"
min = 43.0
max = 79.0

[[constraints]]
type = "range"
field = "table"
min = 43.0
max = 95.0

[[constraints]]
type = "range"
field = "price"
min = 326.0
max = 18823.0

[[constraints]]
type = "range"
field = "x"
min = 0.0
max = 10.74

[[constraints]]
type = "range"
field = "y"
min = 0.0
max = 58.9

[[constraints]]
type = "range"
field = "z"
min = 0.0
max = 31.8

[[constraints]]
type = "check"
expr = "carat <= depth"

[[constraints]]
type = "check"
expr = "carat <= table"

[[constraints]]
type = "check"
expr = "carat <= price"

[[constraints]]
type = "check"
expr = "depth <= price"

[[constraints]]
type = "check"
expr = "x <= depth"

[[constraints]]
type = "check"
expr = "y <= depth"

[[constraints]]
type = "check"
expr = "z <= depth"

[[constraints]]
type = "check"
expr = "table <= price"

[[constraints]]
type = "check"
expr = "x <= table"

[[constraints]]
type = "check"
expr = "z <= table"

[[constraints]]
type = "check"
expr = "x <= price"

[[constraints]]
type = "check"
expr = "y <= price"

[[constraints]]
type = "check"
expr = "z <= price"
