[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "weight",
]
matrix = [
    [
    1.0,
    -0.4174573199403935,
],
    [
    -0.4174573199403935,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "weight",
]
matrix = [
    [
    1.0,
    -0.40455037229022456,
],
    [
    -0.40455037229022456,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "horsepower",
]
matrix = [
    [
    1.0,
    -0.6891955103342349,
],
    [
    -0.6891955103342349,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "horsepower",
]
matrix = [
    [
    1.0,
    -0.658142304021837,
],
    [
    -0.658142304021837,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "mpg",
]
matrix = [
    [
    1.0,
    0.42028891210165037,
],
    [
    0.42028891210165037,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "mpg",
]
matrix = [
    [
    1.0,
    0.43867747957086217,
],
    [
    0.43867747957086217,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.54368408350093,
],
    [
    -0.54368408350093,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.49651192134583266,
],
    [
    -0.49651192134583266,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.505419489052177,
],
    [
    -0.505419489052177,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "acceleration",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.4741890658657841,
],
    [
    -0.4741890658657841,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "weight",
]
matrix = [
    [
    1.0,
    -0.3065643342832897,
],
    [
    -0.3065643342832897,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "horsepower",
]
matrix = [
    [
    1.0,
    -0.41636147709998783,
],
    [
    -0.41636147709998783,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "horsepower",
]
matrix = [
    [
    1.0,
    -0.3894982985927776,
],
    [
    -0.3894982985927776,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "mpg",
]
matrix = [
    [
    1.0,
    0.5792671330833096,
],
    [
    0.5792671330833096,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "mpg",
]
matrix = [
    [
    1.0,
    0.573468703192175,
],
    [
    0.573468703192175,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.3701641610793245,
],
    [
    -0.3701641610793245,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.30525727049555273,
],
    [
    -0.30525727049555273,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.3487457966135948,
],
    [
    -0.3487457966135948,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "model_year",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.33501238723038046,
],
    [
    -0.33501238723038046,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "horsepower",
]
matrix = [
    [
    1.0,
    0.8645377375741428,
],
    [
    0.8645377375741428,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "horsepower",
]
matrix = [
    [
    1.0,
    0.8788193253461962,
],
    [
    0.8788193253461962,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "mpg",
]
matrix = [
    [
    1.0,
    -0.8317409332443352,
],
    [
    -0.8317409332443352,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "mpg",
]
matrix = [
    [
    1.0,
    -0.8749473981990712,
],
    [
    -0.8749473981990712,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "displacement",
]
matrix = [
    [
    1.0,
    0.9328241468416345,
],
    [
    0.9328241468416345,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "displacement",
]
matrix = [
    [
    1.0,
    0.9459855641801795,
],
    [
    0.9459855641801795,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.8960167954533957,
],
    [
    0.8960167954533957,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "weight",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.8733135587408114,
],
    [
    0.8733135587408114,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "mpg",
]
matrix = [
    [
    1.0,
    -0.7784267838977751,
],
    [
    -0.7784267838977751,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "mpg",
]
matrix = [
    [
    1.0,
    -0.8536164024453882,
],
    [
    -0.8536164024453882,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "displacement",
]
matrix = [
    [
    1.0,
    0.897257001843467,
],
    [
    0.897257001843467,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "displacement",
]
matrix = [
    [
    1.0,
    0.8761707908903554,
],
    [
    0.8761707908903554,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.8429833569186564,
],
    [
    0.8429833569186564,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "horsepower",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.8161884518191116,
],
    [
    0.8161884518191116,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "mpg",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.8042028248058989,
],
    [
    -0.8042028248058989,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "mpg",
    "displacement",
]
matrix = [
    [
    1.0,
    -0.8556920118178749,
],
    [
    -0.8556920118178749,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "mpg",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.7753962854205557,
],
    [
    -0.7753962854205557,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "mpg",
    "cylinders",
]
matrix = [
    [
    1.0,
    -0.8218644914450964,
],
    [
    -0.8218644914450964,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "displacement",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.9507213901392443,
],
    [
    0.9507213901392443,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "displacement",
    "cylinders",
]
matrix = [
    [
    1.0,
    0.9118759147045389,
],
    [
    0.9118759147045389,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "name",
    "origin",
]
matrix = [
    [
    1.0,
    0.9999999999999984,
],
    [
    0.9999999999999984,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "mpg"
given = "origin"

[[correlations.distributions]]
when = "japan"
distribution = "normal"

[correlations.distributions.params]
mean = 30.450632911392397
std_dev = 6.051380706928184

[[correlations.distributions]]
when = "europe"
distribution = "log_normal"

[correlations.distributions.params]
mu = 3.3005717450499628
sigma = 0.235026576032752

[[correlations.distributions]]
when = "usa"
distribution = "log_normal"

[correlations.distributions.params]
mu = 2.9521321458985432
sigma = 0.30648791268494596

[correlations.default]
kind = "gamma"

[correlations.default.params]
scale = 2.5914193569033355
shape = 9.07401297350066

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "displacement"
given = "origin"

[[correlations.distributions]]
when = "usa"
distribution = "uniform"

[correlations.distributions.params]
max = 455.0
min = 85.0

[[correlations.distributions]]
when = "japan"
distribution = "log_normal"

[correlations.distributions.params]
mu = 4.608685402686416
sigma = 0.2121496583603339

[[correlations.distributions]]
when = "europe"
distribution = "log_normal"

[correlations.distributions.params]
mu = 4.673132282374047
sigma = 0.19467613722959695

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 5.123173847894801
sigma = 0.5306108547157526

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "horsepower"
given = "origin"

[[correlations.distributions]]
when = "japan"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 4.356343630928012
sigma = 0.2157666704621968

[[correlations.distributions]]
when = "usa"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 4.726435323609734
sigma = 0.323285562414901

[[correlations.distributions]]
when = "europe"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 4.96983656551339
shape = 16.209551856981427

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 4.587931382423751
sigma = 0.3429406140914995

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "weight"
given = "origin"

[[correlations.distributions]]
when = "europe"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 1825.0
shape = 3.777835375763564

[[correlations.distributions]]
when = "japan"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.695766182943783
sigma = 0.14117838226907867

[[correlations.distributions]]
when = "usa"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 187.14187296622293
shape = 17.964615153308966

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 7.956890111251137
sigma = 0.28031214790157094

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "cylinders"
given = "origin"

[[correlations.distributions]]
when = "usa"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 8.0
min = 4.0

[[correlations.distributions]]
when = "japan"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 1.4025229985735852
sigma = 0.12811434258904958

[[correlations.distributions]]
when = "europe"
distribution = "pareto"
round = true

[correlations.distributions.params]
scale = 4.0
shape = 30.550461447801755

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 8.0
min = 3.0
