[[constraints]]
table = "original"
type = "range"
field = "avail_seat_km_per_week"
min = 259373346.0
max = 7139291291.0

[[constraints]]
table = "original"
type = "range"
field = "incidents_85_99"
min = 0.0
max = 76.0

[[constraints]]
table = "original"
type = "range"
field = "fatal_accidents_85_99"
min = 0.0
max = 14.0

[[constraints]]
table = "original"
type = "range"
field = "fatalities_85_99"
min = 0.0
max = 535.0

[[constraints]]
table = "original"
type = "range"
field = "incidents_00_14"
min = 0.0
max = 24.0

[[constraints]]
table = "original"
type = "range"
field = "fatal_accidents_00_14"
min = 0.0
max = 3.0

[[constraints]]
table = "original"
type = "range"
field = "fatalities_00_14"
min = 0.0
max = 537.0

[[constraints]]
table = "original"
type = "check"
expr = "incidents_85_99 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_85_99 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "fatalities_85_99 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "incidents_00_14 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_00_14 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "fatalities_00_14 <= avail_seat_km_per_week"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_85_99 <= incidents_85_99"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_00_14 <= incidents_85_99"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_85_99 <= fatalities_85_99"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_00_14 <= incidents_00_14"

[[constraints]]
table = "original"
type = "check"
expr = "fatal_accidents_00_14 <= fatalities_00_14"
