[table]
name = "original"
count = 173

[table.stats]
source_rows = 173

[[table.scaling.custom]]
name = "Major_category"
field = "Major_category"
cardinality = 16

[table.sort_by]
column = "Rank"
direction = "asc"

[[columns]]
name = "Rank"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "uniform"
round = true

[columns.generator.params]
max = 173.0
min = 1.0

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 1.0
max = 173.0
mean = 87.0
std = 50.08492787256461

[columns.stats.percentiles]
p25 = 44.0
p50 = 87.0
p75 = 130.0
p95 = 164.0
p99 = 171.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "Major_code"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "uniform"
round = true

[columns.generator.params]
max = 6403.0
min = 1100.0

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 1100.0
max = 6403.0
mean = 3879.815028901734
std = 1687.7531404980978

[columns.stats.percentiles]
p25 = 2403.0
p50 = 3608.0
p75 = 5503.0
p95 = 6205.0
p99 = 6299.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "Major"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_Major.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 173
null_rate = 0.0
min_length = 5
max_length = 65
avg_length = 25.3121387283237

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "Total"
data_type = "int"
nullable = false

[columns.generator]
type = "derived"
expr = "${Men} + ${Women}"

[columns.stats]
distinct_count = 172
null_rate = 0.005780346820809248
min = 124.0
max = 393735.0
mean = 39370.08139534884
std = 63483.49100922603

[columns.stats.percentiles]
p25 = 4626.0
p50 = 15150.0
p75 = 38844.0
p95 = 182621.0
p99 = 280709.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Men"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 8.671720660917384
sigma = 1.5154059993624807

[columns.stats]
distinct_count = 172
null_rate = 0.005780346820809248
min = 119.0
max = 173809.0
mean = 16723.406976744187
std = 28122.433474425

[columns.stats.percentiles]
p25 = 2200.0
p50 = 5521.0
p75 = 14440.0
p95 = 80320.0
p99 = 115030.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Women"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.00004415659365767549

[columns.stats]
distinct_count = 171
null_rate = 0.005780346820809248
min = 0.0
max = 307087.0
mean = 22646.674418604653
std = 41057.330739596655

[columns.stats.percentiles]
p25 = 1784.0
p50 = 8489.0
p75 = 22456.0
p95 = 104114.0
p99 = 168947.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Major_category"
data_type = "string"
nullable = false

[columns.generator]
type = "one_of"

[[columns.generator.choices]]
value = "Engineering"
weight = 0.1676300578034682

[[columns.generator.choices]]
value = "Education"
weight = 0.09248554913294797

[[columns.generator.choices]]
value = "Humanities & Liberal Arts"
weight = 0.08670520231213873

[[columns.generator.choices]]
value = "Biology & Life Science"
weight = 0.08092485549132948

[[columns.generator.choices]]
value = "Business"
weight = 0.07514450867052024

[[columns.generator.choices]]
value = "Health"
weight = 0.06936416184971098

[[columns.generator.choices]]
value = "Computers & Mathematics"
weight = 0.06358381502890173

[[columns.generator.choices]]
value = "Agriculture & Natural Resources"
weight = 0.057803468208092484

[[columns.generator.choices]]
value = "Physical Sciences"
weight = 0.057803468208092484

[[columns.generator.choices]]
value = "Psychology & Social Work"
weight = 0.05202312138728324

[[columns.generator.choices]]
value = "Social Science"
weight = 0.05202312138728324

[[columns.generator.choices]]
value = "Arts"
weight = 0.046242774566473986

[[columns.generator.choices]]
value = "Industrial Arts & Consumer Services"
weight = 0.04046242774566474

[[columns.generator.choices]]
value = "Law & Public Policy"
weight = 0.028901734104046242

[[columns.generator.choices]]
value = "Communications & Journalism"
weight = 0.023121387283236993

[[columns.generator.choices]]
value = "Interdisciplinary"
weight = 0.005780346820809248

[columns.stats]
distinct_count = 16
null_rate = 0.0
min_length = 4
max_length = 35
avg_length = 16.728323699421967

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "ShareWomen"
data_type = "float"
nullable = false
precision = 9

[columns.generator]
type = "derived"
expr = "${Women} / ${Total}"

[columns.stats]
distinct_count = 172
null_rate = 0.005780346820809248
min = 0.0
max = 0.968953683
mean = 0.5222233649593027
std = 0.23120498570746803

[columns.stats.percentiles]
p25 = 0.339670982
p50 = 0.535714286
p75 = 0.702020202
p95 = 0.881293889
p99 = 0.927807246

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "Sample_size"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 4.771570612232312
sigma = 1.5969961869827944

[columns.stats]
distinct_count = 147
null_rate = 0.0
min = 2.0
max = 4212.0
mean = 356.08092485549133
std = 618.3610222824603

[columns.stats.percentiles]
p25 = 39.0
p50 = 130.0
p75 = 338.0
p95 = 1629.0
p99 = 2584.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "Employed"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.00003205871822943961

[columns.stats]
distinct_count = 171
null_rate = 0.0
min = 0.0
max = 307933.0
mean = 31192.763005780347
std = 50675.002240754606

[columns.stats.percentiles]
p25 = 3608.0
p50 = 11797.0
p75 = 31433.0
p95 = 149180.0
p99 = 190183.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "Full_time"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 9.144661534413943
sigma = 1.5047070928103132

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 111.0
max = 251540.0
mean = 26029.306358381502
std = 42869.655091535635

[columns.stats.percentiles]
p25 = 3154.0
p50 = 10048.0
p75 = 25147.0
p95 = 123177.0
p99 = 171385.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Part_time"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.00011321952480521987

[columns.stats]
distinct_count = 170
null_rate = 0.0
min = 0.0
max = 115172.0
mean = 8832.398843930636
std = 14648.179473255246

[columns.stats.percentiles]
p25 = 1030.0
p50 = 3299.0
p75 = 9948.0
p95 = 37965.0
p99 = 57825.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "Full_time_year_round"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 8.84979400738869
sigma = 1.5052264181836452

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 111.0
max = 199897.0
mean = 19694.42774566474
std = 33160.94151435232

[columns.stats.percentiles]
p25 = 2453.0
p50 = 7413.0
p75 = 16891.0
p95 = 88548.0
p99 = 138299.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Unemployed"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.0004138508462412535

[columns.stats]
distinct_count = 161
null_rate = 0.0
min = 0.0
max = 28169.0
mean = 2416.3294797687863
std = 4112.803147955807

[columns.stats.percentiles]
p25 = 304.0
p50 = 893.0
p75 = 2393.0
p95 = 11452.0
p99 = 15022.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "Unemployment_rate"
data_type = "float"
nullable = false
precision = 9

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 0.06819083091329481
std_dev = 0.030243151077978432

[columns.stats]
distinct_count = 169
null_rate = 0.0
min = 0.0
max = 0.177226407
mean = 0.06819083091329481
std = 0.030330939799874303

[columns.stats.percentiles]
p25 = 0.050306435
p50 = 0.067960766
p75 = 0.087557114
p95 = 0.113331949
p99 = 0.151849807

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "Median"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 10.566924343028512
sigma = 0.24960304860715352

[columns.stats]
distinct_count = 59
null_rate = 0.0
min = 22000.0
max = 110000.0
mean = 40151.4450867052
std = 11470.181802133831

[columns.stats.percentiles]
p25 = 33000.0
p50 = 36000.0
p75 = 45000.0
p95 = 60000.0
p99 = 73000.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "P25th"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 10.255065082509615
sigma = 0.2600335650375925

[columns.stats]
distinct_count = 48
null_rate = 0.0
min = 18500.0
max = 95000.0
mean = 29501.445086705204
std = 9166.005235071092

[columns.stats.percentiles]
p25 = 24000.0
p50 = 27000.0
p75 = 33000.0
p95 = 45000.0
p99 = 53000.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "P75th"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "log_normal"
round = true

[columns.generator.params]
mu = 10.814272386154949
sigma = 0.25613749573041017

[columns.stats]
distinct_count = 54
null_rate = 0.0
min = 22000.0
max = 125000.0
mean = 51494.21965317919
std = 14906.279740285894

[columns.stats.percentiles]
p25 = 42000.0
p50 = 47000.0
p75 = 60000.0
p95 = 75000.0
p99 = 105000.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[columns]]
name = "College_jobs"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.00008115146898231367

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 0.0
max = 151643.0
mean = 12322.635838150289
std = 21299.868863290198

[columns.stats.percentiles]
p25 = 1675.0
p50 = 4390.0
p75 = 14444.0
p95 = 40763.0
p99 = 108085.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Non_college_jobs"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.0000752757136181163

[columns.stats]
distinct_count = 173
null_rate = 0.0
min = 0.0
max = 148395.0
mean = 13284.497109826589
std = 23789.655363405003

[columns.stats.percentiles]
p25 = 1591.0
p50 = 4595.0
p75 = 11783.0
p95 = 63946.0
p99 = 100831.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "Low_wage_jobs"
data_type = "int"
nullable = false

[columns.generator]
type = "distribution"
kind = "exponential"
round = true

[columns.generator.params]
lambda = 0.00025913332634322435

[columns.stats]
distinct_count = 166
null_rate = 0.0
min = 0.0
max = 48207.0
mean = 3859.0173410404623
std = 6944.998578928973

[columns.stats.percentiles]
p25 = 340.0
p50 = 1231.0
p75 = 3466.0
p95 = 16839.0
p99 = 28339.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "Rank"
min = 1.0
max = 173.0

[[constraints]]
type = "range"
field = "Major_code"
min = 1100.0
max = 6403.0

[[constraints]]
type = "range"
field = "Total"
min = 124.0
max = 393735.0

[[constraints]]
type = "range"
field = "Men"
min = 119.0
max = 173809.0

[[constraints]]
type = "range"
field = "Women"
min = 0.0
max = 307087.0

[[constraints]]
type = "range"
field = "ShareWomen"
min = 0.0
max = 0.968953683

[[constraints]]
type = "range"
field = "Sample_size"
min = 2.0
max = 4212.0

[[constraints]]
type = "range"
field = "Employed"
min = 0.0
max = 307933.0

[[constraints]]
type = "range"
field = "Full_time"
min = 111.0
max = 251540.0

[[constraints]]
type = "range"
field = "Part_time"
min = 0.0
max = 115172.0

[[constraints]]
type = "range"
field = "Full_time_year_round"
min = 111.0
max = 199897.0

[[constraints]]
type = "range"
field = "Unemployed"
min = 0.0
max = 28169.0

[[constraints]]
type = "range"
field = "Unemployment_rate"
min = 0.0
max = 0.177226407

[[constraints]]
type = "range"
field = "Median"
min = 22000.0
max = 110000.0

[[constraints]]
type = "range"
field = "P25th"
min = 18500.0
max = 95000.0

[[constraints]]
type = "range"
field = "P75th"
min = 22000.0
max = 125000.0

[[constraints]]
type = "range"
field = "College_jobs"
min = 0.0
max = 151643.0

[[constraints]]
type = "range"
field = "Non_college_jobs"
min = 0.0
max = 148395.0

[[constraints]]
type = "range"
field = "Low_wage_jobs"
min = 0.0
max = 48207.0

[[constraints]]
type = "check"
expr = "Rank <= Major_code"

[[constraints]]
type = "check"
expr = "Rank <= Total"

[[constraints]]
type = "check"
expr = "ShareWomen <= Rank"

[[constraints]]
type = "check"
expr = "Rank <= Full_time"

[[constraints]]
type = "check"
expr = "Rank <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Rank"

[[constraints]]
type = "check"
expr = "Rank <= Median"

[[constraints]]
type = "check"
expr = "Rank <= P25th"

[[constraints]]
type = "check"
expr = "Rank <= P75th"

[[constraints]]
type = "check"
expr = "ShareWomen <= Major_code"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Major_code"

[[constraints]]
type = "check"
expr = "Major_code <= Median"

[[constraints]]
type = "check"
expr = "Major_code <= P25th"

[[constraints]]
type = "check"
expr = "Major_code <= P75th"

[[constraints]]
type = "check"
expr = "Men <= Total"

[[constraints]]
type = "check"
expr = "Women <= Total"

[[constraints]]
type = "check"
expr = "ShareWomen <= Total"

[[constraints]]
type = "check"
expr = "Sample_size <= Total"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Total"

[[constraints]]
type = "check"
expr = "ShareWomen <= Men"

[[constraints]]
type = "check"
expr = "Sample_size <= Men"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Men"

[[constraints]]
type = "check"
expr = "ShareWomen <= Women"

[[constraints]]
type = "check"
expr = "ShareWomen <= Sample_size"

[[constraints]]
type = "check"
expr = "ShareWomen <= Full_time"

[[constraints]]
type = "check"
expr = "ShareWomen <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "ShareWomen <= Median"

[[constraints]]
type = "check"
expr = "ShareWomen <= P25th"

[[constraints]]
type = "check"
expr = "ShareWomen <= P75th"

[[constraints]]
type = "check"
expr = "Sample_size <= Full_time"

[[constraints]]
type = "check"
expr = "Sample_size <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Sample_size"

[[constraints]]
type = "check"
expr = "Sample_size <= Median"

[[constraints]]
type = "check"
expr = "Sample_size <= P25th"

[[constraints]]
type = "check"
expr = "Sample_size <= P75th"

[[constraints]]
type = "check"
expr = "Part_time <= Employed"

[[constraints]]
type = "check"
expr = "Unemployed <= Employed"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Employed"

[[constraints]]
type = "check"
expr = "College_jobs <= Employed"

[[constraints]]
type = "check"
expr = "Non_college_jobs <= Employed"

[[constraints]]
type = "check"
expr = "Low_wage_jobs <= Employed"

[[constraints]]
type = "check"
expr = "Part_time <= Full_time"

[[constraints]]
type = "check"
expr = "Full_time_year_round <= Full_time"

[[constraints]]
type = "check"
expr = "Unemployed <= Full_time"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Full_time"

[[constraints]]
type = "check"
expr = "Low_wage_jobs <= Full_time"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Part_time"

[[constraints]]
type = "check"
expr = "Unemployed <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "Low_wage_jobs <= Full_time_year_round"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Unemployed"

[[constraints]]
type = "check"
expr = "Unemployed <= Median"

[[constraints]]
type = "check"
expr = "Unemployed <= P75th"

[[constraints]]
type = "check"
expr = "Unemployed <= Non_college_jobs"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Median"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= P25th"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= P75th"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= College_jobs"

[[constraints]]
type = "check"
expr = "Unemployment_rate <= Non_college_jobs"

[[constraints]]
type = "check"
expr = "P25th <= Median"

[[constraints]]
type = "check"
expr = "Median <= P75th"

[[constraints]]
type = "check"
expr = "P25th <= P75th"

[[constraints]]
type = "check"
expr = "Low_wage_jobs <= Non_college_jobs"
