[[constraints]]
table = "original"
type = "range"
field = "Rank"
min = 0.0

[[constraints]]
table = "original"
type = "range"
field = "Major_code"
min = 1301.0
max = 6199.0

[[constraints]]
table = "original"
type = "range"
field = "Total"
min = 609.0
max = 280709.0

[[constraints]]
table = "original"
type = "range"
field = "Men"
min = 488.0
max = 111762.0

[[constraints]]
table = "original"
type = "range"
field = "Women"
min = 77.0
max = 187621.0

[[constraints]]
table = "original"
type = "range"
field = "ShareWomen"
min = 0.0

[[constraints]]
table = "original"
type = "range"
field = "Median"
min = 0.0

[[constraints]]
table = "original"
type = "check"
expr = "Rank <= Major_code"

[[constraints]]
table = "original"
type = "check"
expr = "Rank <= Total"

[[constraints]]
table = "original"
type = "check"
expr = "Rank <= Men"

[[constraints]]
table = "original"
type = "check"
expr = "Rank <= Women"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Rank"

[[constraints]]
table = "original"
type = "check"
expr = "Rank <= Median"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Major_code"

[[constraints]]
table = "original"
type = "check"
expr = "Major_code <= Median"

[[constraints]]
table = "original"
type = "check"
expr = "Men <= Total"

[[constraints]]
table = "original"
type = "check"
expr = "Women <= Total"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Total"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Men"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Women"

[[constraints]]
table = "original"
type = "check"
expr = "ShareWomen <= Median"
