[table]
name = "original"
count = 5479

[table.stats]
source_rows = 5479

[[table.scaling.custom]]
name = "year"
field = "year"
cardinality = 15

[[table.scaling.custom]]
name = "month"
field = "month"
cardinality = 12

[[table.scaling.custom]]
name = "day_of_week"
field = "day_of_week"
cardinality = 7

[table.sort_by]
column = "year"
direction = "asc"

[[columns]]
name = "year"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 5479

[columns.stats]
distinct_count = 15
null_rate = 0.0
min = 2000.0
max = 2014.0
mean = 2006.99926993977
std = 4.3210852211092075

[columns.stats.percentiles]
p25 = 2003.0
p50 = 2007.0
p75 = 2011.0
p95 = 2014.0
p99 = 2014.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "month"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 5479

[columns.stats]
distinct_count = 12
null_rate = 0.0
min = 1.0
max = 12.0
mean = 6.522723124657785
std = 3.449074592963197

[columns.stats.percentiles]
p25 = 4.0
p50 = 7.0
p75 = 10.0
p95 = 12.0
p99 = 12.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "date_of_month"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 5479

[columns.stats]
distinct_count = 31
null_rate = 0.0
min = 1.0
max = 31.0
mean = 15.730242745026464
std = 8.801151004014331

[columns.stats.percentiles]
p25 = 8.0
p50 = 16.0
p75 = 23.0
p95 = 29.0
p99 = 31.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "day_of_week"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 5479

[columns.stats]
distinct_count = 7
null_rate = 0.0
min = 1.0
max = 7.0
mean = 3.9998174849425077
std = 2.000501936717501

[columns.stats.percentiles]
p25 = 2.0
p50 = 4.0
p75 = 6.0
p95 = 7.0
p99 = 7.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "births"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 4
row_count = 5479

[columns.stats]
distinct_count = 3381
null_rate = 0.0
min = 5728.0
max = 16081.0
mean = 11350.068260631502
std = 2325.821049422689

[columns.stats.percentiles]
p25 = 8740.0
p50 = 12343.0
p75 = 13082.0
p95 = 13974.0
p99 = 14667.0

[columns.traits]
semantic = "integer"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "year"
min = 2000.0
max = 2014.0

[[constraints]]
type = "range"
field = "month"
min = 1.0
max = 12.0

[[constraints]]
type = "range"
field = "date_of_month"
min = 1.0
max = 31.0

[[constraints]]
type = "range"
field = "day_of_week"
min = 1.0
max = 7.0

[[constraints]]
type = "range"
field = "births"
min = 5728.0
max = 16081.0

[[constraints]]
type = "check"
expr = "month <= year"

[[constraints]]
type = "check"
expr = "date_of_month <= year"

[[constraints]]
type = "check"
expr = "day_of_week <= year"

[[constraints]]
type = "check"
expr = "year <= births"

[[constraints]]
type = "check"
expr = "month <= births"

[[constraints]]
type = "check"
expr = "date_of_month <= births"

[[constraints]]
type = "check"
expr = "day_of_week <= births"
