[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "fatalities_85_99",
]
matrix = [
    [
    1.0,
    0.5408664386801441,
],
    [
    0.5408664386801441,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "fatalities_85_99",
]
matrix = [
    [
    1.0,
    0.836670053928162,
],
    [
    0.836670053928162,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "fatal_accidents_00_14",
]
matrix = [
    [
    1.0,
    0.4987577757413317,
],
    [
    0.4987577757413317,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "fatal_accidents_00_14",
]
matrix = [
    [
    1.0,
    0.4938274147445612,
],
    [
    0.4938274147445612,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "avail_seat_km_per_week",
]
matrix = [
    [
    1.0,
    0.46829984685934006,
],
    [
    0.46829984685934006,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "incidents_85_99",
]
matrix = [
    [
    1.0,
    0.8569911061081309,
],
    [
    0.8569911061081309,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "incidents_85_99",
]
matrix = [
    [
    1.0,
    0.8197311791388479,
],
    [
    0.8197311791388479,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "fatalities_00_14",
]
matrix = [
    [
    1.0,
    0.39203774371707906,
],
    [
    0.39203774371707906,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.5729230144414172,
],
    [
    0.5729230144414172,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_85_99",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.34628048355265195,
],
    [
    0.34628048355265195,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatalities_85_99",
    "fatal_accidents_00_14",
]
matrix = [
    [
    1.0,
    0.31122498201618765,
],
    [
    0.31122498201618765,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatalities_85_99",
    "incidents_85_99",
]
matrix = [
    [
    1.0,
    0.6588383881036716,
],
    [
    0.6588383881036716,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "avail_seat_km_per_week",
]
matrix = [
    [
    1.0,
    0.3756728813331892,
],
    [
    0.3756728813331892,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "incidents_85_99",
]
matrix = [
    [
    1.0,
    0.3902488436675696,
],
    [
    0.3902488436675696,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "incidents_85_99",
]
matrix = [
    [
    1.0,
    0.5518616952329267,
],
    [
    0.5518616952329267,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "fatalities_00_14",
]
matrix = [
    [
    1.0,
    0.6958641997699668,
],
    [
    0.6958641997699668,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "fatalities_00_14",
]
matrix = [
    [
    1.0,
    0.9468482655357578,
],
    [
    0.9468482655357578,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.5980711383495719,
],
    [
    0.5980711383495719,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatal_accidents_00_14",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.5568776413676715,
],
    [
    0.5568776413676715,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "avail_seat_km_per_week",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.7259167117625855,
],
    [
    0.7259167117625855,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "avail_seat_km_per_week",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.4610152365077957,
],
    [
    0.4610152365077957,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "incidents_85_99",
    "fatalities_00_14",
]
matrix = [
    [
    1.0,
    0.4564533993526978,
],
    [
    0.4564533993526978,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "incidents_85_99",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.4030088296410955,
],
    [
    0.4030088296410955,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "incidents_85_99",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.495821818541418,
],
    [
    0.495821818541418,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "fatalities_00_14",
    "incidents_00_14",
]
matrix = [
    [
    1.0,
    0.4995836799922703,
],
    [
    0.4995836799922703,
    1.0,
],
]
conditional = []
