[[correlations]]
entity = "original"
fields = [
    "size",
    "total_bill",
]
matrix = [
    [
    1.0,
    0.5983151309049025,
],
    [
    0.5983151309049025,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "size",
    "total_bill",
]
matrix = [
    [
    1.0,
    0.6047911390994543,
],
    [
    0.6047911390994543,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "size",
    "tip",
]
matrix = [
    [
    1.0,
    0.48929877523035775,
],
    [
    0.48929877523035775,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "size",
    "tip",
]
matrix = [
    [
    1.0,
    0.46826792926211475,
],
    [
    0.46826792926211475,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total_bill",
    "tip",
]
matrix = [
    [
    1.0,
    0.6757341092113642,
],
    [
    0.6757341092113642,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "total_bill",
    "tip",
]
matrix = [
    [
    1.0,
    0.6789681219001009,
],
    [
    0.6789681219001009,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "time",
    "day",
]
matrix = [
    [
    1.0,
    0.943295307018853,
],
    [
    0.943295307018853,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "smoker",
    "day",
]
matrix = [
    [
    1.0,
    0.32509277788214896,
],
    [
    0.32509277788214896,
    1.0,
],
]
conditional = []
