[[correlations]]
entity = "original"
fields = [
    "z",
    "carat",
]
matrix = [
    [
    1.0,
    0.9533873805614387,
],
    [
    0.9533873805614387,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "carat",
]
matrix = [
    [
    1.0,
    0.9931834443062174,
],
    [
    0.9931834443062174,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "y",
]
matrix = [
    [
    1.0,
    0.9520057161562895,
],
    [
    0.9520057161562895,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "y",
]
matrix = [
    [
    1.0,
    0.9870675117824327,
],
    [
    0.9870675117824327,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "price",
]
matrix = [
    [
    1.0,
    0.8612494438514684,
],
    [
    0.8612494438514684,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "price",
]
matrix = [
    [
    1.0,
    0.9572322686120686,
],
    [
    0.9572322686120686,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "x",
]
matrix = [
    [
    1.0,
    0.9707717985774705,
],
    [
    0.9707717985774705,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "z",
    "x",
]
matrix = [
    [
    1.0,
    0.9873553172140505,
],
    [
    0.9873553172140505,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "y",
]
matrix = [
    [
    1.0,
    0.9517221990130819,
],
    [
    0.9517221990130819,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "y",
]
matrix = [
    [
    1.0,
    0.9955717485692812,
],
    [
    0.9955717485692812,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "price",
]
matrix = [
    [
    1.0,
    0.9215913011935697,
],
    [
    0.9215913011935697,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "price",
]
matrix = [
    [
    1.0,
    0.9628827988813001,
],
    [
    0.9628827988813001,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "x",
]
matrix = [
    [
    1.0,
    0.9750942267265641,
],
    [
    0.9750942267265641,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "carat",
    "x",
]
matrix = [
    [
    1.0,
    0.9961166041570526,
],
    [
    0.9961166041570526,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "y",
    "price",
]
matrix = [
    [
    1.0,
    0.8654208978642225,
],
    [
    0.8654208978642225,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "y",
    "price",
]
matrix = [
    [
    1.0,
    0.9627188193892315,
],
    [
    0.9627188193892315,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "y",
    "x",
]
matrix = [
    [
    1.0,
    0.9747014796704275,
],
    [
    0.9747014796704275,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "y",
    "x",
]
matrix = [
    [
    1.0,
    0.9978949275849379,
],
    [
    0.9978949275849379,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "price",
    "x",
]
matrix = [
    [
    1.0,
    0.8844351610161778,
],
    [
    0.8844351610161778,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "price",
    "x",
]
matrix = [
    [
    1.0,
    0.9631961087113345,
],
    [
    0.9631961087113345,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "carat"
given = "clarity"

[[correlations.distributions]]
when = "VVS1"
distribution = "pareto"

[correlations.distributions.params]
scale = 0.23
shape = 1.5290342087877415

[[correlations.distributions]]
when = "IF"
distribution = "pareto"

[correlations.distributions.params]
scale = 0.23
shape = 1.534368563592327

[[correlations.distributions]]
when = "SI2"
distribution = "gamma"

[correlations.distributions.params]
scale = 0.2476702994421846
shape = 4.351141290733264

[[correlations.distributions]]
when = "SI1"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.30153069245816827
sigma = 0.5369799534270397

[[correlations.distributions]]
when = "VS1"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.47818393699364115
sigma = 0.5617908825710916

[[correlations.distributions]]
when = "VS2"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.4319771182220129
sigma = 0.5701007090493591

[[correlations.distributions]]
when = "I1"
distribution = "log_normal"

[correlations.distributions.params]
mu = 0.1436717088255041
sigma = 0.4614988620216725

[[correlations.distributions]]
when = "VVS2"
distribution = "pareto"

[correlations.distributions.params]
scale = 0.23
shape = 1.2558870466853695

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = -0.3949669655482774
sigma = 0.5848220841250429

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "price"
given = "clarity"

[[correlations.distributions]]
when = "VS1"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.724773097091837
sigma = 1.0458059559401576

[[correlations.distributions]]
when = "IF"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.405190436660518
sigma = 0.9189940513068667

[[correlations.distributions]]
when = "VS2"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.763029387204058
sigma = 1.0331880059650556

[[correlations.distributions]]
when = "SI2"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 3584.718640119787
shape = 1.4123921885939617

[[correlations.distributions]]
when = "VVS1"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.322970136595668
sigma = 0.8936451661493334

[[correlations.distributions]]
when = "SI1"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.847981042400916
sigma = 0.9891634735554977

[[correlations.distributions]]
when = "VVS2"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.530843457557153
sigma = 1.024375882932501

[[correlations.distributions]]
when = "I1"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 2004.8507834983748
shape = 1.9573370363806657

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 7.786768479077399
sigma = 1.014639937514435

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "carat"
given = "color"

[[correlations.distributions]]
when = "E"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.5595004855016285
sigma = 0.5238619858939542

[[correlations.distributions]]
when = "J"
distribution = "gamma"

[correlations.distributions.params]
scale = 0.30534504531857015
shape = 3.805978744224533

[[correlations.distributions]]
when = "D"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.5525351167344574
sigma = 0.509568951829507

[[correlations.distributions]]
when = "H"
distribution = "gamma"

[correlations.distributions.params]
scale = 0.29793157055115305
shape = 3.060431397925473

[[correlations.distributions]]
when = "G"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.42059409775193307
sigma = 0.5708125363029423

[[correlations.distributions]]
when = "I"
distribution = "gamma"

[correlations.distributions.params]
scale = 0.32658505915395325
shape = 3.1444406420421585

[[correlations.distributions]]
when = "F"
distribution = "log_normal"

[correlations.distributions.params]
mu = -0.44841242369698314
sigma = 0.5389596917099945

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = -0.3949669655482774
sigma = 0.5848220841250429

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "price"
given = "color"

[[correlations.distributions]]
when = "H"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.918445902669146
sigma = 1.0631537395843467

[[correlations.distributions]]
when = "F"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.762439593363952
sigma = 0.9674636914148415

[[correlations.distributions]]
when = "I"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 4378.904006564539
shape = 1.1628194969010919

[[correlations.distributions]]
when = "J"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 3698.56580687781
shape = 1.4394276857377826

[[correlations.distributions]]
when = "E"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.579404675448197
sigma = 0.9253725869219571

[[correlations.distributions]]
when = "D"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.616904920536967
sigma = 0.9262901822353674

[[correlations.distributions]]
when = "G"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.789583395130484
sigma = 1.0276692184519838

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 7.786768479077399
sigma = 1.014639937514435
