[table]
name = "original"
count = 570

[table.stats]
source_rows = 570

[[table.scaling.custom]]
name = "year"
field = "year"
cardinality = 15

[[table.scaling.custom]]
name = "age"
field = "age"
cardinality = 19

[[table.scaling.custom]]
name = "sex"
field = "sex"
cardinality = 2

[table.sort_by]
column = "year"
direction = "asc"

[[columns]]
name = "year"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 570

[columns.stats]
distinct_count = 15
null_rate = 0.0
min = 1850.0
max = 2000.0
mean = 1927.3333333333333
std = 46.726716741182116

[columns.stats.percentiles]
p25 = 1880.0
p50 = 1930.0
p75 = 1970.0
p95 = 2000.0
p99 = 2000.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "age"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 570

[columns.stats]
distinct_count = 19
null_rate = 0.0
min = 0.0
max = 90.0
mean = 45.0
std = 27.41018244983452

[columns.stats.percentiles]
p25 = 20.0
p50 = 45.0
p75 = 70.0
p95 = 90.0
p99 = 90.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "sex"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 570

[columns.stats]
distinct_count = 2
null_rate = 0.0
min = 1.0
max = 2.0
mean = 1.5
std = 0.500439174436886

[columns.stats.percentiles]
p25 = 1.0
p50 = 2.0
p75 = 2.0
p95 = 2.0
p99 = 2.0

[columns.traits]
semantic = "integer"
cardinality = "low"
distribution_shape = "normal"

[[columns]]
name = "people"
data_type = "int"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 3
row_count = 570

[columns.stats]
distinct_count = 570
null_rate = 0.0
min = 5259.0
max = 11635647.0
mean = 3428937.154385965
std = 3101098.438210043

[columns.stats.percentiles]
p25 = 672663.0
p50 = 2548250.0
p75 = 5468378.0
p95 = 9853933.0
p99 = 10756403.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "year"
min = 1850.0
max = 2000.0

[[constraints]]
type = "range"
field = "age"
min = 0.0
max = 90.0

[[constraints]]
type = "range"
field = "sex"
min = 1.0
max = 2.0

[[constraints]]
type = "range"
field = "people"
min = 5259.0
max = 11635647.0

[[constraints]]
type = "check"
expr = "age <= year"

[[constraints]]
type = "check"
expr = "sex <= year"

[[constraints]]
type = "check"
expr = "year <= people"

[[constraints]]
type = "check"
expr = "age <= people"

[[constraints]]
type = "check"
expr = "sex <= people"
