[[correlations]]
entity = "original"
fields = [
    "income",
    "health",
]
matrix = [
    [
    1.0,
    0.6464345423584739,
],
    [
    0.6464345423584739,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "income",
    "health",
]
matrix = [
    [
    1.0,
    0.8317484092334368,
],
    [
    0.8317484092334368,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "region",
    "country",
]
matrix = [
    [
    1.0,
    0.999999999999997,
],
    [
    0.999999999999997,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "population"
given = "region"

[[correlations.distributions]]
when = "sub_saharan_africa"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 15.921832455350092
sigma = 1.5849984037765568

[[correlations.distributions]]
when = "south_asia"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 17.07775496445477
sigma = 2.5814362559798716

[[correlations.distributions]]
when = "europe_central_asia"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 15.738240779172209
sigma = 1.527199695185738

[[correlations.distributions]]
when = "america"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 15.283652423009759
sigma = 2.2696517392345306

[[correlations.distributions]]
when = "middle_east_north_africa"
distribution = "exponential"
round = true

[correlations.distributions.params]
lambda = 0.00000004720213621197386

[[correlations.distributions]]
when = "east_asia_pacific"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 15.510988563473157
sigma = 2.7403168653698153

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 15.773547067647383
sigma = 1.97309649849381

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "income"
given = "region"

[[correlations.distributions]]
when = "europe_central_asia"
distribution = "gamma"
round = true

[correlations.distributions.params]
scale = 10257.978190544849
shape = 2.701742924891904

[[correlations.distributions]]
when = "middle_east_north_africa"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 9.755859551946426
sigma = 1.0462405638661798

[[correlations.distributions]]
when = "sub_saharan_africa"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 7.929661040683373
sigma = 0.9920695927415193

[[correlations.distributions]]
when = "america"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 9.434547745057072
sigma = 0.6552998346136625

[[correlations.distributions]]
when = "east_asia_pacific"
distribution = "log_normal"
round = true

[correlations.distributions.params]
mu = 9.005173023797106
sigma = 1.1587136987262328

[[correlations.distributions]]
when = "south_asia"
distribution = "uniform"
round = true

[correlations.distributions.params]
max = 14408.0
min = 1925.0

[correlations.default]
kind = "log_normal"

[correlations.default.params]
mu = 9.134555954008231
sigma = 1.208425588920513
