[[constraints]]
table = "original"
type = "range"
field = "income"
min = 599.0
max = 132877.0

[[constraints]]
table = "original"
type = "range"
field = "health"
min = 48.5
max = 84.1

[[constraints]]
table = "original"
type = "range"
field = "population"
min = 52993.0
max = 1376048943.0

[[constraints]]
table = "original"
type = "check"
expr = "health <= income"

[[constraints]]
table = "original"
type = "check"
expr = "income <= population"

[[constraints]]
table = "original"
type = "check"
expr = "health <= population"
