[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.8717537758865828,
],
    [
    0.8717537758865828,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_length",
]
matrix = [
    [
    1.0,
    0.8818981264349859,
],
    [
    0.8818981264349859,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.8179411262715759,
],
    [
    0.8179411262715759,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.8342887759080051,
],
    [
    0.8342887759080051,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_width",
    "petal_length",
]
matrix = [
    [
    1.0,
    -0.42844010433054003,
],
    [
    -0.42844010433054003,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_width",
    "petal_length",
]
matrix = [
    [
    1.0,
    -0.30963508601557777,
],
    [
    -0.30963508601557777,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "sepal_width",
    "petal_width",
]
matrix = [
    [
    1.0,
    -0.3661259325364395,
],
    [
    -0.3661259325364395,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.9628654314027955,
],
    [
    0.9628654314027955,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "petal_length",
    "petal_width",
]
matrix = [
    [
    1.0,
    0.9376668235763413,
],
    [
    0.9376668235763413,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "petal_width"
given = "species"

[[correlations.distributions]]
when = "setosa"
distribution = "log_normal"

[correlations.distributions.params]
mu = -1.4846488496657155
sigma = 0.40457810126280963

[[correlations.distributions]]
when = "virginica"
distribution = "uniform"

[correlations.distributions.params]
max = 2.5
min = 1.4

[[correlations.distributions]]
when = "versicolor"
distribution = "uniform"

[correlations.distributions.params]
max = 1.8
min = 1.0

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 2.5
min = 0.1

[[correlations]]
entity = "original"
type = "conditional_distribution"
fields = []
matrix = []
conditional = []
dependent = "petal_length"
given = "species"

[[correlations.distributions]]
when = "setosa"
distribution = "normal"

[correlations.distributions.params]
mean = 1.4620000000000002
std_dev = 0.17191858538273286

[[correlations.distributions]]
when = "versicolor"
distribution = "normal"

[correlations.distributions.params]
mean = 4.26
std_dev = 0.46518813398452025

[[correlations.distributions]]
when = "virginica"
distribution = "log_normal"

[correlations.distributions.params]
mu = 1.7094260198829934
sigma = 0.09680044817909754

[correlations.default]
kind = "uniform"

[correlations.default.params]
max = 6.9
min = 1.0
