[[correlations]]
entity = "original"
fields = [
    "age",
    "people",
]
matrix = [
    [
    1.0,
    -0.6309830433124716,
],
    [
    -0.6309830433124716,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "age",
    "people",
]
matrix = [
    [
    1.0,
    -0.6962082768120974,
],
    [
    -0.6962082768120974,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "people",
]
matrix = [
    [
    1.0,
    0.672588289306252,
],
    [
    0.672588289306252,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "year",
    "people",
]
matrix = [
    [
    1.0,
    0.661700862269158,
],
    [
    0.661700862269158,
    1.0,
],
]
conditional = []
