[table]
name = "original"
count = 6896

[table.stats]
source_rows = 6896

[[table.scaling.custom]]
name = "SEX"
field = "SEX"
cardinality = 4

[table.sort_by]
column = "APPEARANCES"
direction = "desc"

[[columns]]
name = "page_id"
data_type = "int"
nullable = false
primary_key = true

[columns.generator]
type = "sequence"
start = 1
step = 1

[columns.stats]
distinct_count = 6896
null_rate = 0.0
min = 1380.0
max = 404010.0
mean = 147441.20925174013
std = 108388.6311492825

[columns.stats.percentiles]
p25 = 44109.0
p50 = 141268.0
p75 = 213202.0
p95 = 344306.0
p99 = 382168.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "uniform"

[[columns]]
name = "name"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_name.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 6896
null_rate = 0.0
min_length = 10
max_length = 46
avg_length = 23.137470997679813

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "urlslug"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 1

[columns.stats]
distinct_count = 6896
null_rate = 0.0
min_length = 18
max_length = 54
avg_length = 31.181119489559165

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "ID"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 7

[columns.nullable]
probability = 0.29190835266821347

[columns.stats]
distinct_count = 3
null_rate = 0.29190835266821347
min_length = 15
max_length = 16
avg_length = 15.001843129223838

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "ALIGN"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 6

[columns.nullable]
probability = 0.08715197215777262

[columns.stats]
distinct_count = 4
null_rate = 0.08715197215777262
min_length = 14
max_length = 18
avg_length = 14.810802223987292

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "EYE"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 3

[columns.nullable]
probability = 0.5261020881670534

[columns.stats]
distinct_count = 17
null_rate = 0.5261020881670534
min_length = 8
max_length = 18
avg_length = 9.67564259485924

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "HAIR"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 4

[columns.nullable]
probability = 0.3297563805104408

[columns.stats]
distinct_count = 17
null_rate = 0.3297563805104408
min_length = 8
max_length = 21
avg_length = 9.842925140631761

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "SEX"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 5

[columns.nullable]
probability = 0.01812645011600928

[columns.stats]
distinct_count = 4
null_rate = 0.01812645011600928
min_length = 15
max_length = 22
avg_length = 15.599763698124354

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "GSM"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 8

[columns.nullable]
probability = 0.9907192575406032

[columns.stats]
distinct_count = 2
null_rate = 0.9907192575406032
min_length = 19
max_length = 21
avg_length = 20.6875

[columns.traits]
semantic = "name"
pii = true
cardinality = "medium"

[[columns]]
name = "ALIVE"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 9

[columns.stats]
distinct_count = 2
null_rate = 0.0004350348027842227
min_length = 17
max_length = 19
avg_length = 17.491222979834614

[columns.traits]
semantic = "name"
pii = true
cardinality = "low"

[[columns]]
name = "APPEARANCES"
data_type = "int"

[columns.generator]
type = "distribution"
kind = "pareto"
round = true

[columns.generator.params]
scale = 1.0
shape = 0.5229189016414668

[columns.nullable]
probability = 0.051479118329466354

[columns.stats]
distinct_count = 282
null_rate = 0.051479118329466354
min = 1.0
max = 3093.0
mean = 23.62513377159456
std = 87.37850877836887

[columns.stats.percentiles]
p25 = 2.0
p50 = 6.0
p75 = 15.0
p95 = 90.0
p99 = 308.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "long_tail"

[[columns]]
name = "FIRST APPEARANCE"
data_type = "string"

[columns.generator]
type = "tuple_lookup"
source_field = "name"
file = "original__name_urlslug_FIRST_APPEARANCE_EYE_HAIR_SEX_ALIGN_ID_GSM_ALIVE.tsv"
column = 2

[columns.nullable]
probability = 0.010005800464037123

[columns.stats]
distinct_count = 774
null_rate = 0.010005800464037123
min_length = 4
max_length = 15
avg_length = 12.000878863336752

[columns.traits]
semantic = "text"
cardinality = "medium"

[[columns]]
name = "YEAR"
data_type = "int"

[columns.generator]
type = "distribution"
kind = "normal"
round = true

[columns.generator.params]
mean = 1989.7666617840925
std_dev = 16.822962103510303

[columns.nullable]
probability = 0.010005800464037123

[columns.stats]
distinct_count = 79
null_rate = 0.010005800464037123
min = 1935.0
max = 2013.0
mean = 1989.7666617840925
std = 16.82419432926574

[columns.stats.percentiles]
p25 = 1983.0
p50 = 1992.0
p75 = 2003.0
p95 = 2010.0
p99 = 2011.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "page_id"
min = 1380.0
max = 404010.0

[[constraints]]
type = "range"
field = "APPEARANCES"
min = 1.0
max = 3093.0

[[constraints]]
type = "range"
field = "YEAR"
min = 1935.0
max = 2013.0
