[table]
name = "original"
count = 620

[table.stats]
source_rows = 620

[[table.scaling.custom]]
name = "year"
field = "year"
cardinality = 10

[table.sort_by]
column = "country"
direction = "asc"

[[columns]]
name = "_comment"
data_type = "string"

[columns.generator]
type = "one_of"

[[columns.generator.choices]]
value = "Data courtesy of Gapminder.org"
weight = 1.0

[columns.nullable]
probability = 0.9983870967741936

[columns.stats]
distinct_count = 1
null_rate = 0.9983870967741936
min_length = 30
max_length = 30
avg_length = 30.0

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "year"
data_type = "int"
nullable = false

[columns.generator]
type = "one_of"

[[columns.generator.choices]]
value = 2000
weight = 0.1

[[columns.generator.choices]]
value = 1975
weight = 0.1

[[columns.generator.choices]]
value = 1985
weight = 0.1

[[columns.generator.choices]]
value = 1990
weight = 0.1

[[columns.generator.choices]]
value = 1960
weight = 0.1

[[columns.generator.choices]]
value = 1965
weight = 0.1

[[columns.generator.choices]]
value = 1970
weight = 0.1

[[columns.generator.choices]]
value = 1955
weight = 0.1

[[columns.generator.choices]]
value = 1980
weight = 0.1

[[columns.generator.choices]]
value = 1995
weight = 0.1

[columns.stats]
distinct_count = 10
null_rate = 0.0
min = 1955.0
max = 2000.0
mean = 1977.5
std = 14.373002424949107

[columns.stats.percentiles]
p25 = 1965.0
p50 = 1980.0
p75 = 1990.0
p95 = 2000.0
p99 = 2000.0

[columns.traits]
semantic = "integer"
cardinality = "medium"
distribution_shape = "normal"

[[columns]]
name = "fertility"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "uniform"

[columns.generator.params]
max = 8.23
min = 1.03

[columns.stats]
distinct_count = 378
null_rate = 0.0
min = 1.03
max = 8.23
mean = 3.8493548387096794
std = 1.9267510307845221

[columns.stats.percentiles]
p25 = 2.24
p50 = 3.3
p75 = 5.62
p95 = 7.21
p99 = 8.04

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "life_expect"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 66.282935483871
std_dev = 9.50968291400245

[columns.stats]
distinct_count = 562
null_rate = 0.0
min = 27.79
max = 81.57
mean = 66.282935483871
std = 9.517361302749574

[columns.stats.percentiles]
p25 = 61.11
p50 = 69.22
p75 = 73.44
p95 = 77.97
p99 = 79.64

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "n_fertility"
data_type = "float"
precision = 2

[columns.generator]
type = "distribution"
kind = "log_normal"

[columns.generator.params]
mu = 1.184096492435548
sigma = 0.5224644412755822

[columns.nullable]
probability = 0.1

[columns.stats]
distinct_count = 356
null_rate = 0.1
min = 1.03
max = 8.23
mean = 3.7326523297491017
std = 1.901656499173113

[columns.stats.percentiles]
p25 = 2.07
p50 = 3.16
p75 = 5.37
p95 = 7.08
p99 = 8.02

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "n_life_expect"
data_type = "float"
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 67.1327956989248
std_dev = 9.055203343727507

[columns.nullable]
probability = 0.1

[columns.stats]
distinct_count = 509
null_rate = 0.1
min = 27.79
max = 81.57
mean = 67.1327956989248
std = 9.063328247420156

[columns.stats.percentiles]
p25 = 61.99
p50 = 69.81
p75 = 73.82
p95 = 78.04
p99 = 79.64

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[columns]]
name = "country"
data_type = "string"
nullable = false

[columns.generator]
type = "one_of"

[[columns.generator.choices]]
value = "Netherlands"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Belgium"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Austria"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Pakistan"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Kenya"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "El Salvador"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Chile"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Argentina"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Grenada"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "France"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Turkey"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Saudi Arabia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Iran"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Venezuela"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Hong Kong, China"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Croatia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Peru"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Georgia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Rwanda"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "New Zealand"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Barbados"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Egypt"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Bangladesh"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Spain"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Jamaica"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Switzerland"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Brazil"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Dominican Republic"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "South Africa"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "North Korea"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Afghanistan"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "India"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Canada"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "United States"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Colombia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Germany"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Australia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "South Korea"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Costa Rica"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Nigeria"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Indonesia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Portugal"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Cuba"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Iraq"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Finland"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Bahamas"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Mexico"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Lebanon"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Norway"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Poland"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Philippines"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Greece"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "United Kingdom"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Haiti"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Italy"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Ireland"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Bolivia"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Japan"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Iceland"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Israel"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "Ecuador"
weight = 0.016129032258064516

[[columns.generator.choices]]
value = "China"
weight = 0.016129032258064516

[columns.stats]
distinct_count = 62
null_rate = 0.0
min_length = 4
max_length = 18
avg_length = 7.854838709677419

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "p_fertility"
data_type = "float"
precision = 2

[columns.generator]
type = "distribution"
kind = "uniform"

[columns.generator.params]
max = 8.23
min = 1.16

[columns.nullable]
probability = 0.1

[columns.stats]
distinct_count = 360
null_rate = 0.1
min = 1.16
max = 8.23
mean = 3.992491039426524
std = 1.9295063309686518

[columns.stats.percentiles]
p25 = 2.33
p50 = 3.54
p75 = 5.78
p95 = 7.37
p99 = 8.04

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "p_life_expect"
data_type = "float"
precision = 2

[columns.generator]
type = "distribution"
kind = "normal"

[columns.generator.params]
mean = 65.57578853046597
std_dev = 9.449472819401072

[columns.nullable]
probability = 0.1

[columns.stats]
distinct_count = 516
null_rate = 0.1
min = 27.79
max = 80.24
mean = 65.57578853046597
std = 9.457951486714169

[columns.stats.percentiles]
p25 = 60.24
p50 = 68.52
p75 = 72.69
p95 = 77.0
p99 = 78.22

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "skewed"

[[constraints]]
type = "range"
field = "year"
min = 1955.0
max = 2000.0

[[constraints]]
type = "range"
field = "fertility"
min = 1.03
max = 8.23

[[constraints]]
type = "range"
field = "life_expect"
min = 27.79
max = 81.57

[[constraints]]
type = "range"
field = "n_fertility"
min = 1.03
max = 8.23

[[constraints]]
type = "range"
field = "n_life_expect"
min = 27.79
max = 81.57

[[constraints]]
type = "range"
field = "p_fertility"
min = 1.16
max = 8.23

[[constraints]]
type = "range"
field = "p_life_expect"
min = 27.79
max = 80.24

[[constraints]]
type = "check"
expr = "fertility <= year"

[[constraints]]
type = "check"
expr = "life_expect <= year"

[[constraints]]
type = "check"
expr = "n_fertility <= year"

[[constraints]]
type = "check"
expr = "n_life_expect <= year"

[[constraints]]
type = "check"
expr = "p_fertility <= year"

[[constraints]]
type = "check"
expr = "p_life_expect <= year"

[[constraints]]
type = "check"
expr = "fertility <= life_expect"

[[constraints]]
type = "check"
expr = "fertility <= n_life_expect"

[[constraints]]
type = "check"
expr = "fertility <= p_life_expect"

[[constraints]]
type = "check"
expr = "n_fertility <= life_expect"

[[constraints]]
type = "check"
expr = "p_fertility <= life_expect"

[[constraints]]
type = "check"
expr = "n_fertility <= n_life_expect"

[[constraints]]
type = "check"
expr = "n_fertility <= p_life_expect"

[[constraints]]
type = "check"
expr = "p_fertility <= n_life_expect"

[[constraints]]
type = "check"
expr = "p_fertility <= p_life_expect"
