[table]
name = "original"
count = 560

[table.stats]
source_rows = 560

[[columns]]
name = "symbol"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 0
row_count = 560

[columns.stats]
distinct_count = 5
null_rate = 0.0
min_length = 3
max_length = 4
avg_length = 3.780357142857143

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "date"
data_type = "string"
nullable = false

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 1
row_count = 560

[columns.stats]
distinct_count = 123
null_rate = 0.0
min_length = 10
max_length = 10
avg_length = 10.0

[columns.traits]
semantic = "text"
cardinality = "medium"

[[columns]]
name = "price"
data_type = "float"
nullable = false
precision = 2

[columns.generator]
type = "row_lookup"
file = "original__fullrow.tsv"
column = 2
row_count = 560

[columns.stats]
distinct_count = 549
null_rate = 0.0
min = 5.97
max = 707.0
mean = 100.73428571428576
std = 132.55477114107094

[columns.stats.percentiles]
p25 = 24.29
p50 = 57.27
p75 = 100.82
p95 = 458.16
p99 = 574.29

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "price"
min = 5.97
max = 707.0
