[table]
name = "original"
count = 1119

[table.stats]
source_rows = 1119

[[table.scaling.custom]]
name = "answerKey"
field = "answerKey"
cardinality = 8

[[columns]]
name = "id"
data_type = "string"
nullable = false
primary_key = true

[columns.generator]
type = "dictionary"
file = "original_id.dict.txt"
expansion = "shuffle"

[columns.stats]
distinct_count = 1119
null_rate = 0.0
min_length = 8
max_length = 22
avg_length = 15.504021447721179

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "question"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "id"
file = "original__id_question_answerKey.tsv"
column = 1

[columns.stats]
distinct_count = 1118
null_rate = 0.0
min_length = 22
max_length = 683
avg_length = 126.3941018766756

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "choices"
data_type = "string"
nullable = false

[columns.generator]
type = "sequence"
start = 1
step = 1

[columns.stats]
null_rate = 0.0

[columns.traits]

[[columns]]
name = "answerKey"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "id"
file = "original__id_question_answerKey.tsv"
column = 2

[columns.stats]
distinct_count = 8
null_rate = 0.0
min_length = 1
max_length = 1
avg_length = 1.0

[columns.traits]
semantic = "categorical"
cardinality = "low"
