[[correlations]]
entity = "original"
fields = [
    "index",
    "start",
]
matrix = [
    [
    1.0,
    0.9750064306904354,
],
    [
    0.9750064306904354,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "index",
    "start",
]
matrix = [
    [
    1.0,
    1.0,
],
    [
    1.0,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "index",
    "end",
]
matrix = [
    [
    1.0,
    0.9753502890732362,
],
    [
    0.9753502890732362,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "index",
    "end",
]
matrix = [
    [
    1.0,
    0.9982502173821434,
],
    [
    0.9982502173821434,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "start",
    "end",
]
matrix = [
    [
    1.0,
    0.971229404914231,
],
    [
    0.971229404914231,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "start",
    "end",
]
matrix = [
    [
    1.0,
    0.9982502173821434,
],
    [
    0.9982502173821434,
    1.0,
],
]
conditional = []
