[[constraints]]
table = "original"
type = "range"
field = "start"
min = 1565.0
max = 1820.0

[[constraints]]
table = "original"
type = "range"
field = "end"
min = 1603.0
max = 1820.0

[[constraints]]
table = "original"
type = "range"
field = "index"
min = 0.0
max = 11.0

[[constraints]]
table = "original"
type = "check"
expr = "start <= end"

[[constraints]]
table = "original"
type = "check"
expr = "index <= start"

[[constraints]]
table = "original"
type = "check"
expr = "index <= end"
