[[constraints]]
table = "original"
type = "range"
field = "latitude"
min = -14.33102278
max = 71.2854475

[[constraints]]
table = "original"
type = "range"
field = "longitude"
min = -176.6460306
max = 145.7686111
