[table]
name = "original"
count = 50

[table.stats]
source_rows = 50

[table.sort_by]
column = "id"
direction = "asc"

[[columns]]
name = "id"
data_type = "int"
nullable = false
primary_key = true

[columns.generator]
type = "tuple_lookup"
source_field = "state"
file = "original__state_id_rate.tsv"
column = 1

[columns.stats]
distinct_count = 50
null_rate = 0.0
min = 1.0
max = 56.0
mean = 29.32
std = 15.78224266932521

[columns.stats.percentiles]
p25 = 17.0
p50 = 30.0
p75 = 42.0
p95 = 54.0
p99 = 56.0

[columns.traits]
semantic = "integer"
cardinality = "unique"
distribution_shape = "normal"

[[columns]]
name = "rate"
data_type = "float"
nullable = false
precision = 3

[columns.generator]
type = "tuple_lookup"
source_field = "state"
file = "original__state_id_rate.tsv"
column = 2

[columns.stats]
distinct_count = 38
null_rate = 0.0
min = 0.1
max = 0.201
mean = 0.15581999999999996
std = 0.023120527146027706

[columns.stats.percentiles]
p25 = 0.139
p50 = 0.159
p75 = 0.172
p95 = 0.195
p99 = 0.201

[columns.traits]
semantic = "float"
cardinality = "high"
distribution_shape = "normal"

[[columns]]
name = "state"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_state.dict.txt"
expansion = "shuffle"

[columns.stats]
distinct_count = 50
null_rate = 0.0
min_length = 2
max_length = 2
avg_length = 2.0

[columns.traits]
semantic = "text"
cardinality = "unique"

[[constraints]]
type = "range"
field = "id"
min = 0.0

[[constraints]]
type = "range"
field = "rate"
min = 0.1
max = 0.201

[[constraints]]
type = "check"
expr = "rate <= id"
