[table]
name = "original"
count = 3376

[table.stats]
source_rows = 3376

[[table.scaling.custom]]
name = "country"
field = "country"
cardinality = 5

[[columns]]
name = "iata"
data_type = "string"
nullable = false

[columns.generator]
type = "dictionary"
file = "original_iata.dict.txt"
expansion = "sample"

[columns.stats]
distinct_count = 3376
null_rate = 0.0
min_length = 3
max_length = 4
avg_length = 3.012440758293839

[columns.traits]
semantic = "text"
cardinality = "unique"

[[columns]]
name = "name"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 1

[columns.stats]
distinct_count = 3237
null_rate = 0.0
min_length = 3
max_length = 41
avg_length = 16.10308056872038

[columns.traits]
semantic = "text"
pii = true
cardinality = "high"

[[columns]]
name = "city"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 2

[columns.stats]
distinct_count = 2675
null_rate = 0.0
min_length = 2
max_length = 33
avg_length = 8.628554502369669

[columns.traits]
semantic = "text"
cardinality = "high"

[[columns]]
name = "state"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 3

[columns.stats]
distinct_count = 57
null_rate = 0.0
min_length = 2
max_length = 2
avg_length = 2.0

[columns.traits]
semantic = "categorical"
cardinality = "medium"

[[columns]]
name = "country"
data_type = "string"
nullable = false

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 4

[columns.stats]
distinct_count = 5
null_rate = 0.0
min_length = 3
max_length = 30
avg_length = 3.014218009478673

[columns.traits]
semantic = "categorical"
cardinality = "low"

[[columns]]
name = "latitude"
data_type = "float"
nullable = false
precision = 8

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 5

[columns.stats]
distinct_count = 3375
null_rate = 0.0
min = -14.33102278
max = 71.2854475
mean = 40.01120896369369
std = 8.45035675641597

[columns.stats.percentiles]
p25 = 34.68896917
p50 = 39.44136778
p75 = 43.37043194
p95 = 59.5624775
p99 = 66.24956861

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "long_tail"

[[columns]]
name = "longitude"
data_type = "float"
nullable = false
precision = 8

[columns.generator]
type = "tuple_lookup"
source_field = "iata"
file = "original__iata_name_city_state_country_latitude_longitude.tsv"
column = 6

[columns.stats]
distinct_count = 3375
null_rate = 0.0
min = -176.6460306
max = 145.7686111
mean = -98.1904261734448
std = 24.653995395779297

[columns.stats.percentiles]
p25 = -108.5632597
p50 = -93.49568056
p75 = -84.07480528
p95 = -74.00708389
p99 = -68.67433333

[columns.traits]
semantic = "float"
cardinality = "unique"
distribution_shape = "long_tail"

[[constraints]]
type = "range"
field = "latitude"
min = -14.33102278
max = 71.2854475

[[constraints]]
type = "range"
field = "longitude"
min = -176.6460306
max = 145.7686111
