[[correlations]]
entity = "original"
fields = [
    "pulse",
    "",
]
matrix = [
    [
    1.0,
    0.6884887256791001,
],
    [
    0.6884887256791001,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pulse",
    "",
]
matrix = [
    [
    1.0,
    0.7088119056603758,
],
    [
    0.7088119056603758,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pulse",
    "id",
]
matrix = [
    [
    1.0,
    0.679011560894101,
],
    [
    0.679011560894101,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "pulse",
    "id",
]
matrix = [
    [
    1.0,
    0.7011850497173389,
],
    [
    0.7011850497173389,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "",
    "id",
]
matrix = [
    [
    1.0,
    0.9995059898426446,
],
    [
    0.9995059898426446,
    1.0,
],
]
conditional = []

[[correlations]]
entity = "original"
fields = [
    "",
    "id",
]
matrix = [
    [
    1.0,
    0.9995059898426446,
],
    [
    0.9995059898426446,
    1.0,
],
]
conditional = []
